// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ethereumgasfunding"
	"github.com/Wei-Shaw/sub2api/ent/onchainpaymentintent"
)

// EthereumGasFunding is the model entity for the EthereumGasFunding schema.
type EthereumGasFunding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// IntentID holds the value of the "intent_id" field.
	IntentID int64 `json:"intent_id,omitempty"`
	// ChainID holds the value of the "chain_id" field.
	ChainID int64 `json:"chain_id,omitempty"`
	// SponsorAddress holds the value of the "sponsor_address" field.
	SponsorAddress string `json:"sponsor_address,omitempty"`
	// TargetAddress holds the value of the "target_address" field.
	TargetAddress string `json:"target_address,omitempty"`
	// DerivationIndex holds the value of the "derivation_index" field.
	DerivationIndex int64 `json:"derivation_index,omitempty"`
	// AmountWei holds the value of the "amount_wei" field.
	AmountWei string `json:"amount_wei,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// SignerRequestDigest holds the value of the "signer_request_digest" field.
	SignerRequestDigest *string `json:"signer_request_digest,omitempty"`
	// SignerAuditID holds the value of the "signer_audit_id" field.
	SignerAuditID *string `json:"signer_audit_id,omitempty"`
	// Nonce holds the value of the "nonce" field.
	Nonce int64 `json:"nonce,omitempty"`
	// GasLimit holds the value of the "gas_limit" field.
	GasLimit int64 `json:"gas_limit,omitempty"`
	// MaxFeePerGasWei holds the value of the "max_fee_per_gas_wei" field.
	MaxFeePerGasWei string `json:"max_fee_per_gas_wei,omitempty"`
	// MaxPriorityFeePerGasWei holds the value of the "max_priority_fee_per_gas_wei" field.
	MaxPriorityFeePerGasWei string `json:"max_priority_fee_per_gas_wei,omitempty"`
	// TransactionHash holds the value of the "transaction_hash" field.
	TransactionHash *string `json:"transaction_hash,omitempty"`
	// ReplacementOfID holds the value of the "replacement_of_id" field.
	ReplacementOfID *int64 `json:"replacement_of_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Finalized holds the value of the "finalized" field.
	Finalized bool `json:"finalized,omitempty"`
	// FinalizedBlockHeight holds the value of the "finalized_block_height" field.
	FinalizedBlockHeight *int64 `json:"finalized_block_height,omitempty"`
	// FinalizedBlockHash holds the value of the "finalized_block_hash" field.
	FinalizedBlockHash *string `json:"finalized_block_hash,omitempty"`
	// ActualFeeWei holds the value of the "actual_fee_wei" field.
	ActualFeeWei *string `json:"actual_fee_wei,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// FailureCode holds the value of the "failure_code" field.
	FailureCode *string `json:"failure_code,omitempty"`
	// FailureReason holds the value of the "failure_reason" field.
	FailureReason *string `json:"failure_reason,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt *time.Time `json:"next_attempt_at,omitempty"`
	// FinalizedAt holds the value of the "finalized_at" field.
	FinalizedAt *time.Time `json:"finalized_at,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EthereumGasFundingQuery when eager-loading is set.
	Edges        EthereumGasFundingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EthereumGasFundingEdges holds the relations/edges for other nodes in the graph.
type EthereumGasFundingEdges struct {
	// Intent holds the value of the intent edge.
	Intent *OnchainPaymentIntent `json:"intent,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// IntentOrErr returns the Intent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EthereumGasFundingEdges) IntentOrErr() (*OnchainPaymentIntent, error) {
	if e.Intent != nil {
		return e.Intent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: onchainpaymentintent.Label}
	}
	return nil, &NotLoadedError{edge: "intent"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EthereumGasFunding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ethereumgasfunding.FieldFinalized:
			values[i] = new(sql.NullBool)
		case ethereumgasfunding.FieldID, ethereumgasfunding.FieldIntentID, ethereumgasfunding.FieldChainID, ethereumgasfunding.FieldDerivationIndex, ethereumgasfunding.FieldNonce, ethereumgasfunding.FieldGasLimit, ethereumgasfunding.FieldReplacementOfID, ethereumgasfunding.FieldFinalizedBlockHeight, ethereumgasfunding.FieldRetryCount, ethereumgasfunding.FieldVersion:
			values[i] = new(sql.NullInt64)
		case ethereumgasfunding.FieldSponsorAddress, ethereumgasfunding.FieldTargetAddress, ethereumgasfunding.FieldAmountWei, ethereumgasfunding.FieldIdempotencyKey, ethereumgasfunding.FieldSignerRequestDigest, ethereumgasfunding.FieldSignerAuditID, ethereumgasfunding.FieldMaxFeePerGasWei, ethereumgasfunding.FieldMaxPriorityFeePerGasWei, ethereumgasfunding.FieldTransactionHash, ethereumgasfunding.FieldStatus, ethereumgasfunding.FieldFinalizedBlockHash, ethereumgasfunding.FieldActualFeeWei, ethereumgasfunding.FieldFailureCode, ethereumgasfunding.FieldFailureReason:
			values[i] = new(sql.NullString)
		case ethereumgasfunding.FieldCreatedAt, ethereumgasfunding.FieldUpdatedAt, ethereumgasfunding.FieldNextAttemptAt, ethereumgasfunding.FieldFinalizedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EthereumGasFunding fields.
func (_m *EthereumGasFunding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ethereumgasfunding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ethereumgasfunding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ethereumgasfunding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ethereumgasfunding.FieldIntentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field intent_id", values[i])
			} else if value.Valid {
				_m.IntentID = value.Int64
			}
		case ethereumgasfunding.FieldChainID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chain_id", values[i])
			} else if value.Valid {
				_m.ChainID = value.Int64
			}
		case ethereumgasfunding.FieldSponsorAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sponsor_address", values[i])
			} else if value.Valid {
				_m.SponsorAddress = value.String
			}
		case ethereumgasfunding.FieldTargetAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_address", values[i])
			} else if value.Valid {
				_m.TargetAddress = value.String
			}
		case ethereumgasfunding.FieldDerivationIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field derivation_index", values[i])
			} else if value.Valid {
				_m.DerivationIndex = value.Int64
			}
		case ethereumgasfunding.FieldAmountWei:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount_wei", values[i])
			} else if value.Valid {
				_m.AmountWei = value.String
			}
		case ethereumgasfunding.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case ethereumgasfunding.FieldSignerRequestDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signer_request_digest", values[i])
			} else if value.Valid {
				_m.SignerRequestDigest = new(string)
				*_m.SignerRequestDigest = value.String
			}
		case ethereumgasfunding.FieldSignerAuditID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signer_audit_id", values[i])
			} else if value.Valid {
				_m.SignerAuditID = new(string)
				*_m.SignerAuditID = value.String
			}
		case ethereumgasfunding.FieldNonce:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field nonce", values[i])
			} else if value.Valid {
				_m.Nonce = value.Int64
			}
		case ethereumgasfunding.FieldGasLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gas_limit", values[i])
			} else if value.Valid {
				_m.GasLimit = value.Int64
			}
		case ethereumgasfunding.FieldMaxFeePerGasWei:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field max_fee_per_gas_wei", values[i])
			} else if value.Valid {
				_m.MaxFeePerGasWei = value.String
			}
		case ethereumgasfunding.FieldMaxPriorityFeePerGasWei:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field max_priority_fee_per_gas_wei", values[i])
			} else if value.Valid {
				_m.MaxPriorityFeePerGasWei = value.String
			}
		case ethereumgasfunding.FieldTransactionHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_hash", values[i])
			} else if value.Valid {
				_m.TransactionHash = new(string)
				*_m.TransactionHash = value.String
			}
		case ethereumgasfunding.FieldReplacementOfID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field replacement_of_id", values[i])
			} else if value.Valid {
				_m.ReplacementOfID = new(int64)
				*_m.ReplacementOfID = value.Int64
			}
		case ethereumgasfunding.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case ethereumgasfunding.FieldFinalized:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field finalized", values[i])
			} else if value.Valid {
				_m.Finalized = value.Bool
			}
		case ethereumgasfunding.FieldFinalizedBlockHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field finalized_block_height", values[i])
			} else if value.Valid {
				_m.FinalizedBlockHeight = new(int64)
				*_m.FinalizedBlockHeight = value.Int64
			}
		case ethereumgasfunding.FieldFinalizedBlockHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field finalized_block_hash", values[i])
			} else if value.Valid {
				_m.FinalizedBlockHash = new(string)
				*_m.FinalizedBlockHash = value.String
			}
		case ethereumgasfunding.FieldActualFeeWei:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actual_fee_wei", values[i])
			} else if value.Valid {
				_m.ActualFeeWei = new(string)
				*_m.ActualFeeWei = value.String
			}
		case ethereumgasfunding.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case ethereumgasfunding.FieldFailureCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_code", values[i])
			} else if value.Valid {
				_m.FailureCode = new(string)
				*_m.FailureCode = value.String
			}
		case ethereumgasfunding.FieldFailureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_reason", values[i])
			} else if value.Valid {
				_m.FailureReason = new(string)
				*_m.FailureReason = value.String
			}
		case ethereumgasfunding.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = new(time.Time)
				*_m.NextAttemptAt = value.Time
			}
		case ethereumgasfunding.FieldFinalizedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finalized_at", values[i])
			} else if value.Valid {
				_m.FinalizedAt = new(time.Time)
				*_m.FinalizedAt = value.Time
			}
		case ethereumgasfunding.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EthereumGasFunding.
// This includes values selected through modifiers, order, etc.
func (_m *EthereumGasFunding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIntent queries the "intent" edge of the EthereumGasFunding entity.
func (_m *EthereumGasFunding) QueryIntent() *OnchainPaymentIntentQuery {
	return NewEthereumGasFundingClient(_m.config).QueryIntent(_m)
}

// Update returns a builder for updating this EthereumGasFunding.
// Note that you need to call EthereumGasFunding.Unwrap() before calling this method if this EthereumGasFunding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EthereumGasFunding) Update() *EthereumGasFundingUpdateOne {
	return NewEthereumGasFundingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EthereumGasFunding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EthereumGasFunding) Unwrap() *EthereumGasFunding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EthereumGasFunding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EthereumGasFunding) String() string {
	var builder strings.Builder
	builder.WriteString("EthereumGasFunding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("intent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntentID))
	builder.WriteString(", ")
	builder.WriteString("chain_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChainID))
	builder.WriteString(", ")
	builder.WriteString("sponsor_address=")
	builder.WriteString(_m.SponsorAddress)
	builder.WriteString(", ")
	builder.WriteString("target_address=")
	builder.WriteString(_m.TargetAddress)
	builder.WriteString(", ")
	builder.WriteString("derivation_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.DerivationIndex))
	builder.WriteString(", ")
	builder.WriteString("amount_wei=")
	builder.WriteString(_m.AmountWei)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	if v := _m.SignerRequestDigest; v != nil {
		builder.WriteString("signer_request_digest=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SignerAuditID; v != nil {
		builder.WriteString("signer_audit_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("nonce=")
	builder.WriteString(fmt.Sprintf("%v", _m.Nonce))
	builder.WriteString(", ")
	builder.WriteString("gas_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.GasLimit))
	builder.WriteString(", ")
	builder.WriteString("max_fee_per_gas_wei=")
	builder.WriteString(_m.MaxFeePerGasWei)
	builder.WriteString(", ")
	builder.WriteString("max_priority_fee_per_gas_wei=")
	builder.WriteString(_m.MaxPriorityFeePerGasWei)
	builder.WriteString(", ")
	if v := _m.TransactionHash; v != nil {
		builder.WriteString("transaction_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReplacementOfID; v != nil {
		builder.WriteString("replacement_of_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("finalized=")
	builder.WriteString(fmt.Sprintf("%v", _m.Finalized))
	builder.WriteString(", ")
	if v := _m.FinalizedBlockHeight; v != nil {
		builder.WriteString("finalized_block_height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FinalizedBlockHash; v != nil {
		builder.WriteString("finalized_block_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ActualFeeWei; v != nil {
		builder.WriteString("actual_fee_wei=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	if v := _m.FailureCode; v != nil {
		builder.WriteString("failure_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FailureReason; v != nil {
		builder.WriteString("failure_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.NextAttemptAt; v != nil {
		builder.WriteString("next_attempt_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinalizedAt; v != nil {
		builder.WriteString("finalized_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// EthereumGasFundings is a parsable slice of EthereumGasFunding.
type EthereumGasFundings []*EthereumGasFunding
