// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ethereumnoncestate"
)

// EthereumNonceState is the model entity for the EthereumNonceState schema.
type EthereumNonceState struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ChainID holds the value of the "chain_id" field.
	ChainID int64 `json:"chain_id,omitempty"`
	// SenderAddress holds the value of the "sender_address" field.
	SenderAddress string `json:"sender_address,omitempty"`
	// NextNonce holds the value of the "next_nonce" field.
	NextNonce int64 `json:"next_nonce,omitempty"`
	// ObservedPendingNonce holds the value of the "observed_pending_nonce" field.
	ObservedPendingNonce int64 `json:"observed_pending_nonce,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LeaseOwner holds the value of the "lease_owner" field.
	LeaseOwner *string `json:"lease_owner,omitempty"`
	// LeaseUntil holds the value of the "lease_until" field.
	LeaseUntil *time.Time `json:"lease_until,omitempty"`
	// LastReconciledAt holds the value of the "last_reconciled_at" field.
	LastReconciledAt *time.Time `json:"last_reconciled_at,omitempty"`
	// LastErrorCode holds the value of the "last_error_code" field.
	LastErrorCode *string `json:"last_error_code,omitempty"`
	// LastErrorMessage holds the value of the "last_error_message" field.
	LastErrorMessage *string `json:"last_error_message,omitempty"`
	// Version holds the value of the "version" field.
	Version      int `json:"version,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EthereumNonceState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ethereumnoncestate.FieldID, ethereumnoncestate.FieldChainID, ethereumnoncestate.FieldNextNonce, ethereumnoncestate.FieldObservedPendingNonce, ethereumnoncestate.FieldVersion:
			values[i] = new(sql.NullInt64)
		case ethereumnoncestate.FieldSenderAddress, ethereumnoncestate.FieldStatus, ethereumnoncestate.FieldLeaseOwner, ethereumnoncestate.FieldLastErrorCode, ethereumnoncestate.FieldLastErrorMessage:
			values[i] = new(sql.NullString)
		case ethereumnoncestate.FieldCreatedAt, ethereumnoncestate.FieldUpdatedAt, ethereumnoncestate.FieldLeaseUntil, ethereumnoncestate.FieldLastReconciledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EthereumNonceState fields.
func (_m *EthereumNonceState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ethereumnoncestate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ethereumnoncestate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ethereumnoncestate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ethereumnoncestate.FieldChainID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chain_id", values[i])
			} else if value.Valid {
				_m.ChainID = value.Int64
			}
		case ethereumnoncestate.FieldSenderAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_address", values[i])
			} else if value.Valid {
				_m.SenderAddress = value.String
			}
		case ethereumnoncestate.FieldNextNonce:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field next_nonce", values[i])
			} else if value.Valid {
				_m.NextNonce = value.Int64
			}
		case ethereumnoncestate.FieldObservedPendingNonce:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field observed_pending_nonce", values[i])
			} else if value.Valid {
				_m.ObservedPendingNonce = value.Int64
			}
		case ethereumnoncestate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case ethereumnoncestate.FieldLeaseOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lease_owner", values[i])
			} else if value.Valid {
				_m.LeaseOwner = new(string)
				*_m.LeaseOwner = value.String
			}
		case ethereumnoncestate.FieldLeaseUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_until", values[i])
			} else if value.Valid {
				_m.LeaseUntil = new(time.Time)
				*_m.LeaseUntil = value.Time
			}
		case ethereumnoncestate.FieldLastReconciledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_reconciled_at", values[i])
			} else if value.Valid {
				_m.LastReconciledAt = new(time.Time)
				*_m.LastReconciledAt = value.Time
			}
		case ethereumnoncestate.FieldLastErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_code", values[i])
			} else if value.Valid {
				_m.LastErrorCode = new(string)
				*_m.LastErrorCode = value.String
			}
		case ethereumnoncestate.FieldLastErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_message", values[i])
			} else if value.Valid {
				_m.LastErrorMessage = new(string)
				*_m.LastErrorMessage = value.String
			}
		case ethereumnoncestate.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EthereumNonceState.
// This includes values selected through modifiers, order, etc.
func (_m *EthereumNonceState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this EthereumNonceState.
// Note that you need to call EthereumNonceState.Unwrap() before calling this method if this EthereumNonceState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EthereumNonceState) Update() *EthereumNonceStateUpdateOne {
	return NewEthereumNonceStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EthereumNonceState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EthereumNonceState) Unwrap() *EthereumNonceState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EthereumNonceState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EthereumNonceState) String() string {
	var builder strings.Builder
	builder.WriteString("EthereumNonceState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("chain_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChainID))
	builder.WriteString(", ")
	builder.WriteString("sender_address=")
	builder.WriteString(_m.SenderAddress)
	builder.WriteString(", ")
	builder.WriteString("next_nonce=")
	builder.WriteString(fmt.Sprintf("%v", _m.NextNonce))
	builder.WriteString(", ")
	builder.WriteString("observed_pending_nonce=")
	builder.WriteString(fmt.Sprintf("%v", _m.ObservedPendingNonce))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LeaseOwner; v != nil {
		builder.WriteString("lease_owner=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LeaseUntil; v != nil {
		builder.WriteString("lease_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastReconciledAt; v != nil {
		builder.WriteString("last_reconciled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastErrorCode; v != nil {
		builder.WriteString("last_error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastErrorMessage; v != nil {
		builder.WriteString("last_error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// EthereumNonceStates is a parsable slice of EthereumNonceState.
type EthereumNonceStates []*EthereumNonceState
