// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/onchaindeposit"
	"github.com/Wei-Shaw/sub2api/ent/onchainpaymentintent"
)

// OnchainDepositCreate is the builder for creating a OnchainDeposit entity.
type OnchainDepositCreate struct {
	config
	mutation *OnchainDepositMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OnchainDepositCreate) SetCreatedAt(v time.Time) *OnchainDepositCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableCreatedAt(v *time.Time) *OnchainDepositCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OnchainDepositCreate) SetUpdatedAt(v time.Time) *OnchainDepositCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableUpdatedAt(v *time.Time) *OnchainDepositCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetIntentID sets the "intent_id" field.
func (_c *OnchainDepositCreate) SetIntentID(v int64) *OnchainDepositCreate {
	_c.mutation.SetIntentID(v)
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *OnchainDepositCreate) SetPaymentOrderID(v int64) *OnchainDepositCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OnchainDepositCreate) SetUserID(v int64) *OnchainDepositCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNetwork sets the "network" field.
func (_c *OnchainDepositCreate) SetNetwork(v string) *OnchainDepositCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetChainID sets the "chain_id" field.
func (_c *OnchainDepositCreate) SetChainID(v int64) *OnchainDepositCreate {
	_c.mutation.SetChainID(v)
	return _c
}

// SetTransactionID sets the "transaction_id" field.
func (_c *OnchainDepositCreate) SetTransactionID(v string) *OnchainDepositCreate {
	_c.mutation.SetTransactionID(v)
	return _c
}

// SetLogIndex sets the "log_index" field.
func (_c *OnchainDepositCreate) SetLogIndex(v int64) *OnchainDepositCreate {
	_c.mutation.SetLogIndex(v)
	return _c
}

// SetTransactionIndex sets the "transaction_index" field.
func (_c *OnchainDepositCreate) SetTransactionIndex(v int64) *OnchainDepositCreate {
	_c.mutation.SetTransactionIndex(v)
	return _c
}

// SetNillableTransactionIndex sets the "transaction_index" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableTransactionIndex(v *int64) *OnchainDepositCreate {
	if v != nil {
		_c.SetTransactionIndex(*v)
	}
	return _c
}

// SetBlockHeight sets the "block_height" field.
func (_c *OnchainDepositCreate) SetBlockHeight(v int64) *OnchainDepositCreate {
	_c.mutation.SetBlockHeight(v)
	return _c
}

// SetBlockHash sets the "block_hash" field.
func (_c *OnchainDepositCreate) SetBlockHash(v string) *OnchainDepositCreate {
	_c.mutation.SetBlockHash(v)
	return _c
}

// SetTokenContract sets the "token_contract" field.
func (_c *OnchainDepositCreate) SetTokenContract(v string) *OnchainDepositCreate {
	_c.mutation.SetTokenContract(v)
	return _c
}

// SetFromAddress sets the "from_address" field.
func (_c *OnchainDepositCreate) SetFromAddress(v string) *OnchainDepositCreate {
	_c.mutation.SetFromAddress(v)
	return _c
}

// SetToAddress sets the "to_address" field.
func (_c *OnchainDepositCreate) SetToAddress(v string) *OnchainDepositCreate {
	_c.mutation.SetToAddress(v)
	return _c
}

// SetAmountRaw sets the "amount_raw" field.
func (_c *OnchainDepositCreate) SetAmountRaw(v string) *OnchainDepositCreate {
	_c.mutation.SetAmountRaw(v)
	return _c
}

// SetTransactionTime sets the "transaction_time" field.
func (_c *OnchainDepositCreate) SetTransactionTime(v time.Time) *OnchainDepositCreate {
	_c.mutation.SetTransactionTime(v)
	return _c
}

// SetReceiptSuccess sets the "receipt_success" field.
func (_c *OnchainDepositCreate) SetReceiptSuccess(v bool) *OnchainDepositCreate {
	_c.mutation.SetReceiptSuccess(v)
	return _c
}

// SetFinalized sets the "finalized" field.
func (_c *OnchainDepositCreate) SetFinalized(v bool) *OnchainDepositCreate {
	_c.mutation.SetFinalized(v)
	return _c
}

// SetNillableFinalized sets the "finalized" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableFinalized(v *bool) *OnchainDepositCreate {
	if v != nil {
		_c.SetFinalized(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OnchainDepositCreate) SetStatus(v string) *OnchainDepositCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableStatus(v *string) *OnchainDepositCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetValidationError sets the "validation_error" field.
func (_c *OnchainDepositCreate) SetValidationError(v string) *OnchainDepositCreate {
	_c.mutation.SetValidationError(v)
	return _c
}

// SetNillableValidationError sets the "validation_error" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableValidationError(v *string) *OnchainDepositCreate {
	if v != nil {
		_c.SetValidationError(*v)
	}
	return _c
}

// SetCreditAuditRef sets the "credit_audit_ref" field.
func (_c *OnchainDepositCreate) SetCreditAuditRef(v string) *OnchainDepositCreate {
	_c.mutation.SetCreditAuditRef(v)
	return _c
}

// SetNillableCreditAuditRef sets the "credit_audit_ref" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableCreditAuditRef(v *string) *OnchainDepositCreate {
	if v != nil {
		_c.SetCreditAuditRef(*v)
	}
	return _c
}

// SetCreditedAt sets the "credited_at" field.
func (_c *OnchainDepositCreate) SetCreditedAt(v time.Time) *OnchainDepositCreate {
	_c.mutation.SetCreditedAt(v)
	return _c
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableCreditedAt(v *time.Time) *OnchainDepositCreate {
	if v != nil {
		_c.SetCreditedAt(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *OnchainDepositCreate) SetVersion(v int) *OnchainDepositCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *OnchainDepositCreate) SetNillableVersion(v *int) *OnchainDepositCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetIntent sets the "intent" edge to the OnchainPaymentIntent entity.
func (_c *OnchainDepositCreate) SetIntent(v *OnchainPaymentIntent) *OnchainDepositCreate {
	return _c.SetIntentID(v.ID)
}

// Mutation returns the OnchainDepositMutation object of the builder.
func (_c *OnchainDepositCreate) Mutation() *OnchainDepositMutation {
	return _c.mutation
}

// Save creates the OnchainDeposit in the database.
func (_c *OnchainDepositCreate) Save(ctx context.Context) (*OnchainDeposit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OnchainDepositCreate) SaveX(ctx context.Context) *OnchainDeposit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OnchainDepositCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OnchainDepositCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OnchainDepositCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := onchaindeposit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := onchaindeposit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TransactionIndex(); !ok {
		v := onchaindeposit.DefaultTransactionIndex
		_c.mutation.SetTransactionIndex(v)
	}
	if _, ok := _c.mutation.Finalized(); !ok {
		v := onchaindeposit.DefaultFinalized
		_c.mutation.SetFinalized(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := onchaindeposit.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := onchaindeposit.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OnchainDepositCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OnchainDeposit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OnchainDeposit.updated_at"`)}
	}
	if _, ok := _c.mutation.IntentID(); !ok {
		return &ValidationError{Name: "intent_id", err: errors.New(`ent: missing required field "OnchainDeposit.intent_id"`)}
	}
	if v, ok := _c.mutation.IntentID(); ok {
		if err := onchaindeposit.IntentIDValidator(v); err != nil {
			return &ValidationError{Name: "intent_id", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.intent_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentOrderID(); !ok {
		return &ValidationError{Name: "payment_order_id", err: errors.New(`ent: missing required field "OnchainDeposit.payment_order_id"`)}
	}
	if v, ok := _c.mutation.PaymentOrderID(); ok {
		if err := onchaindeposit.PaymentOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_order_id", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.payment_order_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OnchainDeposit.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := onchaindeposit.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "OnchainDeposit.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := onchaindeposit.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChainID(); !ok {
		return &ValidationError{Name: "chain_id", err: errors.New(`ent: missing required field "OnchainDeposit.chain_id"`)}
	}
	if v, ok := _c.mutation.ChainID(); ok {
		if err := onchaindeposit.ChainIDValidator(v); err != nil {
			return &ValidationError{Name: "chain_id", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.chain_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TransactionID(); !ok {
		return &ValidationError{Name: "transaction_id", err: errors.New(`ent: missing required field "OnchainDeposit.transaction_id"`)}
	}
	if v, ok := _c.mutation.TransactionID(); ok {
		if err := onchaindeposit.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.transaction_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LogIndex(); !ok {
		return &ValidationError{Name: "log_index", err: errors.New(`ent: missing required field "OnchainDeposit.log_index"`)}
	}
	if v, ok := _c.mutation.LogIndex(); ok {
		if err := onchaindeposit.LogIndexValidator(v); err != nil {
			return &ValidationError{Name: "log_index", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.log_index": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TransactionIndex(); !ok {
		return &ValidationError{Name: "transaction_index", err: errors.New(`ent: missing required field "OnchainDeposit.transaction_index"`)}
	}
	if v, ok := _c.mutation.TransactionIndex(); ok {
		if err := onchaindeposit.TransactionIndexValidator(v); err != nil {
			return &ValidationError{Name: "transaction_index", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.transaction_index": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BlockHeight(); !ok {
		return &ValidationError{Name: "block_height", err: errors.New(`ent: missing required field "OnchainDeposit.block_height"`)}
	}
	if v, ok := _c.mutation.BlockHeight(); ok {
		if err := onchaindeposit.BlockHeightValidator(v); err != nil {
			return &ValidationError{Name: "block_height", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.block_height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BlockHash(); !ok {
		return &ValidationError{Name: "block_hash", err: errors.New(`ent: missing required field "OnchainDeposit.block_hash"`)}
	}
	if v, ok := _c.mutation.BlockHash(); ok {
		if err := onchaindeposit.BlockHashValidator(v); err != nil {
			return &ValidationError{Name: "block_hash", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.block_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenContract(); !ok {
		return &ValidationError{Name: "token_contract", err: errors.New(`ent: missing required field "OnchainDeposit.token_contract"`)}
	}
	if v, ok := _c.mutation.TokenContract(); ok {
		if err := onchaindeposit.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.token_contract": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromAddress(); !ok {
		return &ValidationError{Name: "from_address", err: errors.New(`ent: missing required field "OnchainDeposit.from_address"`)}
	}
	if v, ok := _c.mutation.FromAddress(); ok {
		if err := onchaindeposit.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.from_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToAddress(); !ok {
		return &ValidationError{Name: "to_address", err: errors.New(`ent: missing required field "OnchainDeposit.to_address"`)}
	}
	if v, ok := _c.mutation.ToAddress(); ok {
		if err := onchaindeposit.ToAddressValidator(v); err != nil {
			return &ValidationError{Name: "to_address", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.to_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountRaw(); !ok {
		return &ValidationError{Name: "amount_raw", err: errors.New(`ent: missing required field "OnchainDeposit.amount_raw"`)}
	}
	if _, ok := _c.mutation.TransactionTime(); !ok {
		return &ValidationError{Name: "transaction_time", err: errors.New(`ent: missing required field "OnchainDeposit.transaction_time"`)}
	}
	if _, ok := _c.mutation.ReceiptSuccess(); !ok {
		return &ValidationError{Name: "receipt_success", err: errors.New(`ent: missing required field "OnchainDeposit.receipt_success"`)}
	}
	if _, ok := _c.mutation.Finalized(); !ok {
		return &ValidationError{Name: "finalized", err: errors.New(`ent: missing required field "OnchainDeposit.finalized"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OnchainDeposit.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := onchaindeposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CreditAuditRef(); ok {
		if err := onchaindeposit.CreditAuditRefValidator(v); err != nil {
			return &ValidationError{Name: "credit_audit_ref", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.credit_audit_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "OnchainDeposit.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := onchaindeposit.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.version": %w`, err)}
		}
	}
	if len(_c.mutation.IntentIDs()) == 0 {
		return &ValidationError{Name: "intent", err: errors.New(`ent: missing required edge "OnchainDeposit.intent"`)}
	}
	return nil
}

func (_c *OnchainDepositCreate) sqlSave(ctx context.Context) (*OnchainDeposit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OnchainDepositCreate) createSpec() (*OnchainDeposit, *sqlgraph.CreateSpec) {
	var (
		_node = &OnchainDeposit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(onchaindeposit.Table, sqlgraph.NewFieldSpec(onchaindeposit.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(onchaindeposit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(onchaindeposit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(onchaindeposit.FieldPaymentOrderID, field.TypeInt64, value)
		_node.PaymentOrderID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(onchaindeposit.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(onchaindeposit.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.ChainID(); ok {
		_spec.SetField(onchaindeposit.FieldChainID, field.TypeInt64, value)
		_node.ChainID = value
	}
	if value, ok := _c.mutation.TransactionID(); ok {
		_spec.SetField(onchaindeposit.FieldTransactionID, field.TypeString, value)
		_node.TransactionID = value
	}
	if value, ok := _c.mutation.LogIndex(); ok {
		_spec.SetField(onchaindeposit.FieldLogIndex, field.TypeInt64, value)
		_node.LogIndex = value
	}
	if value, ok := _c.mutation.TransactionIndex(); ok {
		_spec.SetField(onchaindeposit.FieldTransactionIndex, field.TypeInt64, value)
		_node.TransactionIndex = value
	}
	if value, ok := _c.mutation.BlockHeight(); ok {
		_spec.SetField(onchaindeposit.FieldBlockHeight, field.TypeInt64, value)
		_node.BlockHeight = value
	}
	if value, ok := _c.mutation.BlockHash(); ok {
		_spec.SetField(onchaindeposit.FieldBlockHash, field.TypeString, value)
		_node.BlockHash = value
	}
	if value, ok := _c.mutation.TokenContract(); ok {
		_spec.SetField(onchaindeposit.FieldTokenContract, field.TypeString, value)
		_node.TokenContract = value
	}
	if value, ok := _c.mutation.FromAddress(); ok {
		_spec.SetField(onchaindeposit.FieldFromAddress, field.TypeString, value)
		_node.FromAddress = value
	}
	if value, ok := _c.mutation.ToAddress(); ok {
		_spec.SetField(onchaindeposit.FieldToAddress, field.TypeString, value)
		_node.ToAddress = value
	}
	if value, ok := _c.mutation.AmountRaw(); ok {
		_spec.SetField(onchaindeposit.FieldAmountRaw, field.TypeString, value)
		_node.AmountRaw = value
	}
	if value, ok := _c.mutation.TransactionTime(); ok {
		_spec.SetField(onchaindeposit.FieldTransactionTime, field.TypeTime, value)
		_node.TransactionTime = value
	}
	if value, ok := _c.mutation.ReceiptSuccess(); ok {
		_spec.SetField(onchaindeposit.FieldReceiptSuccess, field.TypeBool, value)
		_node.ReceiptSuccess = value
	}
	if value, ok := _c.mutation.Finalized(); ok {
		_spec.SetField(onchaindeposit.FieldFinalized, field.TypeBool, value)
		_node.Finalized = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(onchaindeposit.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ValidationError(); ok {
		_spec.SetField(onchaindeposit.FieldValidationError, field.TypeString, value)
		_node.ValidationError = &value
	}
	if value, ok := _c.mutation.CreditAuditRef(); ok {
		_spec.SetField(onchaindeposit.FieldCreditAuditRef, field.TypeString, value)
		_node.CreditAuditRef = &value
	}
	if value, ok := _c.mutation.CreditedAt(); ok {
		_spec.SetField(onchaindeposit.FieldCreditedAt, field.TypeTime, value)
		_node.CreditedAt = &value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(onchaindeposit.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if nodes := _c.mutation.IntentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   onchaindeposit.IntentTable,
			Columns: []string{onchaindeposit.IntentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(onchainpaymentintent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IntentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OnchainDeposit.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OnchainDepositUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OnchainDepositCreate) OnConflict(opts ...sql.ConflictOption) *OnchainDepositUpsertOne {
	_c.conflict = opts
	return &OnchainDepositUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OnchainDepositCreate) OnConflictColumns(columns ...string) *OnchainDepositUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OnchainDepositUpsertOne{
		create: _c,
	}
}

type (
	// OnchainDepositUpsertOne is the builder for "upsert"-ing
	//  one OnchainDeposit node.
	OnchainDepositUpsertOne struct {
		create *OnchainDepositCreate
	}

	// OnchainDepositUpsert is the "OnConflict" setter.
	OnchainDepositUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OnchainDepositUpsert) SetUpdatedAt(v time.Time) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateUpdatedAt() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldUpdatedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *OnchainDepositUpsert) SetStatus(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateStatus() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldStatus)
	return u
}

// SetValidationError sets the "validation_error" field.
func (u *OnchainDepositUpsert) SetValidationError(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldValidationError, v)
	return u
}

// UpdateValidationError sets the "validation_error" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateValidationError() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldValidationError)
	return u
}

// ClearValidationError clears the value of the "validation_error" field.
func (u *OnchainDepositUpsert) ClearValidationError() *OnchainDepositUpsert {
	u.SetNull(onchaindeposit.FieldValidationError)
	return u
}

// SetCreditAuditRef sets the "credit_audit_ref" field.
func (u *OnchainDepositUpsert) SetCreditAuditRef(v string) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldCreditAuditRef, v)
	return u
}

// UpdateCreditAuditRef sets the "credit_audit_ref" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateCreditAuditRef() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldCreditAuditRef)
	return u
}

// ClearCreditAuditRef clears the value of the "credit_audit_ref" field.
func (u *OnchainDepositUpsert) ClearCreditAuditRef() *OnchainDepositUpsert {
	u.SetNull(onchaindeposit.FieldCreditAuditRef)
	return u
}

// SetCreditedAt sets the "credited_at" field.
func (u *OnchainDepositUpsert) SetCreditedAt(v time.Time) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldCreditedAt, v)
	return u
}

// UpdateCreditedAt sets the "credited_at" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateCreditedAt() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldCreditedAt)
	return u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (u *OnchainDepositUpsert) ClearCreditedAt() *OnchainDepositUpsert {
	u.SetNull(onchaindeposit.FieldCreditedAt)
	return u
}

// SetVersion sets the "version" field.
func (u *OnchainDepositUpsert) SetVersion(v int) *OnchainDepositUpsert {
	u.Set(onchaindeposit.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *OnchainDepositUpsert) UpdateVersion() *OnchainDepositUpsert {
	u.SetExcluded(onchaindeposit.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *OnchainDepositUpsert) AddVersion(v int) *OnchainDepositUpsert {
	u.Add(onchaindeposit.FieldVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OnchainDepositUpsertOne) UpdateNewValues() *OnchainDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(onchaindeposit.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.IntentID(); exists {
			s.SetIgnore(onchaindeposit.FieldIntentID)
		}
		if _, exists := u.create.mutation.PaymentOrderID(); exists {
			s.SetIgnore(onchaindeposit.FieldPaymentOrderID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(onchaindeposit.FieldUserID)
		}
		if _, exists := u.create.mutation.Network(); exists {
			s.SetIgnore(onchaindeposit.FieldNetwork)
		}
		if _, exists := u.create.mutation.ChainID(); exists {
			s.SetIgnore(onchaindeposit.FieldChainID)
		}
		if _, exists := u.create.mutation.TransactionID(); exists {
			s.SetIgnore(onchaindeposit.FieldTransactionID)
		}
		if _, exists := u.create.mutation.LogIndex(); exists {
			s.SetIgnore(onchaindeposit.FieldLogIndex)
		}
		if _, exists := u.create.mutation.TransactionIndex(); exists {
			s.SetIgnore(onchaindeposit.FieldTransactionIndex)
		}
		if _, exists := u.create.mutation.BlockHeight(); exists {
			s.SetIgnore(onchaindeposit.FieldBlockHeight)
		}
		if _, exists := u.create.mutation.BlockHash(); exists {
			s.SetIgnore(onchaindeposit.FieldBlockHash)
		}
		if _, exists := u.create.mutation.TokenContract(); exists {
			s.SetIgnore(onchaindeposit.FieldTokenContract)
		}
		if _, exists := u.create.mutation.FromAddress(); exists {
			s.SetIgnore(onchaindeposit.FieldFromAddress)
		}
		if _, exists := u.create.mutation.ToAddress(); exists {
			s.SetIgnore(onchaindeposit.FieldToAddress)
		}
		if _, exists := u.create.mutation.AmountRaw(); exists {
			s.SetIgnore(onchaindeposit.FieldAmountRaw)
		}
		if _, exists := u.create.mutation.TransactionTime(); exists {
			s.SetIgnore(onchaindeposit.FieldTransactionTime)
		}
		if _, exists := u.create.mutation.ReceiptSuccess(); exists {
			s.SetIgnore(onchaindeposit.FieldReceiptSuccess)
		}
		if _, exists := u.create.mutation.Finalized(); exists {
			s.SetIgnore(onchaindeposit.FieldFinalized)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OnchainDepositUpsertOne) Ignore() *OnchainDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OnchainDepositUpsertOne) DoNothing() *OnchainDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OnchainDepositCreate.OnConflict
// documentation for more info.
func (u *OnchainDepositUpsertOne) Update(set func(*OnchainDepositUpsert)) *OnchainDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OnchainDepositUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OnchainDepositUpsertOne) SetUpdatedAt(v time.Time) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateUpdatedAt() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *OnchainDepositUpsertOne) SetStatus(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateStatus() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateStatus()
	})
}

// SetValidationError sets the "validation_error" field.
func (u *OnchainDepositUpsertOne) SetValidationError(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetValidationError(v)
	})
}

// UpdateValidationError sets the "validation_error" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateValidationError() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateValidationError()
	})
}

// ClearValidationError clears the value of the "validation_error" field.
func (u *OnchainDepositUpsertOne) ClearValidationError() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.ClearValidationError()
	})
}

// SetCreditAuditRef sets the "credit_audit_ref" field.
func (u *OnchainDepositUpsertOne) SetCreditAuditRef(v string) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetCreditAuditRef(v)
	})
}

// UpdateCreditAuditRef sets the "credit_audit_ref" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateCreditAuditRef() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateCreditAuditRef()
	})
}

// ClearCreditAuditRef clears the value of the "credit_audit_ref" field.
func (u *OnchainDepositUpsertOne) ClearCreditAuditRef() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.ClearCreditAuditRef()
	})
}

// SetCreditedAt sets the "credited_at" field.
func (u *OnchainDepositUpsertOne) SetCreditedAt(v time.Time) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetCreditedAt(v)
	})
}

// UpdateCreditedAt sets the "credited_at" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateCreditedAt() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateCreditedAt()
	})
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (u *OnchainDepositUpsertOne) ClearCreditedAt() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.ClearCreditedAt()
	})
}

// SetVersion sets the "version" field.
func (u *OnchainDepositUpsertOne) SetVersion(v int) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *OnchainDepositUpsertOne) AddVersion(v int) *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *OnchainDepositUpsertOne) UpdateVersion() *OnchainDepositUpsertOne {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *OnchainDepositUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OnchainDepositCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OnchainDepositUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OnchainDepositUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OnchainDepositUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OnchainDepositCreateBulk is the builder for creating many OnchainDeposit entities in bulk.
type OnchainDepositCreateBulk struct {
	config
	err      error
	builders []*OnchainDepositCreate
	conflict []sql.ConflictOption
}

// Save creates the OnchainDeposit entities in the database.
func (_c *OnchainDepositCreateBulk) Save(ctx context.Context) ([]*OnchainDeposit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OnchainDeposit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OnchainDepositMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OnchainDepositCreateBulk) SaveX(ctx context.Context) []*OnchainDeposit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OnchainDepositCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OnchainDepositCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OnchainDeposit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OnchainDepositUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OnchainDepositCreateBulk) OnConflict(opts ...sql.ConflictOption) *OnchainDepositUpsertBulk {
	_c.conflict = opts
	return &OnchainDepositUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OnchainDepositCreateBulk) OnConflictColumns(columns ...string) *OnchainDepositUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OnchainDepositUpsertBulk{
		create: _c,
	}
}

// OnchainDepositUpsertBulk is the builder for "upsert"-ing
// a bulk of OnchainDeposit nodes.
type OnchainDepositUpsertBulk struct {
	create *OnchainDepositCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OnchainDepositUpsertBulk) UpdateNewValues() *OnchainDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(onchaindeposit.FieldCreatedAt)
			}
			if _, exists := b.mutation.IntentID(); exists {
				s.SetIgnore(onchaindeposit.FieldIntentID)
			}
			if _, exists := b.mutation.PaymentOrderID(); exists {
				s.SetIgnore(onchaindeposit.FieldPaymentOrderID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(onchaindeposit.FieldUserID)
			}
			if _, exists := b.mutation.Network(); exists {
				s.SetIgnore(onchaindeposit.FieldNetwork)
			}
			if _, exists := b.mutation.ChainID(); exists {
				s.SetIgnore(onchaindeposit.FieldChainID)
			}
			if _, exists := b.mutation.TransactionID(); exists {
				s.SetIgnore(onchaindeposit.FieldTransactionID)
			}
			if _, exists := b.mutation.LogIndex(); exists {
				s.SetIgnore(onchaindeposit.FieldLogIndex)
			}
			if _, exists := b.mutation.TransactionIndex(); exists {
				s.SetIgnore(onchaindeposit.FieldTransactionIndex)
			}
			if _, exists := b.mutation.BlockHeight(); exists {
				s.SetIgnore(onchaindeposit.FieldBlockHeight)
			}
			if _, exists := b.mutation.BlockHash(); exists {
				s.SetIgnore(onchaindeposit.FieldBlockHash)
			}
			if _, exists := b.mutation.TokenContract(); exists {
				s.SetIgnore(onchaindeposit.FieldTokenContract)
			}
			if _, exists := b.mutation.FromAddress(); exists {
				s.SetIgnore(onchaindeposit.FieldFromAddress)
			}
			if _, exists := b.mutation.ToAddress(); exists {
				s.SetIgnore(onchaindeposit.FieldToAddress)
			}
			if _, exists := b.mutation.AmountRaw(); exists {
				s.SetIgnore(onchaindeposit.FieldAmountRaw)
			}
			if _, exists := b.mutation.TransactionTime(); exists {
				s.SetIgnore(onchaindeposit.FieldTransactionTime)
			}
			if _, exists := b.mutation.ReceiptSuccess(); exists {
				s.SetIgnore(onchaindeposit.FieldReceiptSuccess)
			}
			if _, exists := b.mutation.Finalized(); exists {
				s.SetIgnore(onchaindeposit.FieldFinalized)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OnchainDeposit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OnchainDepositUpsertBulk) Ignore() *OnchainDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OnchainDepositUpsertBulk) DoNothing() *OnchainDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OnchainDepositCreateBulk.OnConflict
// documentation for more info.
func (u *OnchainDepositUpsertBulk) Update(set func(*OnchainDepositUpsert)) *OnchainDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OnchainDepositUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OnchainDepositUpsertBulk) SetUpdatedAt(v time.Time) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateUpdatedAt() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *OnchainDepositUpsertBulk) SetStatus(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateStatus() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateStatus()
	})
}

// SetValidationError sets the "validation_error" field.
func (u *OnchainDepositUpsertBulk) SetValidationError(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetValidationError(v)
	})
}

// UpdateValidationError sets the "validation_error" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateValidationError() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateValidationError()
	})
}

// ClearValidationError clears the value of the "validation_error" field.
func (u *OnchainDepositUpsertBulk) ClearValidationError() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.ClearValidationError()
	})
}

// SetCreditAuditRef sets the "credit_audit_ref" field.
func (u *OnchainDepositUpsertBulk) SetCreditAuditRef(v string) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetCreditAuditRef(v)
	})
}

// UpdateCreditAuditRef sets the "credit_audit_ref" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateCreditAuditRef() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateCreditAuditRef()
	})
}

// ClearCreditAuditRef clears the value of the "credit_audit_ref" field.
func (u *OnchainDepositUpsertBulk) ClearCreditAuditRef() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.ClearCreditAuditRef()
	})
}

// SetCreditedAt sets the "credited_at" field.
func (u *OnchainDepositUpsertBulk) SetCreditedAt(v time.Time) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetCreditedAt(v)
	})
}

// UpdateCreditedAt sets the "credited_at" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateCreditedAt() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateCreditedAt()
	})
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (u *OnchainDepositUpsertBulk) ClearCreditedAt() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.ClearCreditedAt()
	})
}

// SetVersion sets the "version" field.
func (u *OnchainDepositUpsertBulk) SetVersion(v int) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *OnchainDepositUpsertBulk) AddVersion(v int) *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *OnchainDepositUpsertBulk) UpdateVersion() *OnchainDepositUpsertBulk {
	return u.Update(func(s *OnchainDepositUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *OnchainDepositUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OnchainDepositCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OnchainDepositCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OnchainDepositUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
