// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/walletderivationcursor"
)

// WalletDerivationCursorCreate is the builder for creating a WalletDerivationCursor entity.
type WalletDerivationCursorCreate struct {
	config
	mutation *WalletDerivationCursorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *WalletDerivationCursorCreate) SetCreatedAt(v time.Time) *WalletDerivationCursorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WalletDerivationCursorCreate) SetNillableCreatedAt(v *time.Time) *WalletDerivationCursorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WalletDerivationCursorCreate) SetUpdatedAt(v time.Time) *WalletDerivationCursorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WalletDerivationCursorCreate) SetNillableUpdatedAt(v *time.Time) *WalletDerivationCursorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetNetwork sets the "network" field.
func (_c *WalletDerivationCursorCreate) SetNetwork(v string) *WalletDerivationCursorCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetNextIndex sets the "next_index" field.
func (_c *WalletDerivationCursorCreate) SetNextIndex(v int64) *WalletDerivationCursorCreate {
	_c.mutation.SetNextIndex(v)
	return _c
}

// SetNillableNextIndex sets the "next_index" field if the given value is not nil.
func (_c *WalletDerivationCursorCreate) SetNillableNextIndex(v *int64) *WalletDerivationCursorCreate {
	if v != nil {
		_c.SetNextIndex(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *WalletDerivationCursorCreate) SetVersion(v int) *WalletDerivationCursorCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *WalletDerivationCursorCreate) SetNillableVersion(v *int) *WalletDerivationCursorCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// Mutation returns the WalletDerivationCursorMutation object of the builder.
func (_c *WalletDerivationCursorCreate) Mutation() *WalletDerivationCursorMutation {
	return _c.mutation
}

// Save creates the WalletDerivationCursor in the database.
func (_c *WalletDerivationCursorCreate) Save(ctx context.Context) (*WalletDerivationCursor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WalletDerivationCursorCreate) SaveX(ctx context.Context) *WalletDerivationCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletDerivationCursorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletDerivationCursorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WalletDerivationCursorCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := walletderivationcursor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := walletderivationcursor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.NextIndex(); !ok {
		v := walletderivationcursor.DefaultNextIndex
		_c.mutation.SetNextIndex(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := walletderivationcursor.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WalletDerivationCursorCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WalletDerivationCursor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WalletDerivationCursor.updated_at"`)}
	}
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "WalletDerivationCursor.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := walletderivationcursor.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "WalletDerivationCursor.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NextIndex(); !ok {
		return &ValidationError{Name: "next_index", err: errors.New(`ent: missing required field "WalletDerivationCursor.next_index"`)}
	}
	if v, ok := _c.mutation.NextIndex(); ok {
		if err := walletderivationcursor.NextIndexValidator(v); err != nil {
			return &ValidationError{Name: "next_index", err: fmt.Errorf(`ent: validator failed for field "WalletDerivationCursor.next_index": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "WalletDerivationCursor.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := walletderivationcursor.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "WalletDerivationCursor.version": %w`, err)}
		}
	}
	return nil
}

func (_c *WalletDerivationCursorCreate) sqlSave(ctx context.Context) (*WalletDerivationCursor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WalletDerivationCursorCreate) createSpec() (*WalletDerivationCursor, *sqlgraph.CreateSpec) {
	var (
		_node = &WalletDerivationCursor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(walletderivationcursor.Table, sqlgraph.NewFieldSpec(walletderivationcursor.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(walletderivationcursor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(walletderivationcursor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(walletderivationcursor.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.NextIndex(); ok {
		_spec.SetField(walletderivationcursor.FieldNextIndex, field.TypeInt64, value)
		_node.NextIndex = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(walletderivationcursor.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WalletDerivationCursor.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WalletDerivationCursorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WalletDerivationCursorCreate) OnConflict(opts ...sql.ConflictOption) *WalletDerivationCursorUpsertOne {
	_c.conflict = opts
	return &WalletDerivationCursorUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WalletDerivationCursor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WalletDerivationCursorCreate) OnConflictColumns(columns ...string) *WalletDerivationCursorUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WalletDerivationCursorUpsertOne{
		create: _c,
	}
}

type (
	// WalletDerivationCursorUpsertOne is the builder for "upsert"-ing
	//  one WalletDerivationCursor node.
	WalletDerivationCursorUpsertOne struct {
		create *WalletDerivationCursorCreate
	}

	// WalletDerivationCursorUpsert is the "OnConflict" setter.
	WalletDerivationCursorUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletDerivationCursorUpsert) SetUpdatedAt(v time.Time) *WalletDerivationCursorUpsert {
	u.Set(walletderivationcursor.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletDerivationCursorUpsert) UpdateUpdatedAt() *WalletDerivationCursorUpsert {
	u.SetExcluded(walletderivationcursor.FieldUpdatedAt)
	return u
}

// SetNextIndex sets the "next_index" field.
func (u *WalletDerivationCursorUpsert) SetNextIndex(v int64) *WalletDerivationCursorUpsert {
	u.Set(walletderivationcursor.FieldNextIndex, v)
	return u
}

// UpdateNextIndex sets the "next_index" field to the value that was provided on create.
func (u *WalletDerivationCursorUpsert) UpdateNextIndex() *WalletDerivationCursorUpsert {
	u.SetExcluded(walletderivationcursor.FieldNextIndex)
	return u
}

// AddNextIndex adds v to the "next_index" field.
func (u *WalletDerivationCursorUpsert) AddNextIndex(v int64) *WalletDerivationCursorUpsert {
	u.Add(walletderivationcursor.FieldNextIndex, v)
	return u
}

// SetVersion sets the "version" field.
func (u *WalletDerivationCursorUpsert) SetVersion(v int) *WalletDerivationCursorUpsert {
	u.Set(walletderivationcursor.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *WalletDerivationCursorUpsert) UpdateVersion() *WalletDerivationCursorUpsert {
	u.SetExcluded(walletderivationcursor.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *WalletDerivationCursorUpsert) AddVersion(v int) *WalletDerivationCursorUpsert {
	u.Add(walletderivationcursor.FieldVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WalletDerivationCursor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WalletDerivationCursorUpsertOne) UpdateNewValues() *WalletDerivationCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(walletderivationcursor.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Network(); exists {
			s.SetIgnore(walletderivationcursor.FieldNetwork)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WalletDerivationCursor.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WalletDerivationCursorUpsertOne) Ignore() *WalletDerivationCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WalletDerivationCursorUpsertOne) DoNothing() *WalletDerivationCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WalletDerivationCursorCreate.OnConflict
// documentation for more info.
func (u *WalletDerivationCursorUpsertOne) Update(set func(*WalletDerivationCursorUpsert)) *WalletDerivationCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WalletDerivationCursorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletDerivationCursorUpsertOne) SetUpdatedAt(v time.Time) *WalletDerivationCursorUpsertOne {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletDerivationCursorUpsertOne) UpdateUpdatedAt() *WalletDerivationCursorUpsertOne {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetNextIndex sets the "next_index" field.
func (u *WalletDerivationCursorUpsertOne) SetNextIndex(v int64) *WalletDerivationCursorUpsertOne {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.SetNextIndex(v)
	})
}

// AddNextIndex adds v to the "next_index" field.
func (u *WalletDerivationCursorUpsertOne) AddNextIndex(v int64) *WalletDerivationCursorUpsertOne {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.AddNextIndex(v)
	})
}

// UpdateNextIndex sets the "next_index" field to the value that was provided on create.
func (u *WalletDerivationCursorUpsertOne) UpdateNextIndex() *WalletDerivationCursorUpsertOne {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.UpdateNextIndex()
	})
}

// SetVersion sets the "version" field.
func (u *WalletDerivationCursorUpsertOne) SetVersion(v int) *WalletDerivationCursorUpsertOne {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *WalletDerivationCursorUpsertOne) AddVersion(v int) *WalletDerivationCursorUpsertOne {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *WalletDerivationCursorUpsertOne) UpdateVersion() *WalletDerivationCursorUpsertOne {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *WalletDerivationCursorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WalletDerivationCursorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WalletDerivationCursorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WalletDerivationCursorUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WalletDerivationCursorUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WalletDerivationCursorCreateBulk is the builder for creating many WalletDerivationCursor entities in bulk.
type WalletDerivationCursorCreateBulk struct {
	config
	err      error
	builders []*WalletDerivationCursorCreate
	conflict []sql.ConflictOption
}

// Save creates the WalletDerivationCursor entities in the database.
func (_c *WalletDerivationCursorCreateBulk) Save(ctx context.Context) ([]*WalletDerivationCursor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WalletDerivationCursor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WalletDerivationCursorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WalletDerivationCursorCreateBulk) SaveX(ctx context.Context) []*WalletDerivationCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletDerivationCursorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletDerivationCursorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WalletDerivationCursor.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WalletDerivationCursorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WalletDerivationCursorCreateBulk) OnConflict(opts ...sql.ConflictOption) *WalletDerivationCursorUpsertBulk {
	_c.conflict = opts
	return &WalletDerivationCursorUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WalletDerivationCursor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WalletDerivationCursorCreateBulk) OnConflictColumns(columns ...string) *WalletDerivationCursorUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WalletDerivationCursorUpsertBulk{
		create: _c,
	}
}

// WalletDerivationCursorUpsertBulk is the builder for "upsert"-ing
// a bulk of WalletDerivationCursor nodes.
type WalletDerivationCursorUpsertBulk struct {
	create *WalletDerivationCursorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WalletDerivationCursor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WalletDerivationCursorUpsertBulk) UpdateNewValues() *WalletDerivationCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(walletderivationcursor.FieldCreatedAt)
			}
			if _, exists := b.mutation.Network(); exists {
				s.SetIgnore(walletderivationcursor.FieldNetwork)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WalletDerivationCursor.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WalletDerivationCursorUpsertBulk) Ignore() *WalletDerivationCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WalletDerivationCursorUpsertBulk) DoNothing() *WalletDerivationCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WalletDerivationCursorCreateBulk.OnConflict
// documentation for more info.
func (u *WalletDerivationCursorUpsertBulk) Update(set func(*WalletDerivationCursorUpsert)) *WalletDerivationCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WalletDerivationCursorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletDerivationCursorUpsertBulk) SetUpdatedAt(v time.Time) *WalletDerivationCursorUpsertBulk {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletDerivationCursorUpsertBulk) UpdateUpdatedAt() *WalletDerivationCursorUpsertBulk {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetNextIndex sets the "next_index" field.
func (u *WalletDerivationCursorUpsertBulk) SetNextIndex(v int64) *WalletDerivationCursorUpsertBulk {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.SetNextIndex(v)
	})
}

// AddNextIndex adds v to the "next_index" field.
func (u *WalletDerivationCursorUpsertBulk) AddNextIndex(v int64) *WalletDerivationCursorUpsertBulk {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.AddNextIndex(v)
	})
}

// UpdateNextIndex sets the "next_index" field to the value that was provided on create.
func (u *WalletDerivationCursorUpsertBulk) UpdateNextIndex() *WalletDerivationCursorUpsertBulk {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.UpdateNextIndex()
	})
}

// SetVersion sets the "version" field.
func (u *WalletDerivationCursorUpsertBulk) SetVersion(v int) *WalletDerivationCursorUpsertBulk {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *WalletDerivationCursorUpsertBulk) AddVersion(v int) *WalletDerivationCursorUpsertBulk {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *WalletDerivationCursorUpsertBulk) UpdateVersion() *WalletDerivationCursorUpsertBulk {
	return u.Update(func(s *WalletDerivationCursorUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *WalletDerivationCursorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WalletDerivationCursorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WalletDerivationCursorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WalletDerivationCursorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
