// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/walletderivationcursor"
)

// WalletDerivationCursorUpdate is the builder for updating WalletDerivationCursor entities.
type WalletDerivationCursorUpdate struct {
	config
	hooks    []Hook
	mutation *WalletDerivationCursorMutation
}

// Where appends a list predicates to the WalletDerivationCursorUpdate builder.
func (_u *WalletDerivationCursorUpdate) Where(ps ...predicate.WalletDerivationCursor) *WalletDerivationCursorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WalletDerivationCursorUpdate) SetUpdatedAt(v time.Time) *WalletDerivationCursorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNextIndex sets the "next_index" field.
func (_u *WalletDerivationCursorUpdate) SetNextIndex(v int64) *WalletDerivationCursorUpdate {
	_u.mutation.ResetNextIndex()
	_u.mutation.SetNextIndex(v)
	return _u
}

// SetNillableNextIndex sets the "next_index" field if the given value is not nil.
func (_u *WalletDerivationCursorUpdate) SetNillableNextIndex(v *int64) *WalletDerivationCursorUpdate {
	if v != nil {
		_u.SetNextIndex(*v)
	}
	return _u
}

// AddNextIndex adds value to the "next_index" field.
func (_u *WalletDerivationCursorUpdate) AddNextIndex(v int64) *WalletDerivationCursorUpdate {
	_u.mutation.AddNextIndex(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *WalletDerivationCursorUpdate) SetVersion(v int) *WalletDerivationCursorUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *WalletDerivationCursorUpdate) SetNillableVersion(v *int) *WalletDerivationCursorUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *WalletDerivationCursorUpdate) AddVersion(v int) *WalletDerivationCursorUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the WalletDerivationCursorMutation object of the builder.
func (_u *WalletDerivationCursorUpdate) Mutation() *WalletDerivationCursorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WalletDerivationCursorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletDerivationCursorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WalletDerivationCursorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletDerivationCursorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WalletDerivationCursorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := walletderivationcursor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WalletDerivationCursorUpdate) check() error {
	if v, ok := _u.mutation.NextIndex(); ok {
		if err := walletderivationcursor.NextIndexValidator(v); err != nil {
			return &ValidationError{Name: "next_index", err: fmt.Errorf(`ent: validator failed for field "WalletDerivationCursor.next_index": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := walletderivationcursor.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "WalletDerivationCursor.version": %w`, err)}
		}
	}
	return nil
}

func (_u *WalletDerivationCursorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(walletderivationcursor.Table, walletderivationcursor.Columns, sqlgraph.NewFieldSpec(walletderivationcursor.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(walletderivationcursor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NextIndex(); ok {
		_spec.SetField(walletderivationcursor.FieldNextIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextIndex(); ok {
		_spec.AddField(walletderivationcursor.FieldNextIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(walletderivationcursor.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(walletderivationcursor.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{walletderivationcursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WalletDerivationCursorUpdateOne is the builder for updating a single WalletDerivationCursor entity.
type WalletDerivationCursorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WalletDerivationCursorMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WalletDerivationCursorUpdateOne) SetUpdatedAt(v time.Time) *WalletDerivationCursorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNextIndex sets the "next_index" field.
func (_u *WalletDerivationCursorUpdateOne) SetNextIndex(v int64) *WalletDerivationCursorUpdateOne {
	_u.mutation.ResetNextIndex()
	_u.mutation.SetNextIndex(v)
	return _u
}

// SetNillableNextIndex sets the "next_index" field if the given value is not nil.
func (_u *WalletDerivationCursorUpdateOne) SetNillableNextIndex(v *int64) *WalletDerivationCursorUpdateOne {
	if v != nil {
		_u.SetNextIndex(*v)
	}
	return _u
}

// AddNextIndex adds value to the "next_index" field.
func (_u *WalletDerivationCursorUpdateOne) AddNextIndex(v int64) *WalletDerivationCursorUpdateOne {
	_u.mutation.AddNextIndex(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *WalletDerivationCursorUpdateOne) SetVersion(v int) *WalletDerivationCursorUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *WalletDerivationCursorUpdateOne) SetNillableVersion(v *int) *WalletDerivationCursorUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *WalletDerivationCursorUpdateOne) AddVersion(v int) *WalletDerivationCursorUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the WalletDerivationCursorMutation object of the builder.
func (_u *WalletDerivationCursorUpdateOne) Mutation() *WalletDerivationCursorMutation {
	return _u.mutation
}

// Where appends a list predicates to the WalletDerivationCursorUpdate builder.
func (_u *WalletDerivationCursorUpdateOne) Where(ps ...predicate.WalletDerivationCursor) *WalletDerivationCursorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WalletDerivationCursorUpdateOne) Select(field string, fields ...string) *WalletDerivationCursorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WalletDerivationCursor entity.
func (_u *WalletDerivationCursorUpdateOne) Save(ctx context.Context) (*WalletDerivationCursor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletDerivationCursorUpdateOne) SaveX(ctx context.Context) *WalletDerivationCursor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WalletDerivationCursorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletDerivationCursorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WalletDerivationCursorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := walletderivationcursor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WalletDerivationCursorUpdateOne) check() error {
	if v, ok := _u.mutation.NextIndex(); ok {
		if err := walletderivationcursor.NextIndexValidator(v); err != nil {
			return &ValidationError{Name: "next_index", err: fmt.Errorf(`ent: validator failed for field "WalletDerivationCursor.next_index": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := walletderivationcursor.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "WalletDerivationCursor.version": %w`, err)}
		}
	}
	return nil
}

func (_u *WalletDerivationCursorUpdateOne) sqlSave(ctx context.Context) (_node *WalletDerivationCursor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(walletderivationcursor.Table, walletderivationcursor.Columns, sqlgraph.NewFieldSpec(walletderivationcursor.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WalletDerivationCursor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, walletderivationcursor.FieldID)
		for _, f := range fields {
			if !walletderivationcursor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != walletderivationcursor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(walletderivationcursor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NextIndex(); ok {
		_spec.SetField(walletderivationcursor.FieldNextIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextIndex(); ok {
		_spec.AddField(walletderivationcursor.FieldNextIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(walletderivationcursor.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(walletderivationcursor.FieldVersion, field.TypeInt, value)
	}
	_node = &WalletDerivationCursor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{walletderivationcursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
