// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ethereumnoncestate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EthereumNonceStateUpdate is the builder for updating EthereumNonceState entities.
type EthereumNonceStateUpdate struct {
	config
	hooks    []Hook
	mutation *EthereumNonceStateMutation
}

// Where appends a list predicates to the EthereumNonceStateUpdate builder.
func (_u *EthereumNonceStateUpdate) Where(ps ...predicate.EthereumNonceState) *EthereumNonceStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EthereumNonceStateUpdate) SetUpdatedAt(v time.Time) *EthereumNonceStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNextNonce sets the "next_nonce" field.
func (_u *EthereumNonceStateUpdate) SetNextNonce(v int64) *EthereumNonceStateUpdate {
	_u.mutation.ResetNextNonce()
	_u.mutation.SetNextNonce(v)
	return _u
}

// SetNillableNextNonce sets the "next_nonce" field if the given value is not nil.
func (_u *EthereumNonceStateUpdate) SetNillableNextNonce(v *int64) *EthereumNonceStateUpdate {
	if v != nil {
		_u.SetNextNonce(*v)
	}
	return _u
}

// AddNextNonce adds value to the "next_nonce" field.
func (_u *EthereumNonceStateUpdate) AddNextNonce(v int64) *EthereumNonceStateUpdate {
	_u.mutation.AddNextNonce(v)
	return _u
}

// SetObservedPendingNonce sets the "observed_pending_nonce" field.
func (_u *EthereumNonceStateUpdate) SetObservedPendingNonce(v int64) *EthereumNonceStateUpdate {
	_u.mutation.ResetObservedPendingNonce()
	_u.mutation.SetObservedPendingNonce(v)
	return _u
}

// SetNillableObservedPendingNonce sets the "observed_pending_nonce" field if the given value is not nil.
func (_u *EthereumNonceStateUpdate) SetNillableObservedPendingNonce(v *int64) *EthereumNonceStateUpdate {
	if v != nil {
		_u.SetObservedPendingNonce(*v)
	}
	return _u
}

// AddObservedPendingNonce adds value to the "observed_pending_nonce" field.
func (_u *EthereumNonceStateUpdate) AddObservedPendingNonce(v int64) *EthereumNonceStateUpdate {
	_u.mutation.AddObservedPendingNonce(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EthereumNonceStateUpdate) SetStatus(v string) *EthereumNonceStateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EthereumNonceStateUpdate) SetNillableStatus(v *string) *EthereumNonceStateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *EthereumNonceStateUpdate) SetLeaseOwner(v string) *EthereumNonceStateUpdate {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *EthereumNonceStateUpdate) SetNillableLeaseOwner(v *string) *EthereumNonceStateUpdate {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *EthereumNonceStateUpdate) ClearLeaseOwner() *EthereumNonceStateUpdate {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseUntil sets the "lease_until" field.
func (_u *EthereumNonceStateUpdate) SetLeaseUntil(v time.Time) *EthereumNonceStateUpdate {
	_u.mutation.SetLeaseUntil(v)
	return _u
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_u *EthereumNonceStateUpdate) SetNillableLeaseUntil(v *time.Time) *EthereumNonceStateUpdate {
	if v != nil {
		_u.SetLeaseUntil(*v)
	}
	return _u
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (_u *EthereumNonceStateUpdate) ClearLeaseUntil() *EthereumNonceStateUpdate {
	_u.mutation.ClearLeaseUntil()
	return _u
}

// SetLastReconciledAt sets the "last_reconciled_at" field.
func (_u *EthereumNonceStateUpdate) SetLastReconciledAt(v time.Time) *EthereumNonceStateUpdate {
	_u.mutation.SetLastReconciledAt(v)
	return _u
}

// SetNillableLastReconciledAt sets the "last_reconciled_at" field if the given value is not nil.
func (_u *EthereumNonceStateUpdate) SetNillableLastReconciledAt(v *time.Time) *EthereumNonceStateUpdate {
	if v != nil {
		_u.SetLastReconciledAt(*v)
	}
	return _u
}

// ClearLastReconciledAt clears the value of the "last_reconciled_at" field.
func (_u *EthereumNonceStateUpdate) ClearLastReconciledAt() *EthereumNonceStateUpdate {
	_u.mutation.ClearLastReconciledAt()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *EthereumNonceStateUpdate) SetLastErrorCode(v string) *EthereumNonceStateUpdate {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *EthereumNonceStateUpdate) SetNillableLastErrorCode(v *string) *EthereumNonceStateUpdate {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *EthereumNonceStateUpdate) ClearLastErrorCode() *EthereumNonceStateUpdate {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *EthereumNonceStateUpdate) SetLastErrorMessage(v string) *EthereumNonceStateUpdate {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *EthereumNonceStateUpdate) SetNillableLastErrorMessage(v *string) *EthereumNonceStateUpdate {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *EthereumNonceStateUpdate) ClearLastErrorMessage() *EthereumNonceStateUpdate {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetVersion sets the "version" field.
func (_u *EthereumNonceStateUpdate) SetVersion(v int) *EthereumNonceStateUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *EthereumNonceStateUpdate) SetNillableVersion(v *int) *EthereumNonceStateUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *EthereumNonceStateUpdate) AddVersion(v int) *EthereumNonceStateUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the EthereumNonceStateMutation object of the builder.
func (_u *EthereumNonceStateUpdate) Mutation() *EthereumNonceStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EthereumNonceStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EthereumNonceStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EthereumNonceStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EthereumNonceStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EthereumNonceStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ethereumnoncestate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EthereumNonceStateUpdate) check() error {
	if v, ok := _u.mutation.NextNonce(); ok {
		if err := ethereumnoncestate.NextNonceValidator(v); err != nil {
			return &ValidationError{Name: "next_nonce", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.next_nonce": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObservedPendingNonce(); ok {
		if err := ethereumnoncestate.ObservedPendingNonceValidator(v); err != nil {
			return &ValidationError{Name: "observed_pending_nonce", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.observed_pending_nonce": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ethereumnoncestate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := ethereumnoncestate.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := ethereumnoncestate.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.last_error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := ethereumnoncestate.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.version": %w`, err)}
		}
	}
	return nil
}

func (_u *EthereumNonceStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ethereumnoncestate.Table, ethereumnoncestate.Columns, sqlgraph.NewFieldSpec(ethereumnoncestate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ethereumnoncestate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NextNonce(); ok {
		_spec.SetField(ethereumnoncestate.FieldNextNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextNonce(); ok {
		_spec.AddField(ethereumnoncestate.FieldNextNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ObservedPendingNonce(); ok {
		_spec.SetField(ethereumnoncestate.FieldObservedPendingNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedObservedPendingNonce(); ok {
		_spec.AddField(ethereumnoncestate.FieldObservedPendingNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ethereumnoncestate.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(ethereumnoncestate.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(ethereumnoncestate.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseUntil(); ok {
		_spec.SetField(ethereumnoncestate.FieldLeaseUntil, field.TypeTime, value)
	}
	if _u.mutation.LeaseUntilCleared() {
		_spec.ClearField(ethereumnoncestate.FieldLeaseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LastReconciledAt(); ok {
		_spec.SetField(ethereumnoncestate.FieldLastReconciledAt, field.TypeTime, value)
	}
	if _u.mutation.LastReconciledAtCleared() {
		_spec.ClearField(ethereumnoncestate.FieldLastReconciledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(ethereumnoncestate.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(ethereumnoncestate.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(ethereumnoncestate.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(ethereumnoncestate.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(ethereumnoncestate.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(ethereumnoncestate.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ethereumnoncestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EthereumNonceStateUpdateOne is the builder for updating a single EthereumNonceState entity.
type EthereumNonceStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EthereumNonceStateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EthereumNonceStateUpdateOne) SetUpdatedAt(v time.Time) *EthereumNonceStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNextNonce sets the "next_nonce" field.
func (_u *EthereumNonceStateUpdateOne) SetNextNonce(v int64) *EthereumNonceStateUpdateOne {
	_u.mutation.ResetNextNonce()
	_u.mutation.SetNextNonce(v)
	return _u
}

// SetNillableNextNonce sets the "next_nonce" field if the given value is not nil.
func (_u *EthereumNonceStateUpdateOne) SetNillableNextNonce(v *int64) *EthereumNonceStateUpdateOne {
	if v != nil {
		_u.SetNextNonce(*v)
	}
	return _u
}

// AddNextNonce adds value to the "next_nonce" field.
func (_u *EthereumNonceStateUpdateOne) AddNextNonce(v int64) *EthereumNonceStateUpdateOne {
	_u.mutation.AddNextNonce(v)
	return _u
}

// SetObservedPendingNonce sets the "observed_pending_nonce" field.
func (_u *EthereumNonceStateUpdateOne) SetObservedPendingNonce(v int64) *EthereumNonceStateUpdateOne {
	_u.mutation.ResetObservedPendingNonce()
	_u.mutation.SetObservedPendingNonce(v)
	return _u
}

// SetNillableObservedPendingNonce sets the "observed_pending_nonce" field if the given value is not nil.
func (_u *EthereumNonceStateUpdateOne) SetNillableObservedPendingNonce(v *int64) *EthereumNonceStateUpdateOne {
	if v != nil {
		_u.SetObservedPendingNonce(*v)
	}
	return _u
}

// AddObservedPendingNonce adds value to the "observed_pending_nonce" field.
func (_u *EthereumNonceStateUpdateOne) AddObservedPendingNonce(v int64) *EthereumNonceStateUpdateOne {
	_u.mutation.AddObservedPendingNonce(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EthereumNonceStateUpdateOne) SetStatus(v string) *EthereumNonceStateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EthereumNonceStateUpdateOne) SetNillableStatus(v *string) *EthereumNonceStateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *EthereumNonceStateUpdateOne) SetLeaseOwner(v string) *EthereumNonceStateUpdateOne {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *EthereumNonceStateUpdateOne) SetNillableLeaseOwner(v *string) *EthereumNonceStateUpdateOne {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *EthereumNonceStateUpdateOne) ClearLeaseOwner() *EthereumNonceStateUpdateOne {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseUntil sets the "lease_until" field.
func (_u *EthereumNonceStateUpdateOne) SetLeaseUntil(v time.Time) *EthereumNonceStateUpdateOne {
	_u.mutation.SetLeaseUntil(v)
	return _u
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_u *EthereumNonceStateUpdateOne) SetNillableLeaseUntil(v *time.Time) *EthereumNonceStateUpdateOne {
	if v != nil {
		_u.SetLeaseUntil(*v)
	}
	return _u
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (_u *EthereumNonceStateUpdateOne) ClearLeaseUntil() *EthereumNonceStateUpdateOne {
	_u.mutation.ClearLeaseUntil()
	return _u
}

// SetLastReconciledAt sets the "last_reconciled_at" field.
func (_u *EthereumNonceStateUpdateOne) SetLastReconciledAt(v time.Time) *EthereumNonceStateUpdateOne {
	_u.mutation.SetLastReconciledAt(v)
	return _u
}

// SetNillableLastReconciledAt sets the "last_reconciled_at" field if the given value is not nil.
func (_u *EthereumNonceStateUpdateOne) SetNillableLastReconciledAt(v *time.Time) *EthereumNonceStateUpdateOne {
	if v != nil {
		_u.SetLastReconciledAt(*v)
	}
	return _u
}

// ClearLastReconciledAt clears the value of the "last_reconciled_at" field.
func (_u *EthereumNonceStateUpdateOne) ClearLastReconciledAt() *EthereumNonceStateUpdateOne {
	_u.mutation.ClearLastReconciledAt()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *EthereumNonceStateUpdateOne) SetLastErrorCode(v string) *EthereumNonceStateUpdateOne {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *EthereumNonceStateUpdateOne) SetNillableLastErrorCode(v *string) *EthereumNonceStateUpdateOne {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *EthereumNonceStateUpdateOne) ClearLastErrorCode() *EthereumNonceStateUpdateOne {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *EthereumNonceStateUpdateOne) SetLastErrorMessage(v string) *EthereumNonceStateUpdateOne {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *EthereumNonceStateUpdateOne) SetNillableLastErrorMessage(v *string) *EthereumNonceStateUpdateOne {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *EthereumNonceStateUpdateOne) ClearLastErrorMessage() *EthereumNonceStateUpdateOne {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetVersion sets the "version" field.
func (_u *EthereumNonceStateUpdateOne) SetVersion(v int) *EthereumNonceStateUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *EthereumNonceStateUpdateOne) SetNillableVersion(v *int) *EthereumNonceStateUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *EthereumNonceStateUpdateOne) AddVersion(v int) *EthereumNonceStateUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the EthereumNonceStateMutation object of the builder.
func (_u *EthereumNonceStateUpdateOne) Mutation() *EthereumNonceStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the EthereumNonceStateUpdate builder.
func (_u *EthereumNonceStateUpdateOne) Where(ps ...predicate.EthereumNonceState) *EthereumNonceStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EthereumNonceStateUpdateOne) Select(field string, fields ...string) *EthereumNonceStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EthereumNonceState entity.
func (_u *EthereumNonceStateUpdateOne) Save(ctx context.Context) (*EthereumNonceState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EthereumNonceStateUpdateOne) SaveX(ctx context.Context) *EthereumNonceState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EthereumNonceStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EthereumNonceStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EthereumNonceStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ethereumnoncestate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EthereumNonceStateUpdateOne) check() error {
	if v, ok := _u.mutation.NextNonce(); ok {
		if err := ethereumnoncestate.NextNonceValidator(v); err != nil {
			return &ValidationError{Name: "next_nonce", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.next_nonce": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObservedPendingNonce(); ok {
		if err := ethereumnoncestate.ObservedPendingNonceValidator(v); err != nil {
			return &ValidationError{Name: "observed_pending_nonce", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.observed_pending_nonce": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ethereumnoncestate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := ethereumnoncestate.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := ethereumnoncestate.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.last_error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := ethereumnoncestate.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "EthereumNonceState.version": %w`, err)}
		}
	}
	return nil
}

func (_u *EthereumNonceStateUpdateOne) sqlSave(ctx context.Context) (_node *EthereumNonceState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ethereumnoncestate.Table, ethereumnoncestate.Columns, sqlgraph.NewFieldSpec(ethereumnoncestate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EthereumNonceState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ethereumnoncestate.FieldID)
		for _, f := range fields {
			if !ethereumnoncestate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ethereumnoncestate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ethereumnoncestate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NextNonce(); ok {
		_spec.SetField(ethereumnoncestate.FieldNextNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextNonce(); ok {
		_spec.AddField(ethereumnoncestate.FieldNextNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ObservedPendingNonce(); ok {
		_spec.SetField(ethereumnoncestate.FieldObservedPendingNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedObservedPendingNonce(); ok {
		_spec.AddField(ethereumnoncestate.FieldObservedPendingNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ethereumnoncestate.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(ethereumnoncestate.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(ethereumnoncestate.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseUntil(); ok {
		_spec.SetField(ethereumnoncestate.FieldLeaseUntil, field.TypeTime, value)
	}
	if _u.mutation.LeaseUntilCleared() {
		_spec.ClearField(ethereumnoncestate.FieldLeaseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LastReconciledAt(); ok {
		_spec.SetField(ethereumnoncestate.FieldLastReconciledAt, field.TypeTime, value)
	}
	if _u.mutation.LastReconciledAtCleared() {
		_spec.ClearField(ethereumnoncestate.FieldLastReconciledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(ethereumnoncestate.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(ethereumnoncestate.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(ethereumnoncestate.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(ethereumnoncestate.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(ethereumnoncestate.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(ethereumnoncestate.FieldVersion, field.TypeInt, value)
	}
	_node = &EthereumNonceState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ethereumnoncestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
