// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/onchaindeposit"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OnchainDepositUpdate is the builder for updating OnchainDeposit entities.
type OnchainDepositUpdate struct {
	config
	hooks    []Hook
	mutation *OnchainDepositMutation
}

// Where appends a list predicates to the OnchainDepositUpdate builder.
func (_u *OnchainDepositUpdate) Where(ps ...predicate.OnchainDeposit) *OnchainDepositUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OnchainDepositUpdate) SetUpdatedAt(v time.Time) *OnchainDepositUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OnchainDepositUpdate) SetStatus(v string) *OnchainDepositUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableStatus(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetValidationError sets the "validation_error" field.
func (_u *OnchainDepositUpdate) SetValidationError(v string) *OnchainDepositUpdate {
	_u.mutation.SetValidationError(v)
	return _u
}

// SetNillableValidationError sets the "validation_error" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableValidationError(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetValidationError(*v)
	}
	return _u
}

// ClearValidationError clears the value of the "validation_error" field.
func (_u *OnchainDepositUpdate) ClearValidationError() *OnchainDepositUpdate {
	_u.mutation.ClearValidationError()
	return _u
}

// SetCreditAuditRef sets the "credit_audit_ref" field.
func (_u *OnchainDepositUpdate) SetCreditAuditRef(v string) *OnchainDepositUpdate {
	_u.mutation.SetCreditAuditRef(v)
	return _u
}

// SetNillableCreditAuditRef sets the "credit_audit_ref" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableCreditAuditRef(v *string) *OnchainDepositUpdate {
	if v != nil {
		_u.SetCreditAuditRef(*v)
	}
	return _u
}

// ClearCreditAuditRef clears the value of the "credit_audit_ref" field.
func (_u *OnchainDepositUpdate) ClearCreditAuditRef() *OnchainDepositUpdate {
	_u.mutation.ClearCreditAuditRef()
	return _u
}

// SetCreditedAt sets the "credited_at" field.
func (_u *OnchainDepositUpdate) SetCreditedAt(v time.Time) *OnchainDepositUpdate {
	_u.mutation.SetCreditedAt(v)
	return _u
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableCreditedAt(v *time.Time) *OnchainDepositUpdate {
	if v != nil {
		_u.SetCreditedAt(*v)
	}
	return _u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (_u *OnchainDepositUpdate) ClearCreditedAt() *OnchainDepositUpdate {
	_u.mutation.ClearCreditedAt()
	return _u
}

// SetVersion sets the "version" field.
func (_u *OnchainDepositUpdate) SetVersion(v int) *OnchainDepositUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *OnchainDepositUpdate) SetNillableVersion(v *int) *OnchainDepositUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *OnchainDepositUpdate) AddVersion(v int) *OnchainDepositUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the OnchainDepositMutation object of the builder.
func (_u *OnchainDepositUpdate) Mutation() *OnchainDepositMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OnchainDepositUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OnchainDepositUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OnchainDepositUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OnchainDepositUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OnchainDepositUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := onchaindeposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OnchainDepositUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := onchaindeposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreditAuditRef(); ok {
		if err := onchaindeposit.CreditAuditRefValidator(v); err != nil {
			return &ValidationError{Name: "credit_audit_ref", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.credit_audit_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := onchaindeposit.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.version": %w`, err)}
		}
	}
	if _u.mutation.IntentCleared() && len(_u.mutation.IntentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OnchainDeposit.intent"`)
	}
	return nil
}

func (_u *OnchainDepositUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(onchaindeposit.Table, onchaindeposit.Columns, sqlgraph.NewFieldSpec(onchaindeposit.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(onchaindeposit.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(onchaindeposit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidationError(); ok {
		_spec.SetField(onchaindeposit.FieldValidationError, field.TypeString, value)
	}
	if _u.mutation.ValidationErrorCleared() {
		_spec.ClearField(onchaindeposit.FieldValidationError, field.TypeString)
	}
	if value, ok := _u.mutation.CreditAuditRef(); ok {
		_spec.SetField(onchaindeposit.FieldCreditAuditRef, field.TypeString, value)
	}
	if _u.mutation.CreditAuditRefCleared() {
		_spec.ClearField(onchaindeposit.FieldCreditAuditRef, field.TypeString)
	}
	if value, ok := _u.mutation.CreditedAt(); ok {
		_spec.SetField(onchaindeposit.FieldCreditedAt, field.TypeTime, value)
	}
	if _u.mutation.CreditedAtCleared() {
		_spec.ClearField(onchaindeposit.FieldCreditedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(onchaindeposit.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(onchaindeposit.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onchaindeposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OnchainDepositUpdateOne is the builder for updating a single OnchainDeposit entity.
type OnchainDepositUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OnchainDepositMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OnchainDepositUpdateOne) SetUpdatedAt(v time.Time) *OnchainDepositUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OnchainDepositUpdateOne) SetStatus(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableStatus(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetValidationError sets the "validation_error" field.
func (_u *OnchainDepositUpdateOne) SetValidationError(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetValidationError(v)
	return _u
}

// SetNillableValidationError sets the "validation_error" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableValidationError(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetValidationError(*v)
	}
	return _u
}

// ClearValidationError clears the value of the "validation_error" field.
func (_u *OnchainDepositUpdateOne) ClearValidationError() *OnchainDepositUpdateOne {
	_u.mutation.ClearValidationError()
	return _u
}

// SetCreditAuditRef sets the "credit_audit_ref" field.
func (_u *OnchainDepositUpdateOne) SetCreditAuditRef(v string) *OnchainDepositUpdateOne {
	_u.mutation.SetCreditAuditRef(v)
	return _u
}

// SetNillableCreditAuditRef sets the "credit_audit_ref" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableCreditAuditRef(v *string) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetCreditAuditRef(*v)
	}
	return _u
}

// ClearCreditAuditRef clears the value of the "credit_audit_ref" field.
func (_u *OnchainDepositUpdateOne) ClearCreditAuditRef() *OnchainDepositUpdateOne {
	_u.mutation.ClearCreditAuditRef()
	return _u
}

// SetCreditedAt sets the "credited_at" field.
func (_u *OnchainDepositUpdateOne) SetCreditedAt(v time.Time) *OnchainDepositUpdateOne {
	_u.mutation.SetCreditedAt(v)
	return _u
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableCreditedAt(v *time.Time) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetCreditedAt(*v)
	}
	return _u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (_u *OnchainDepositUpdateOne) ClearCreditedAt() *OnchainDepositUpdateOne {
	_u.mutation.ClearCreditedAt()
	return _u
}

// SetVersion sets the "version" field.
func (_u *OnchainDepositUpdateOne) SetVersion(v int) *OnchainDepositUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *OnchainDepositUpdateOne) SetNillableVersion(v *int) *OnchainDepositUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *OnchainDepositUpdateOne) AddVersion(v int) *OnchainDepositUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the OnchainDepositMutation object of the builder.
func (_u *OnchainDepositUpdateOne) Mutation() *OnchainDepositMutation {
	return _u.mutation
}

// Where appends a list predicates to the OnchainDepositUpdate builder.
func (_u *OnchainDepositUpdateOne) Where(ps ...predicate.OnchainDeposit) *OnchainDepositUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OnchainDepositUpdateOne) Select(field string, fields ...string) *OnchainDepositUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OnchainDeposit entity.
func (_u *OnchainDepositUpdateOne) Save(ctx context.Context) (*OnchainDeposit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OnchainDepositUpdateOne) SaveX(ctx context.Context) *OnchainDeposit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OnchainDepositUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OnchainDepositUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OnchainDepositUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := onchaindeposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OnchainDepositUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := onchaindeposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreditAuditRef(); ok {
		if err := onchaindeposit.CreditAuditRefValidator(v); err != nil {
			return &ValidationError{Name: "credit_audit_ref", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.credit_audit_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := onchaindeposit.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "OnchainDeposit.version": %w`, err)}
		}
	}
	if _u.mutation.IntentCleared() && len(_u.mutation.IntentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OnchainDeposit.intent"`)
	}
	return nil
}

func (_u *OnchainDepositUpdateOne) sqlSave(ctx context.Context) (_node *OnchainDeposit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(onchaindeposit.Table, onchaindeposit.Columns, sqlgraph.NewFieldSpec(onchaindeposit.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OnchainDeposit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, onchaindeposit.FieldID)
		for _, f := range fields {
			if !onchaindeposit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != onchaindeposit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(onchaindeposit.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(onchaindeposit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidationError(); ok {
		_spec.SetField(onchaindeposit.FieldValidationError, field.TypeString, value)
	}
	if _u.mutation.ValidationErrorCleared() {
		_spec.ClearField(onchaindeposit.FieldValidationError, field.TypeString)
	}
	if value, ok := _u.mutation.CreditAuditRef(); ok {
		_spec.SetField(onchaindeposit.FieldCreditAuditRef, field.TypeString, value)
	}
	if _u.mutation.CreditAuditRefCleared() {
		_spec.ClearField(onchaindeposit.FieldCreditAuditRef, field.TypeString)
	}
	if value, ok := _u.mutation.CreditedAt(); ok {
		_spec.SetField(onchaindeposit.FieldCreditedAt, field.TypeTime, value)
	}
	if _u.mutation.CreditedAtCleared() {
		_spec.ClearField(onchaindeposit.FieldCreditedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(onchaindeposit.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(onchaindeposit.FieldVersion, field.TypeInt, value)
	}
	_node = &OnchainDeposit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{onchaindeposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
