// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/walletderivationcursor"
)

// WalletDerivationCursor is the model entity for the WalletDerivationCursor schema.
type WalletDerivationCursor struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Network holds the value of the "network" field.
	Network string `json:"network,omitempty"`
	// NextIndex holds the value of the "next_index" field.
	NextIndex int64 `json:"next_index,omitempty"`
	// Version holds the value of the "version" field.
	Version      int `json:"version,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WalletDerivationCursor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case walletderivationcursor.FieldID, walletderivationcursor.FieldNextIndex, walletderivationcursor.FieldVersion:
			values[i] = new(sql.NullInt64)
		case walletderivationcursor.FieldNetwork:
			values[i] = new(sql.NullString)
		case walletderivationcursor.FieldCreatedAt, walletderivationcursor.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WalletDerivationCursor fields.
func (_m *WalletDerivationCursor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case walletderivationcursor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case walletderivationcursor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case walletderivationcursor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case walletderivationcursor.FieldNetwork:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value.Valid {
				_m.Network = value.String
			}
		case walletderivationcursor.FieldNextIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field next_index", values[i])
			} else if value.Valid {
				_m.NextIndex = value.Int64
			}
		case walletderivationcursor.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WalletDerivationCursor.
// This includes values selected through modifiers, order, etc.
func (_m *WalletDerivationCursor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WalletDerivationCursor.
// Note that you need to call WalletDerivationCursor.Unwrap() before calling this method if this WalletDerivationCursor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WalletDerivationCursor) Update() *WalletDerivationCursorUpdateOne {
	return NewWalletDerivationCursorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WalletDerivationCursor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WalletDerivationCursor) Unwrap() *WalletDerivationCursor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WalletDerivationCursor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WalletDerivationCursor) String() string {
	var builder strings.Builder
	builder.WriteString("WalletDerivationCursor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(_m.Network)
	builder.WriteString(", ")
	builder.WriteString("next_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.NextIndex))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// WalletDerivationCursors is a parsable slice of WalletDerivationCursor.
type WalletDerivationCursors []*WalletDerivationCursor
