// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/onchainpaymentintent"
	"github.com/Wei-Shaw/sub2api/ent/walletsweep"
)

// WalletSweepCreate is the builder for creating a WalletSweep entity.
type WalletSweepCreate struct {
	config
	mutation *WalletSweepMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *WalletSweepCreate) SetCreatedAt(v time.Time) *WalletSweepCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableCreatedAt(v *time.Time) *WalletSweepCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WalletSweepCreate) SetUpdatedAt(v time.Time) *WalletSweepCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableUpdatedAt(v *time.Time) *WalletSweepCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetIntentID sets the "intent_id" field.
func (_c *WalletSweepCreate) SetIntentID(v int64) *WalletSweepCreate {
	_c.mutation.SetIntentID(v)
	return _c
}

// SetNetwork sets the "network" field.
func (_c *WalletSweepCreate) SetNetwork(v string) *WalletSweepCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetChainID sets the "chain_id" field.
func (_c *WalletSweepCreate) SetChainID(v int64) *WalletSweepCreate {
	_c.mutation.SetChainID(v)
	return _c
}

// SetSourceAddress sets the "source_address" field.
func (_c *WalletSweepCreate) SetSourceAddress(v string) *WalletSweepCreate {
	_c.mutation.SetSourceAddress(v)
	return _c
}

// SetDestinationAddress sets the "destination_address" field.
func (_c *WalletSweepCreate) SetDestinationAddress(v string) *WalletSweepCreate {
	_c.mutation.SetDestinationAddress(v)
	return _c
}

// SetBalanceSnapshotRaw sets the "balance_snapshot_raw" field.
func (_c *WalletSweepCreate) SetBalanceSnapshotRaw(v string) *WalletSweepCreate {
	_c.mutation.SetBalanceSnapshotRaw(v)
	return _c
}

// SetAmountRaw sets the "amount_raw" field.
func (_c *WalletSweepCreate) SetAmountRaw(v string) *WalletSweepCreate {
	_c.mutation.SetAmountRaw(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *WalletSweepCreate) SetIdempotencyKey(v string) *WalletSweepCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetSignerRequestDigest sets the "signer_request_digest" field.
func (_c *WalletSweepCreate) SetSignerRequestDigest(v string) *WalletSweepCreate {
	_c.mutation.SetSignerRequestDigest(v)
	return _c
}

// SetNillableSignerRequestDigest sets the "signer_request_digest" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableSignerRequestDigest(v *string) *WalletSweepCreate {
	if v != nil {
		_c.SetSignerRequestDigest(*v)
	}
	return _c
}

// SetSignerAuditID sets the "signer_audit_id" field.
func (_c *WalletSweepCreate) SetSignerAuditID(v string) *WalletSweepCreate {
	_c.mutation.SetSignerAuditID(v)
	return _c
}

// SetNillableSignerAuditID sets the "signer_audit_id" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableSignerAuditID(v *string) *WalletSweepCreate {
	if v != nil {
		_c.SetSignerAuditID(*v)
	}
	return _c
}

// SetTransactionID sets the "transaction_id" field.
func (_c *WalletSweepCreate) SetTransactionID(v string) *WalletSweepCreate {
	_c.mutation.SetTransactionID(v)
	return _c
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableTransactionID(v *string) *WalletSweepCreate {
	if v != nil {
		_c.SetTransactionID(*v)
	}
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *WalletSweepCreate) SetNonce(v int64) *WalletSweepCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableNonce(v *int64) *WalletSweepCreate {
	if v != nil {
		_c.SetNonce(*v)
	}
	return _c
}

// SetReplacementOfID sets the "replacement_of_id" field.
func (_c *WalletSweepCreate) SetReplacementOfID(v int64) *WalletSweepCreate {
	_c.mutation.SetReplacementOfID(v)
	return _c
}

// SetNillableReplacementOfID sets the "replacement_of_id" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableReplacementOfID(v *int64) *WalletSweepCreate {
	if v != nil {
		_c.SetReplacementOfID(*v)
	}
	return _c
}

// SetFeeRaw sets the "fee_raw" field.
func (_c *WalletSweepCreate) SetFeeRaw(v string) *WalletSweepCreate {
	_c.mutation.SetFeeRaw(v)
	return _c
}

// SetNillableFeeRaw sets the "fee_raw" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableFeeRaw(v *string) *WalletSweepCreate {
	if v != nil {
		_c.SetFeeRaw(*v)
	}
	return _c
}

// SetEnergyUsed sets the "energy_used" field.
func (_c *WalletSweepCreate) SetEnergyUsed(v int64) *WalletSweepCreate {
	_c.mutation.SetEnergyUsed(v)
	return _c
}

// SetNillableEnergyUsed sets the "energy_used" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableEnergyUsed(v *int64) *WalletSweepCreate {
	if v != nil {
		_c.SetEnergyUsed(*v)
	}
	return _c
}

// SetBandwidthUsed sets the "bandwidth_used" field.
func (_c *WalletSweepCreate) SetBandwidthUsed(v int64) *WalletSweepCreate {
	_c.mutation.SetBandwidthUsed(v)
	return _c
}

// SetNillableBandwidthUsed sets the "bandwidth_used" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableBandwidthUsed(v *int64) *WalletSweepCreate {
	if v != nil {
		_c.SetBandwidthUsed(*v)
	}
	return _c
}

// SetFinalizedBlockHeight sets the "finalized_block_height" field.
func (_c *WalletSweepCreate) SetFinalizedBlockHeight(v int64) *WalletSweepCreate {
	_c.mutation.SetFinalizedBlockHeight(v)
	return _c
}

// SetNillableFinalizedBlockHeight sets the "finalized_block_height" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableFinalizedBlockHeight(v *int64) *WalletSweepCreate {
	if v != nil {
		_c.SetFinalizedBlockHeight(*v)
	}
	return _c
}

// SetFinalizedBlockHash sets the "finalized_block_hash" field.
func (_c *WalletSweepCreate) SetFinalizedBlockHash(v string) *WalletSweepCreate {
	_c.mutation.SetFinalizedBlockHash(v)
	return _c
}

// SetNillableFinalizedBlockHash sets the "finalized_block_hash" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableFinalizedBlockHash(v *string) *WalletSweepCreate {
	if v != nil {
		_c.SetFinalizedBlockHash(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WalletSweepCreate) SetStatus(v string) *WalletSweepCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableStatus(v *string) *WalletSweepCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *WalletSweepCreate) SetRetryCount(v int) *WalletSweepCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableRetryCount(v *int) *WalletSweepCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetFailureCode sets the "failure_code" field.
func (_c *WalletSweepCreate) SetFailureCode(v string) *WalletSweepCreate {
	_c.mutation.SetFailureCode(v)
	return _c
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableFailureCode(v *string) *WalletSweepCreate {
	if v != nil {
		_c.SetFailureCode(*v)
	}
	return _c
}

// SetFailureReason sets the "failure_reason" field.
func (_c *WalletSweepCreate) SetFailureReason(v string) *WalletSweepCreate {
	_c.mutation.SetFailureReason(v)
	return _c
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableFailureReason(v *string) *WalletSweepCreate {
	if v != nil {
		_c.SetFailureReason(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *WalletSweepCreate) SetNextAttemptAt(v time.Time) *WalletSweepCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableNextAttemptAt(v *time.Time) *WalletSweepCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetFinalizedAt sets the "finalized_at" field.
func (_c *WalletSweepCreate) SetFinalizedAt(v time.Time) *WalletSweepCreate {
	_c.mutation.SetFinalizedAt(v)
	return _c
}

// SetNillableFinalizedAt sets the "finalized_at" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableFinalizedAt(v *time.Time) *WalletSweepCreate {
	if v != nil {
		_c.SetFinalizedAt(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *WalletSweepCreate) SetVersion(v int) *WalletSweepCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *WalletSweepCreate) SetNillableVersion(v *int) *WalletSweepCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetIntent sets the "intent" edge to the OnchainPaymentIntent entity.
func (_c *WalletSweepCreate) SetIntent(v *OnchainPaymentIntent) *WalletSweepCreate {
	return _c.SetIntentID(v.ID)
}

// Mutation returns the WalletSweepMutation object of the builder.
func (_c *WalletSweepCreate) Mutation() *WalletSweepMutation {
	return _c.mutation
}

// Save creates the WalletSweep in the database.
func (_c *WalletSweepCreate) Save(ctx context.Context) (*WalletSweep, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WalletSweepCreate) SaveX(ctx context.Context) *WalletSweep {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletSweepCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletSweepCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WalletSweepCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := walletsweep.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := walletsweep.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.FeeRaw(); !ok {
		v := walletsweep.DefaultFeeRaw
		_c.mutation.SetFeeRaw(v)
	}
	if _, ok := _c.mutation.EnergyUsed(); !ok {
		v := walletsweep.DefaultEnergyUsed
		_c.mutation.SetEnergyUsed(v)
	}
	if _, ok := _c.mutation.BandwidthUsed(); !ok {
		v := walletsweep.DefaultBandwidthUsed
		_c.mutation.SetBandwidthUsed(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := walletsweep.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := walletsweep.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := walletsweep.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WalletSweepCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WalletSweep.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WalletSweep.updated_at"`)}
	}
	if _, ok := _c.mutation.IntentID(); !ok {
		return &ValidationError{Name: "intent_id", err: errors.New(`ent: missing required field "WalletSweep.intent_id"`)}
	}
	if v, ok := _c.mutation.IntentID(); ok {
		if err := walletsweep.IntentIDValidator(v); err != nil {
			return &ValidationError{Name: "intent_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.intent_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "WalletSweep.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := walletsweep.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChainID(); !ok {
		return &ValidationError{Name: "chain_id", err: errors.New(`ent: missing required field "WalletSweep.chain_id"`)}
	}
	if v, ok := _c.mutation.ChainID(); ok {
		if err := walletsweep.ChainIDValidator(v); err != nil {
			return &ValidationError{Name: "chain_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.chain_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceAddress(); !ok {
		return &ValidationError{Name: "source_address", err: errors.New(`ent: missing required field "WalletSweep.source_address"`)}
	}
	if v, ok := _c.mutation.SourceAddress(); ok {
		if err := walletsweep.SourceAddressValidator(v); err != nil {
			return &ValidationError{Name: "source_address", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.source_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DestinationAddress(); !ok {
		return &ValidationError{Name: "destination_address", err: errors.New(`ent: missing required field "WalletSweep.destination_address"`)}
	}
	if v, ok := _c.mutation.DestinationAddress(); ok {
		if err := walletsweep.DestinationAddressValidator(v); err != nil {
			return &ValidationError{Name: "destination_address", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.destination_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceSnapshotRaw(); !ok {
		return &ValidationError{Name: "balance_snapshot_raw", err: errors.New(`ent: missing required field "WalletSweep.balance_snapshot_raw"`)}
	}
	if _, ok := _c.mutation.AmountRaw(); !ok {
		return &ValidationError{Name: "amount_raw", err: errors.New(`ent: missing required field "WalletSweep.amount_raw"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "WalletSweep.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := walletsweep.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SignerRequestDigest(); ok {
		if err := walletsweep.SignerRequestDigestValidator(v); err != nil {
			return &ValidationError{Name: "signer_request_digest", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.signer_request_digest": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SignerAuditID(); ok {
		if err := walletsweep.SignerAuditIDValidator(v); err != nil {
			return &ValidationError{Name: "signer_audit_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.signer_audit_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TransactionID(); ok {
		if err := walletsweep.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.transaction_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Nonce(); ok {
		if err := walletsweep.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.nonce": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ReplacementOfID(); ok {
		if err := walletsweep.ReplacementOfIDValidator(v); err != nil {
			return &ValidationError{Name: "replacement_of_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.replacement_of_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FeeRaw(); !ok {
		return &ValidationError{Name: "fee_raw", err: errors.New(`ent: missing required field "WalletSweep.fee_raw"`)}
	}
	if _, ok := _c.mutation.EnergyUsed(); !ok {
		return &ValidationError{Name: "energy_used", err: errors.New(`ent: missing required field "WalletSweep.energy_used"`)}
	}
	if v, ok := _c.mutation.EnergyUsed(); ok {
		if err := walletsweep.EnergyUsedValidator(v); err != nil {
			return &ValidationError{Name: "energy_used", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.energy_used": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BandwidthUsed(); !ok {
		return &ValidationError{Name: "bandwidth_used", err: errors.New(`ent: missing required field "WalletSweep.bandwidth_used"`)}
	}
	if v, ok := _c.mutation.BandwidthUsed(); ok {
		if err := walletsweep.BandwidthUsedValidator(v); err != nil {
			return &ValidationError{Name: "bandwidth_used", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.bandwidth_used": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FinalizedBlockHeight(); ok {
		if err := walletsweep.FinalizedBlockHeightValidator(v); err != nil {
			return &ValidationError{Name: "finalized_block_height", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.finalized_block_height": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FinalizedBlockHash(); ok {
		if err := walletsweep.FinalizedBlockHashValidator(v); err != nil {
			return &ValidationError{Name: "finalized_block_hash", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.finalized_block_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WalletSweep.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := walletsweep.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "WalletSweep.retry_count"`)}
	}
	if v, ok := _c.mutation.RetryCount(); ok {
		if err := walletsweep.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.retry_count": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FailureCode(); ok {
		if err := walletsweep.FailureCodeValidator(v); err != nil {
			return &ValidationError{Name: "failure_code", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.failure_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "WalletSweep.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := walletsweep.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.version": %w`, err)}
		}
	}
	if len(_c.mutation.IntentIDs()) == 0 {
		return &ValidationError{Name: "intent", err: errors.New(`ent: missing required edge "WalletSweep.intent"`)}
	}
	return nil
}

func (_c *WalletSweepCreate) sqlSave(ctx context.Context) (*WalletSweep, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WalletSweepCreate) createSpec() (*WalletSweep, *sqlgraph.CreateSpec) {
	var (
		_node = &WalletSweep{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(walletsweep.Table, sqlgraph.NewFieldSpec(walletsweep.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(walletsweep.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(walletsweep.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(walletsweep.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.ChainID(); ok {
		_spec.SetField(walletsweep.FieldChainID, field.TypeInt64, value)
		_node.ChainID = value
	}
	if value, ok := _c.mutation.SourceAddress(); ok {
		_spec.SetField(walletsweep.FieldSourceAddress, field.TypeString, value)
		_node.SourceAddress = value
	}
	if value, ok := _c.mutation.DestinationAddress(); ok {
		_spec.SetField(walletsweep.FieldDestinationAddress, field.TypeString, value)
		_node.DestinationAddress = value
	}
	if value, ok := _c.mutation.BalanceSnapshotRaw(); ok {
		_spec.SetField(walletsweep.FieldBalanceSnapshotRaw, field.TypeString, value)
		_node.BalanceSnapshotRaw = value
	}
	if value, ok := _c.mutation.AmountRaw(); ok {
		_spec.SetField(walletsweep.FieldAmountRaw, field.TypeString, value)
		_node.AmountRaw = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(walletsweep.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.SignerRequestDigest(); ok {
		_spec.SetField(walletsweep.FieldSignerRequestDigest, field.TypeString, value)
		_node.SignerRequestDigest = &value
	}
	if value, ok := _c.mutation.SignerAuditID(); ok {
		_spec.SetField(walletsweep.FieldSignerAuditID, field.TypeString, value)
		_node.SignerAuditID = &value
	}
	if value, ok := _c.mutation.TransactionID(); ok {
		_spec.SetField(walletsweep.FieldTransactionID, field.TypeString, value)
		_node.TransactionID = &value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(walletsweep.FieldNonce, field.TypeInt64, value)
		_node.Nonce = &value
	}
	if value, ok := _c.mutation.ReplacementOfID(); ok {
		_spec.SetField(walletsweep.FieldReplacementOfID, field.TypeInt64, value)
		_node.ReplacementOfID = &value
	}
	if value, ok := _c.mutation.FeeRaw(); ok {
		_spec.SetField(walletsweep.FieldFeeRaw, field.TypeString, value)
		_node.FeeRaw = value
	}
	if value, ok := _c.mutation.EnergyUsed(); ok {
		_spec.SetField(walletsweep.FieldEnergyUsed, field.TypeInt64, value)
		_node.EnergyUsed = value
	}
	if value, ok := _c.mutation.BandwidthUsed(); ok {
		_spec.SetField(walletsweep.FieldBandwidthUsed, field.TypeInt64, value)
		_node.BandwidthUsed = value
	}
	if value, ok := _c.mutation.FinalizedBlockHeight(); ok {
		_spec.SetField(walletsweep.FieldFinalizedBlockHeight, field.TypeInt64, value)
		_node.FinalizedBlockHeight = &value
	}
	if value, ok := _c.mutation.FinalizedBlockHash(); ok {
		_spec.SetField(walletsweep.FieldFinalizedBlockHash, field.TypeString, value)
		_node.FinalizedBlockHash = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(walletsweep.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(walletsweep.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.FailureCode(); ok {
		_spec.SetField(walletsweep.FieldFailureCode, field.TypeString, value)
		_node.FailureCode = &value
	}
	if value, ok := _c.mutation.FailureReason(); ok {
		_spec.SetField(walletsweep.FieldFailureReason, field.TypeString, value)
		_node.FailureReason = &value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(walletsweep.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = &value
	}
	if value, ok := _c.mutation.FinalizedAt(); ok {
		_spec.SetField(walletsweep.FieldFinalizedAt, field.TypeTime, value)
		_node.FinalizedAt = &value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(walletsweep.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if nodes := _c.mutation.IntentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   walletsweep.IntentTable,
			Columns: []string{walletsweep.IntentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(onchainpaymentintent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IntentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WalletSweep.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WalletSweepUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WalletSweepCreate) OnConflict(opts ...sql.ConflictOption) *WalletSweepUpsertOne {
	_c.conflict = opts
	return &WalletSweepUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WalletSweep.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WalletSweepCreate) OnConflictColumns(columns ...string) *WalletSweepUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WalletSweepUpsertOne{
		create: _c,
	}
}

type (
	// WalletSweepUpsertOne is the builder for "upsert"-ing
	//  one WalletSweep node.
	WalletSweepUpsertOne struct {
		create *WalletSweepCreate
	}

	// WalletSweepUpsert is the "OnConflict" setter.
	WalletSweepUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletSweepUpsert) SetUpdatedAt(v time.Time) *WalletSweepUpsert {
	u.Set(walletsweep.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateUpdatedAt() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldUpdatedAt)
	return u
}

// SetSignerRequestDigest sets the "signer_request_digest" field.
func (u *WalletSweepUpsert) SetSignerRequestDigest(v string) *WalletSweepUpsert {
	u.Set(walletsweep.FieldSignerRequestDigest, v)
	return u
}

// UpdateSignerRequestDigest sets the "signer_request_digest" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateSignerRequestDigest() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldSignerRequestDigest)
	return u
}

// ClearSignerRequestDigest clears the value of the "signer_request_digest" field.
func (u *WalletSweepUpsert) ClearSignerRequestDigest() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldSignerRequestDigest)
	return u
}

// SetSignerAuditID sets the "signer_audit_id" field.
func (u *WalletSweepUpsert) SetSignerAuditID(v string) *WalletSweepUpsert {
	u.Set(walletsweep.FieldSignerAuditID, v)
	return u
}

// UpdateSignerAuditID sets the "signer_audit_id" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateSignerAuditID() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldSignerAuditID)
	return u
}

// ClearSignerAuditID clears the value of the "signer_audit_id" field.
func (u *WalletSweepUpsert) ClearSignerAuditID() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldSignerAuditID)
	return u
}

// SetTransactionID sets the "transaction_id" field.
func (u *WalletSweepUpsert) SetTransactionID(v string) *WalletSweepUpsert {
	u.Set(walletsweep.FieldTransactionID, v)
	return u
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateTransactionID() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldTransactionID)
	return u
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (u *WalletSweepUpsert) ClearTransactionID() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldTransactionID)
	return u
}

// SetNonce sets the "nonce" field.
func (u *WalletSweepUpsert) SetNonce(v int64) *WalletSweepUpsert {
	u.Set(walletsweep.FieldNonce, v)
	return u
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateNonce() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldNonce)
	return u
}

// AddNonce adds v to the "nonce" field.
func (u *WalletSweepUpsert) AddNonce(v int64) *WalletSweepUpsert {
	u.Add(walletsweep.FieldNonce, v)
	return u
}

// ClearNonce clears the value of the "nonce" field.
func (u *WalletSweepUpsert) ClearNonce() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldNonce)
	return u
}

// SetReplacementOfID sets the "replacement_of_id" field.
func (u *WalletSweepUpsert) SetReplacementOfID(v int64) *WalletSweepUpsert {
	u.Set(walletsweep.FieldReplacementOfID, v)
	return u
}

// UpdateReplacementOfID sets the "replacement_of_id" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateReplacementOfID() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldReplacementOfID)
	return u
}

// AddReplacementOfID adds v to the "replacement_of_id" field.
func (u *WalletSweepUpsert) AddReplacementOfID(v int64) *WalletSweepUpsert {
	u.Add(walletsweep.FieldReplacementOfID, v)
	return u
}

// ClearReplacementOfID clears the value of the "replacement_of_id" field.
func (u *WalletSweepUpsert) ClearReplacementOfID() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldReplacementOfID)
	return u
}

// SetFeeRaw sets the "fee_raw" field.
func (u *WalletSweepUpsert) SetFeeRaw(v string) *WalletSweepUpsert {
	u.Set(walletsweep.FieldFeeRaw, v)
	return u
}

// UpdateFeeRaw sets the "fee_raw" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateFeeRaw() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldFeeRaw)
	return u
}

// SetEnergyUsed sets the "energy_used" field.
func (u *WalletSweepUpsert) SetEnergyUsed(v int64) *WalletSweepUpsert {
	u.Set(walletsweep.FieldEnergyUsed, v)
	return u
}

// UpdateEnergyUsed sets the "energy_used" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateEnergyUsed() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldEnergyUsed)
	return u
}

// AddEnergyUsed adds v to the "energy_used" field.
func (u *WalletSweepUpsert) AddEnergyUsed(v int64) *WalletSweepUpsert {
	u.Add(walletsweep.FieldEnergyUsed, v)
	return u
}

// SetBandwidthUsed sets the "bandwidth_used" field.
func (u *WalletSweepUpsert) SetBandwidthUsed(v int64) *WalletSweepUpsert {
	u.Set(walletsweep.FieldBandwidthUsed, v)
	return u
}

// UpdateBandwidthUsed sets the "bandwidth_used" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateBandwidthUsed() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldBandwidthUsed)
	return u
}

// AddBandwidthUsed adds v to the "bandwidth_used" field.
func (u *WalletSweepUpsert) AddBandwidthUsed(v int64) *WalletSweepUpsert {
	u.Add(walletsweep.FieldBandwidthUsed, v)
	return u
}

// SetFinalizedBlockHeight sets the "finalized_block_height" field.
func (u *WalletSweepUpsert) SetFinalizedBlockHeight(v int64) *WalletSweepUpsert {
	u.Set(walletsweep.FieldFinalizedBlockHeight, v)
	return u
}

// UpdateFinalizedBlockHeight sets the "finalized_block_height" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateFinalizedBlockHeight() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldFinalizedBlockHeight)
	return u
}

// AddFinalizedBlockHeight adds v to the "finalized_block_height" field.
func (u *WalletSweepUpsert) AddFinalizedBlockHeight(v int64) *WalletSweepUpsert {
	u.Add(walletsweep.FieldFinalizedBlockHeight, v)
	return u
}

// ClearFinalizedBlockHeight clears the value of the "finalized_block_height" field.
func (u *WalletSweepUpsert) ClearFinalizedBlockHeight() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldFinalizedBlockHeight)
	return u
}

// SetFinalizedBlockHash sets the "finalized_block_hash" field.
func (u *WalletSweepUpsert) SetFinalizedBlockHash(v string) *WalletSweepUpsert {
	u.Set(walletsweep.FieldFinalizedBlockHash, v)
	return u
}

// UpdateFinalizedBlockHash sets the "finalized_block_hash" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateFinalizedBlockHash() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldFinalizedBlockHash)
	return u
}

// ClearFinalizedBlockHash clears the value of the "finalized_block_hash" field.
func (u *WalletSweepUpsert) ClearFinalizedBlockHash() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldFinalizedBlockHash)
	return u
}

// SetStatus sets the "status" field.
func (u *WalletSweepUpsert) SetStatus(v string) *WalletSweepUpsert {
	u.Set(walletsweep.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateStatus() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldStatus)
	return u
}

// SetRetryCount sets the "retry_count" field.
func (u *WalletSweepUpsert) SetRetryCount(v int) *WalletSweepUpsert {
	u.Set(walletsweep.FieldRetryCount, v)
	return u
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateRetryCount() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldRetryCount)
	return u
}

// AddRetryCount adds v to the "retry_count" field.
func (u *WalletSweepUpsert) AddRetryCount(v int) *WalletSweepUpsert {
	u.Add(walletsweep.FieldRetryCount, v)
	return u
}

// SetFailureCode sets the "failure_code" field.
func (u *WalletSweepUpsert) SetFailureCode(v string) *WalletSweepUpsert {
	u.Set(walletsweep.FieldFailureCode, v)
	return u
}

// UpdateFailureCode sets the "failure_code" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateFailureCode() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldFailureCode)
	return u
}

// ClearFailureCode clears the value of the "failure_code" field.
func (u *WalletSweepUpsert) ClearFailureCode() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldFailureCode)
	return u
}

// SetFailureReason sets the "failure_reason" field.
func (u *WalletSweepUpsert) SetFailureReason(v string) *WalletSweepUpsert {
	u.Set(walletsweep.FieldFailureReason, v)
	return u
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateFailureReason() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldFailureReason)
	return u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (u *WalletSweepUpsert) ClearFailureReason() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldFailureReason)
	return u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *WalletSweepUpsert) SetNextAttemptAt(v time.Time) *WalletSweepUpsert {
	u.Set(walletsweep.FieldNextAttemptAt, v)
	return u
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateNextAttemptAt() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldNextAttemptAt)
	return u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *WalletSweepUpsert) ClearNextAttemptAt() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldNextAttemptAt)
	return u
}

// SetFinalizedAt sets the "finalized_at" field.
func (u *WalletSweepUpsert) SetFinalizedAt(v time.Time) *WalletSweepUpsert {
	u.Set(walletsweep.FieldFinalizedAt, v)
	return u
}

// UpdateFinalizedAt sets the "finalized_at" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateFinalizedAt() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldFinalizedAt)
	return u
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (u *WalletSweepUpsert) ClearFinalizedAt() *WalletSweepUpsert {
	u.SetNull(walletsweep.FieldFinalizedAt)
	return u
}

// SetVersion sets the "version" field.
func (u *WalletSweepUpsert) SetVersion(v int) *WalletSweepUpsert {
	u.Set(walletsweep.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *WalletSweepUpsert) UpdateVersion() *WalletSweepUpsert {
	u.SetExcluded(walletsweep.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *WalletSweepUpsert) AddVersion(v int) *WalletSweepUpsert {
	u.Add(walletsweep.FieldVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WalletSweep.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WalletSweepUpsertOne) UpdateNewValues() *WalletSweepUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(walletsweep.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.IntentID(); exists {
			s.SetIgnore(walletsweep.FieldIntentID)
		}
		if _, exists := u.create.mutation.Network(); exists {
			s.SetIgnore(walletsweep.FieldNetwork)
		}
		if _, exists := u.create.mutation.ChainID(); exists {
			s.SetIgnore(walletsweep.FieldChainID)
		}
		if _, exists := u.create.mutation.SourceAddress(); exists {
			s.SetIgnore(walletsweep.FieldSourceAddress)
		}
		if _, exists := u.create.mutation.DestinationAddress(); exists {
			s.SetIgnore(walletsweep.FieldDestinationAddress)
		}
		if _, exists := u.create.mutation.BalanceSnapshotRaw(); exists {
			s.SetIgnore(walletsweep.FieldBalanceSnapshotRaw)
		}
		if _, exists := u.create.mutation.AmountRaw(); exists {
			s.SetIgnore(walletsweep.FieldAmountRaw)
		}
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(walletsweep.FieldIdempotencyKey)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WalletSweep.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WalletSweepUpsertOne) Ignore() *WalletSweepUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WalletSweepUpsertOne) DoNothing() *WalletSweepUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WalletSweepCreate.OnConflict
// documentation for more info.
func (u *WalletSweepUpsertOne) Update(set func(*WalletSweepUpsert)) *WalletSweepUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WalletSweepUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletSweepUpsertOne) SetUpdatedAt(v time.Time) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateUpdatedAt() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSignerRequestDigest sets the "signer_request_digest" field.
func (u *WalletSweepUpsertOne) SetSignerRequestDigest(v string) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetSignerRequestDigest(v)
	})
}

// UpdateSignerRequestDigest sets the "signer_request_digest" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateSignerRequestDigest() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateSignerRequestDigest()
	})
}

// ClearSignerRequestDigest clears the value of the "signer_request_digest" field.
func (u *WalletSweepUpsertOne) ClearSignerRequestDigest() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearSignerRequestDigest()
	})
}

// SetSignerAuditID sets the "signer_audit_id" field.
func (u *WalletSweepUpsertOne) SetSignerAuditID(v string) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetSignerAuditID(v)
	})
}

// UpdateSignerAuditID sets the "signer_audit_id" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateSignerAuditID() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateSignerAuditID()
	})
}

// ClearSignerAuditID clears the value of the "signer_audit_id" field.
func (u *WalletSweepUpsertOne) ClearSignerAuditID() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearSignerAuditID()
	})
}

// SetTransactionID sets the "transaction_id" field.
func (u *WalletSweepUpsertOne) SetTransactionID(v string) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetTransactionID(v)
	})
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateTransactionID() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateTransactionID()
	})
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (u *WalletSweepUpsertOne) ClearTransactionID() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearTransactionID()
	})
}

// SetNonce sets the "nonce" field.
func (u *WalletSweepUpsertOne) SetNonce(v int64) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetNonce(v)
	})
}

// AddNonce adds v to the "nonce" field.
func (u *WalletSweepUpsertOne) AddNonce(v int64) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateNonce() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateNonce()
	})
}

// ClearNonce clears the value of the "nonce" field.
func (u *WalletSweepUpsertOne) ClearNonce() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearNonce()
	})
}

// SetReplacementOfID sets the "replacement_of_id" field.
func (u *WalletSweepUpsertOne) SetReplacementOfID(v int64) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetReplacementOfID(v)
	})
}

// AddReplacementOfID adds v to the "replacement_of_id" field.
func (u *WalletSweepUpsertOne) AddReplacementOfID(v int64) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddReplacementOfID(v)
	})
}

// UpdateReplacementOfID sets the "replacement_of_id" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateReplacementOfID() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateReplacementOfID()
	})
}

// ClearReplacementOfID clears the value of the "replacement_of_id" field.
func (u *WalletSweepUpsertOne) ClearReplacementOfID() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearReplacementOfID()
	})
}

// SetFeeRaw sets the "fee_raw" field.
func (u *WalletSweepUpsertOne) SetFeeRaw(v string) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFeeRaw(v)
	})
}

// UpdateFeeRaw sets the "fee_raw" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateFeeRaw() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFeeRaw()
	})
}

// SetEnergyUsed sets the "energy_used" field.
func (u *WalletSweepUpsertOne) SetEnergyUsed(v int64) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetEnergyUsed(v)
	})
}

// AddEnergyUsed adds v to the "energy_used" field.
func (u *WalletSweepUpsertOne) AddEnergyUsed(v int64) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddEnergyUsed(v)
	})
}

// UpdateEnergyUsed sets the "energy_used" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateEnergyUsed() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateEnergyUsed()
	})
}

// SetBandwidthUsed sets the "bandwidth_used" field.
func (u *WalletSweepUpsertOne) SetBandwidthUsed(v int64) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetBandwidthUsed(v)
	})
}

// AddBandwidthUsed adds v to the "bandwidth_used" field.
func (u *WalletSweepUpsertOne) AddBandwidthUsed(v int64) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddBandwidthUsed(v)
	})
}

// UpdateBandwidthUsed sets the "bandwidth_used" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateBandwidthUsed() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateBandwidthUsed()
	})
}

// SetFinalizedBlockHeight sets the "finalized_block_height" field.
func (u *WalletSweepUpsertOne) SetFinalizedBlockHeight(v int64) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFinalizedBlockHeight(v)
	})
}

// AddFinalizedBlockHeight adds v to the "finalized_block_height" field.
func (u *WalletSweepUpsertOne) AddFinalizedBlockHeight(v int64) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddFinalizedBlockHeight(v)
	})
}

// UpdateFinalizedBlockHeight sets the "finalized_block_height" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateFinalizedBlockHeight() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFinalizedBlockHeight()
	})
}

// ClearFinalizedBlockHeight clears the value of the "finalized_block_height" field.
func (u *WalletSweepUpsertOne) ClearFinalizedBlockHeight() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearFinalizedBlockHeight()
	})
}

// SetFinalizedBlockHash sets the "finalized_block_hash" field.
func (u *WalletSweepUpsertOne) SetFinalizedBlockHash(v string) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFinalizedBlockHash(v)
	})
}

// UpdateFinalizedBlockHash sets the "finalized_block_hash" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateFinalizedBlockHash() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFinalizedBlockHash()
	})
}

// ClearFinalizedBlockHash clears the value of the "finalized_block_hash" field.
func (u *WalletSweepUpsertOne) ClearFinalizedBlockHash() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearFinalizedBlockHash()
	})
}

// SetStatus sets the "status" field.
func (u *WalletSweepUpsertOne) SetStatus(v string) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateStatus() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateStatus()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *WalletSweepUpsertOne) SetRetryCount(v int) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *WalletSweepUpsertOne) AddRetryCount(v int) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateRetryCount() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateRetryCount()
	})
}

// SetFailureCode sets the "failure_code" field.
func (u *WalletSweepUpsertOne) SetFailureCode(v string) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFailureCode(v)
	})
}

// UpdateFailureCode sets the "failure_code" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateFailureCode() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFailureCode()
	})
}

// ClearFailureCode clears the value of the "failure_code" field.
func (u *WalletSweepUpsertOne) ClearFailureCode() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearFailureCode()
	})
}

// SetFailureReason sets the "failure_reason" field.
func (u *WalletSweepUpsertOne) SetFailureReason(v string) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFailureReason(v)
	})
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateFailureReason() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFailureReason()
	})
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (u *WalletSweepUpsertOne) ClearFailureReason() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearFailureReason()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *WalletSweepUpsertOne) SetNextAttemptAt(v time.Time) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateNextAttemptAt() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *WalletSweepUpsertOne) ClearNextAttemptAt() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearNextAttemptAt()
	})
}

// SetFinalizedAt sets the "finalized_at" field.
func (u *WalletSweepUpsertOne) SetFinalizedAt(v time.Time) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFinalizedAt(v)
	})
}

// UpdateFinalizedAt sets the "finalized_at" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateFinalizedAt() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFinalizedAt()
	})
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (u *WalletSweepUpsertOne) ClearFinalizedAt() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearFinalizedAt()
	})
}

// SetVersion sets the "version" field.
func (u *WalletSweepUpsertOne) SetVersion(v int) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *WalletSweepUpsertOne) AddVersion(v int) *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *WalletSweepUpsertOne) UpdateVersion() *WalletSweepUpsertOne {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *WalletSweepUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WalletSweepCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WalletSweepUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WalletSweepUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WalletSweepUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WalletSweepCreateBulk is the builder for creating many WalletSweep entities in bulk.
type WalletSweepCreateBulk struct {
	config
	err      error
	builders []*WalletSweepCreate
	conflict []sql.ConflictOption
}

// Save creates the WalletSweep entities in the database.
func (_c *WalletSweepCreateBulk) Save(ctx context.Context) ([]*WalletSweep, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WalletSweep, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WalletSweepMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WalletSweepCreateBulk) SaveX(ctx context.Context) []*WalletSweep {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletSweepCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletSweepCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WalletSweep.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WalletSweepUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WalletSweepCreateBulk) OnConflict(opts ...sql.ConflictOption) *WalletSweepUpsertBulk {
	_c.conflict = opts
	return &WalletSweepUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WalletSweep.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WalletSweepCreateBulk) OnConflictColumns(columns ...string) *WalletSweepUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WalletSweepUpsertBulk{
		create: _c,
	}
}

// WalletSweepUpsertBulk is the builder for "upsert"-ing
// a bulk of WalletSweep nodes.
type WalletSweepUpsertBulk struct {
	create *WalletSweepCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WalletSweep.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WalletSweepUpsertBulk) UpdateNewValues() *WalletSweepUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(walletsweep.FieldCreatedAt)
			}
			if _, exists := b.mutation.IntentID(); exists {
				s.SetIgnore(walletsweep.FieldIntentID)
			}
			if _, exists := b.mutation.Network(); exists {
				s.SetIgnore(walletsweep.FieldNetwork)
			}
			if _, exists := b.mutation.ChainID(); exists {
				s.SetIgnore(walletsweep.FieldChainID)
			}
			if _, exists := b.mutation.SourceAddress(); exists {
				s.SetIgnore(walletsweep.FieldSourceAddress)
			}
			if _, exists := b.mutation.DestinationAddress(); exists {
				s.SetIgnore(walletsweep.FieldDestinationAddress)
			}
			if _, exists := b.mutation.BalanceSnapshotRaw(); exists {
				s.SetIgnore(walletsweep.FieldBalanceSnapshotRaw)
			}
			if _, exists := b.mutation.AmountRaw(); exists {
				s.SetIgnore(walletsweep.FieldAmountRaw)
			}
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(walletsweep.FieldIdempotencyKey)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WalletSweep.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WalletSweepUpsertBulk) Ignore() *WalletSweepUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WalletSweepUpsertBulk) DoNothing() *WalletSweepUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WalletSweepCreateBulk.OnConflict
// documentation for more info.
func (u *WalletSweepUpsertBulk) Update(set func(*WalletSweepUpsert)) *WalletSweepUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WalletSweepUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WalletSweepUpsertBulk) SetUpdatedAt(v time.Time) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateUpdatedAt() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSignerRequestDigest sets the "signer_request_digest" field.
func (u *WalletSweepUpsertBulk) SetSignerRequestDigest(v string) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetSignerRequestDigest(v)
	})
}

// UpdateSignerRequestDigest sets the "signer_request_digest" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateSignerRequestDigest() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateSignerRequestDigest()
	})
}

// ClearSignerRequestDigest clears the value of the "signer_request_digest" field.
func (u *WalletSweepUpsertBulk) ClearSignerRequestDigest() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearSignerRequestDigest()
	})
}

// SetSignerAuditID sets the "signer_audit_id" field.
func (u *WalletSweepUpsertBulk) SetSignerAuditID(v string) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetSignerAuditID(v)
	})
}

// UpdateSignerAuditID sets the "signer_audit_id" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateSignerAuditID() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateSignerAuditID()
	})
}

// ClearSignerAuditID clears the value of the "signer_audit_id" field.
func (u *WalletSweepUpsertBulk) ClearSignerAuditID() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearSignerAuditID()
	})
}

// SetTransactionID sets the "transaction_id" field.
func (u *WalletSweepUpsertBulk) SetTransactionID(v string) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetTransactionID(v)
	})
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateTransactionID() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateTransactionID()
	})
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (u *WalletSweepUpsertBulk) ClearTransactionID() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearTransactionID()
	})
}

// SetNonce sets the "nonce" field.
func (u *WalletSweepUpsertBulk) SetNonce(v int64) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetNonce(v)
	})
}

// AddNonce adds v to the "nonce" field.
func (u *WalletSweepUpsertBulk) AddNonce(v int64) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateNonce() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateNonce()
	})
}

// ClearNonce clears the value of the "nonce" field.
func (u *WalletSweepUpsertBulk) ClearNonce() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearNonce()
	})
}

// SetReplacementOfID sets the "replacement_of_id" field.
func (u *WalletSweepUpsertBulk) SetReplacementOfID(v int64) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetReplacementOfID(v)
	})
}

// AddReplacementOfID adds v to the "replacement_of_id" field.
func (u *WalletSweepUpsertBulk) AddReplacementOfID(v int64) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddReplacementOfID(v)
	})
}

// UpdateReplacementOfID sets the "replacement_of_id" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateReplacementOfID() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateReplacementOfID()
	})
}

// ClearReplacementOfID clears the value of the "replacement_of_id" field.
func (u *WalletSweepUpsertBulk) ClearReplacementOfID() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearReplacementOfID()
	})
}

// SetFeeRaw sets the "fee_raw" field.
func (u *WalletSweepUpsertBulk) SetFeeRaw(v string) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFeeRaw(v)
	})
}

// UpdateFeeRaw sets the "fee_raw" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateFeeRaw() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFeeRaw()
	})
}

// SetEnergyUsed sets the "energy_used" field.
func (u *WalletSweepUpsertBulk) SetEnergyUsed(v int64) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetEnergyUsed(v)
	})
}

// AddEnergyUsed adds v to the "energy_used" field.
func (u *WalletSweepUpsertBulk) AddEnergyUsed(v int64) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddEnergyUsed(v)
	})
}

// UpdateEnergyUsed sets the "energy_used" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateEnergyUsed() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateEnergyUsed()
	})
}

// SetBandwidthUsed sets the "bandwidth_used" field.
func (u *WalletSweepUpsertBulk) SetBandwidthUsed(v int64) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetBandwidthUsed(v)
	})
}

// AddBandwidthUsed adds v to the "bandwidth_used" field.
func (u *WalletSweepUpsertBulk) AddBandwidthUsed(v int64) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddBandwidthUsed(v)
	})
}

// UpdateBandwidthUsed sets the "bandwidth_used" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateBandwidthUsed() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateBandwidthUsed()
	})
}

// SetFinalizedBlockHeight sets the "finalized_block_height" field.
func (u *WalletSweepUpsertBulk) SetFinalizedBlockHeight(v int64) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFinalizedBlockHeight(v)
	})
}

// AddFinalizedBlockHeight adds v to the "finalized_block_height" field.
func (u *WalletSweepUpsertBulk) AddFinalizedBlockHeight(v int64) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddFinalizedBlockHeight(v)
	})
}

// UpdateFinalizedBlockHeight sets the "finalized_block_height" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateFinalizedBlockHeight() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFinalizedBlockHeight()
	})
}

// ClearFinalizedBlockHeight clears the value of the "finalized_block_height" field.
func (u *WalletSweepUpsertBulk) ClearFinalizedBlockHeight() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearFinalizedBlockHeight()
	})
}

// SetFinalizedBlockHash sets the "finalized_block_hash" field.
func (u *WalletSweepUpsertBulk) SetFinalizedBlockHash(v string) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFinalizedBlockHash(v)
	})
}

// UpdateFinalizedBlockHash sets the "finalized_block_hash" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateFinalizedBlockHash() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFinalizedBlockHash()
	})
}

// ClearFinalizedBlockHash clears the value of the "finalized_block_hash" field.
func (u *WalletSweepUpsertBulk) ClearFinalizedBlockHash() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearFinalizedBlockHash()
	})
}

// SetStatus sets the "status" field.
func (u *WalletSweepUpsertBulk) SetStatus(v string) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateStatus() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateStatus()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *WalletSweepUpsertBulk) SetRetryCount(v int) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *WalletSweepUpsertBulk) AddRetryCount(v int) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateRetryCount() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateRetryCount()
	})
}

// SetFailureCode sets the "failure_code" field.
func (u *WalletSweepUpsertBulk) SetFailureCode(v string) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFailureCode(v)
	})
}

// UpdateFailureCode sets the "failure_code" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateFailureCode() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFailureCode()
	})
}

// ClearFailureCode clears the value of the "failure_code" field.
func (u *WalletSweepUpsertBulk) ClearFailureCode() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearFailureCode()
	})
}

// SetFailureReason sets the "failure_reason" field.
func (u *WalletSweepUpsertBulk) SetFailureReason(v string) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFailureReason(v)
	})
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateFailureReason() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFailureReason()
	})
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (u *WalletSweepUpsertBulk) ClearFailureReason() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearFailureReason()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *WalletSweepUpsertBulk) SetNextAttemptAt(v time.Time) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateNextAttemptAt() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *WalletSweepUpsertBulk) ClearNextAttemptAt() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearNextAttemptAt()
	})
}

// SetFinalizedAt sets the "finalized_at" field.
func (u *WalletSweepUpsertBulk) SetFinalizedAt(v time.Time) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetFinalizedAt(v)
	})
}

// UpdateFinalizedAt sets the "finalized_at" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateFinalizedAt() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateFinalizedAt()
	})
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (u *WalletSweepUpsertBulk) ClearFinalizedAt() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.ClearFinalizedAt()
	})
}

// SetVersion sets the "version" field.
func (u *WalletSweepUpsertBulk) SetVersion(v int) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *WalletSweepUpsertBulk) AddVersion(v int) *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *WalletSweepUpsertBulk) UpdateVersion() *WalletSweepUpsertBulk {
	return u.Update(func(s *WalletSweepUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *WalletSweepUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WalletSweepCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WalletSweepCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WalletSweepUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
