// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/walletsweep"
)

// WalletSweepUpdate is the builder for updating WalletSweep entities.
type WalletSweepUpdate struct {
	config
	hooks    []Hook
	mutation *WalletSweepMutation
}

// Where appends a list predicates to the WalletSweepUpdate builder.
func (_u *WalletSweepUpdate) Where(ps ...predicate.WalletSweep) *WalletSweepUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WalletSweepUpdate) SetUpdatedAt(v time.Time) *WalletSweepUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSignerRequestDigest sets the "signer_request_digest" field.
func (_u *WalletSweepUpdate) SetSignerRequestDigest(v string) *WalletSweepUpdate {
	_u.mutation.SetSignerRequestDigest(v)
	return _u
}

// SetNillableSignerRequestDigest sets the "signer_request_digest" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableSignerRequestDigest(v *string) *WalletSweepUpdate {
	if v != nil {
		_u.SetSignerRequestDigest(*v)
	}
	return _u
}

// ClearSignerRequestDigest clears the value of the "signer_request_digest" field.
func (_u *WalletSweepUpdate) ClearSignerRequestDigest() *WalletSweepUpdate {
	_u.mutation.ClearSignerRequestDigest()
	return _u
}

// SetSignerAuditID sets the "signer_audit_id" field.
func (_u *WalletSweepUpdate) SetSignerAuditID(v string) *WalletSweepUpdate {
	_u.mutation.SetSignerAuditID(v)
	return _u
}

// SetNillableSignerAuditID sets the "signer_audit_id" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableSignerAuditID(v *string) *WalletSweepUpdate {
	if v != nil {
		_u.SetSignerAuditID(*v)
	}
	return _u
}

// ClearSignerAuditID clears the value of the "signer_audit_id" field.
func (_u *WalletSweepUpdate) ClearSignerAuditID() *WalletSweepUpdate {
	_u.mutation.ClearSignerAuditID()
	return _u
}

// SetTransactionID sets the "transaction_id" field.
func (_u *WalletSweepUpdate) SetTransactionID(v string) *WalletSweepUpdate {
	_u.mutation.SetTransactionID(v)
	return _u
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableTransactionID(v *string) *WalletSweepUpdate {
	if v != nil {
		_u.SetTransactionID(*v)
	}
	return _u
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (_u *WalletSweepUpdate) ClearTransactionID() *WalletSweepUpdate {
	_u.mutation.ClearTransactionID()
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *WalletSweepUpdate) SetNonce(v int64) *WalletSweepUpdate {
	_u.mutation.ResetNonce()
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableNonce(v *int64) *WalletSweepUpdate {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// AddNonce adds value to the "nonce" field.
func (_u *WalletSweepUpdate) AddNonce(v int64) *WalletSweepUpdate {
	_u.mutation.AddNonce(v)
	return _u
}

// ClearNonce clears the value of the "nonce" field.
func (_u *WalletSweepUpdate) ClearNonce() *WalletSweepUpdate {
	_u.mutation.ClearNonce()
	return _u
}

// SetReplacementOfID sets the "replacement_of_id" field.
func (_u *WalletSweepUpdate) SetReplacementOfID(v int64) *WalletSweepUpdate {
	_u.mutation.ResetReplacementOfID()
	_u.mutation.SetReplacementOfID(v)
	return _u
}

// SetNillableReplacementOfID sets the "replacement_of_id" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableReplacementOfID(v *int64) *WalletSweepUpdate {
	if v != nil {
		_u.SetReplacementOfID(*v)
	}
	return _u
}

// AddReplacementOfID adds value to the "replacement_of_id" field.
func (_u *WalletSweepUpdate) AddReplacementOfID(v int64) *WalletSweepUpdate {
	_u.mutation.AddReplacementOfID(v)
	return _u
}

// ClearReplacementOfID clears the value of the "replacement_of_id" field.
func (_u *WalletSweepUpdate) ClearReplacementOfID() *WalletSweepUpdate {
	_u.mutation.ClearReplacementOfID()
	return _u
}

// SetFeeRaw sets the "fee_raw" field.
func (_u *WalletSweepUpdate) SetFeeRaw(v string) *WalletSweepUpdate {
	_u.mutation.SetFeeRaw(v)
	return _u
}

// SetNillableFeeRaw sets the "fee_raw" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableFeeRaw(v *string) *WalletSweepUpdate {
	if v != nil {
		_u.SetFeeRaw(*v)
	}
	return _u
}

// SetEnergyUsed sets the "energy_used" field.
func (_u *WalletSweepUpdate) SetEnergyUsed(v int64) *WalletSweepUpdate {
	_u.mutation.ResetEnergyUsed()
	_u.mutation.SetEnergyUsed(v)
	return _u
}

// SetNillableEnergyUsed sets the "energy_used" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableEnergyUsed(v *int64) *WalletSweepUpdate {
	if v != nil {
		_u.SetEnergyUsed(*v)
	}
	return _u
}

// AddEnergyUsed adds value to the "energy_used" field.
func (_u *WalletSweepUpdate) AddEnergyUsed(v int64) *WalletSweepUpdate {
	_u.mutation.AddEnergyUsed(v)
	return _u
}

// SetBandwidthUsed sets the "bandwidth_used" field.
func (_u *WalletSweepUpdate) SetBandwidthUsed(v int64) *WalletSweepUpdate {
	_u.mutation.ResetBandwidthUsed()
	_u.mutation.SetBandwidthUsed(v)
	return _u
}

// SetNillableBandwidthUsed sets the "bandwidth_used" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableBandwidthUsed(v *int64) *WalletSweepUpdate {
	if v != nil {
		_u.SetBandwidthUsed(*v)
	}
	return _u
}

// AddBandwidthUsed adds value to the "bandwidth_used" field.
func (_u *WalletSweepUpdate) AddBandwidthUsed(v int64) *WalletSweepUpdate {
	_u.mutation.AddBandwidthUsed(v)
	return _u
}

// SetFinalizedBlockHeight sets the "finalized_block_height" field.
func (_u *WalletSweepUpdate) SetFinalizedBlockHeight(v int64) *WalletSweepUpdate {
	_u.mutation.ResetFinalizedBlockHeight()
	_u.mutation.SetFinalizedBlockHeight(v)
	return _u
}

// SetNillableFinalizedBlockHeight sets the "finalized_block_height" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableFinalizedBlockHeight(v *int64) *WalletSweepUpdate {
	if v != nil {
		_u.SetFinalizedBlockHeight(*v)
	}
	return _u
}

// AddFinalizedBlockHeight adds value to the "finalized_block_height" field.
func (_u *WalletSweepUpdate) AddFinalizedBlockHeight(v int64) *WalletSweepUpdate {
	_u.mutation.AddFinalizedBlockHeight(v)
	return _u
}

// ClearFinalizedBlockHeight clears the value of the "finalized_block_height" field.
func (_u *WalletSweepUpdate) ClearFinalizedBlockHeight() *WalletSweepUpdate {
	_u.mutation.ClearFinalizedBlockHeight()
	return _u
}

// SetFinalizedBlockHash sets the "finalized_block_hash" field.
func (_u *WalletSweepUpdate) SetFinalizedBlockHash(v string) *WalletSweepUpdate {
	_u.mutation.SetFinalizedBlockHash(v)
	return _u
}

// SetNillableFinalizedBlockHash sets the "finalized_block_hash" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableFinalizedBlockHash(v *string) *WalletSweepUpdate {
	if v != nil {
		_u.SetFinalizedBlockHash(*v)
	}
	return _u
}

// ClearFinalizedBlockHash clears the value of the "finalized_block_hash" field.
func (_u *WalletSweepUpdate) ClearFinalizedBlockHash() *WalletSweepUpdate {
	_u.mutation.ClearFinalizedBlockHash()
	return _u
}

// SetStatus sets the "status" field.
func (_u *WalletSweepUpdate) SetStatus(v string) *WalletSweepUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableStatus(v *string) *WalletSweepUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *WalletSweepUpdate) SetRetryCount(v int) *WalletSweepUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableRetryCount(v *int) *WalletSweepUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *WalletSweepUpdate) AddRetryCount(v int) *WalletSweepUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *WalletSweepUpdate) SetFailureCode(v string) *WalletSweepUpdate {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableFailureCode(v *string) *WalletSweepUpdate {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// ClearFailureCode clears the value of the "failure_code" field.
func (_u *WalletSweepUpdate) ClearFailureCode() *WalletSweepUpdate {
	_u.mutation.ClearFailureCode()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *WalletSweepUpdate) SetFailureReason(v string) *WalletSweepUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableFailureReason(v *string) *WalletSweepUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *WalletSweepUpdate) ClearFailureReason() *WalletSweepUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *WalletSweepUpdate) SetNextAttemptAt(v time.Time) *WalletSweepUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableNextAttemptAt(v *time.Time) *WalletSweepUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *WalletSweepUpdate) ClearNextAttemptAt() *WalletSweepUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetFinalizedAt sets the "finalized_at" field.
func (_u *WalletSweepUpdate) SetFinalizedAt(v time.Time) *WalletSweepUpdate {
	_u.mutation.SetFinalizedAt(v)
	return _u
}

// SetNillableFinalizedAt sets the "finalized_at" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableFinalizedAt(v *time.Time) *WalletSweepUpdate {
	if v != nil {
		_u.SetFinalizedAt(*v)
	}
	return _u
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (_u *WalletSweepUpdate) ClearFinalizedAt() *WalletSweepUpdate {
	_u.mutation.ClearFinalizedAt()
	return _u
}

// SetVersion sets the "version" field.
func (_u *WalletSweepUpdate) SetVersion(v int) *WalletSweepUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *WalletSweepUpdate) SetNillableVersion(v *int) *WalletSweepUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *WalletSweepUpdate) AddVersion(v int) *WalletSweepUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the WalletSweepMutation object of the builder.
func (_u *WalletSweepUpdate) Mutation() *WalletSweepMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WalletSweepUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletSweepUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WalletSweepUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletSweepUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WalletSweepUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := walletsweep.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WalletSweepUpdate) check() error {
	if v, ok := _u.mutation.SignerRequestDigest(); ok {
		if err := walletsweep.SignerRequestDigestValidator(v); err != nil {
			return &ValidationError{Name: "signer_request_digest", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.signer_request_digest": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SignerAuditID(); ok {
		if err := walletsweep.SignerAuditIDValidator(v); err != nil {
			return &ValidationError{Name: "signer_audit_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.signer_audit_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TransactionID(); ok {
		if err := walletsweep.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.transaction_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nonce(); ok {
		if err := walletsweep.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.nonce": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReplacementOfID(); ok {
		if err := walletsweep.ReplacementOfIDValidator(v); err != nil {
			return &ValidationError{Name: "replacement_of_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.replacement_of_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EnergyUsed(); ok {
		if err := walletsweep.EnergyUsedValidator(v); err != nil {
			return &ValidationError{Name: "energy_used", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.energy_used": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BandwidthUsed(); ok {
		if err := walletsweep.BandwidthUsedValidator(v); err != nil {
			return &ValidationError{Name: "bandwidth_used", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.bandwidth_used": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FinalizedBlockHeight(); ok {
		if err := walletsweep.FinalizedBlockHeightValidator(v); err != nil {
			return &ValidationError{Name: "finalized_block_height", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.finalized_block_height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FinalizedBlockHash(); ok {
		if err := walletsweep.FinalizedBlockHashValidator(v); err != nil {
			return &ValidationError{Name: "finalized_block_hash", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.finalized_block_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := walletsweep.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetryCount(); ok {
		if err := walletsweep.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.retry_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureCode(); ok {
		if err := walletsweep.FailureCodeValidator(v); err != nil {
			return &ValidationError{Name: "failure_code", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.failure_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := walletsweep.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.version": %w`, err)}
		}
	}
	if _u.mutation.IntentCleared() && len(_u.mutation.IntentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WalletSweep.intent"`)
	}
	return nil
}

func (_u *WalletSweepUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(walletsweep.Table, walletsweep.Columns, sqlgraph.NewFieldSpec(walletsweep.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(walletsweep.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SignerRequestDigest(); ok {
		_spec.SetField(walletsweep.FieldSignerRequestDigest, field.TypeString, value)
	}
	if _u.mutation.SignerRequestDigestCleared() {
		_spec.ClearField(walletsweep.FieldSignerRequestDigest, field.TypeString)
	}
	if value, ok := _u.mutation.SignerAuditID(); ok {
		_spec.SetField(walletsweep.FieldSignerAuditID, field.TypeString, value)
	}
	if _u.mutation.SignerAuditIDCleared() {
		_spec.ClearField(walletsweep.FieldSignerAuditID, field.TypeString)
	}
	if value, ok := _u.mutation.TransactionID(); ok {
		_spec.SetField(walletsweep.FieldTransactionID, field.TypeString, value)
	}
	if _u.mutation.TransactionIDCleared() {
		_spec.ClearField(walletsweep.FieldTransactionID, field.TypeString)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(walletsweep.FieldNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNonce(); ok {
		_spec.AddField(walletsweep.FieldNonce, field.TypeInt64, value)
	}
	if _u.mutation.NonceCleared() {
		_spec.ClearField(walletsweep.FieldNonce, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReplacementOfID(); ok {
		_spec.SetField(walletsweep.FieldReplacementOfID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReplacementOfID(); ok {
		_spec.AddField(walletsweep.FieldReplacementOfID, field.TypeInt64, value)
	}
	if _u.mutation.ReplacementOfIDCleared() {
		_spec.ClearField(walletsweep.FieldReplacementOfID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FeeRaw(); ok {
		_spec.SetField(walletsweep.FieldFeeRaw, field.TypeString, value)
	}
	if value, ok := _u.mutation.EnergyUsed(); ok {
		_spec.SetField(walletsweep.FieldEnergyUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEnergyUsed(); ok {
		_spec.AddField(walletsweep.FieldEnergyUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BandwidthUsed(); ok {
		_spec.SetField(walletsweep.FieldBandwidthUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBandwidthUsed(); ok {
		_spec.AddField(walletsweep.FieldBandwidthUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FinalizedBlockHeight(); ok {
		_spec.SetField(walletsweep.FieldFinalizedBlockHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFinalizedBlockHeight(); ok {
		_spec.AddField(walletsweep.FieldFinalizedBlockHeight, field.TypeInt64, value)
	}
	if _u.mutation.FinalizedBlockHeightCleared() {
		_spec.ClearField(walletsweep.FieldFinalizedBlockHeight, field.TypeInt64)
	}
	if value, ok := _u.mutation.FinalizedBlockHash(); ok {
		_spec.SetField(walletsweep.FieldFinalizedBlockHash, field.TypeString, value)
	}
	if _u.mutation.FinalizedBlockHashCleared() {
		_spec.ClearField(walletsweep.FieldFinalizedBlockHash, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(walletsweep.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(walletsweep.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(walletsweep.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(walletsweep.FieldFailureCode, field.TypeString, value)
	}
	if _u.mutation.FailureCodeCleared() {
		_spec.ClearField(walletsweep.FieldFailureCode, field.TypeString)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(walletsweep.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(walletsweep.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(walletsweep.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(walletsweep.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinalizedAt(); ok {
		_spec.SetField(walletsweep.FieldFinalizedAt, field.TypeTime, value)
	}
	if _u.mutation.FinalizedAtCleared() {
		_spec.ClearField(walletsweep.FieldFinalizedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(walletsweep.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(walletsweep.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{walletsweep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WalletSweepUpdateOne is the builder for updating a single WalletSweep entity.
type WalletSweepUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WalletSweepMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WalletSweepUpdateOne) SetUpdatedAt(v time.Time) *WalletSweepUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSignerRequestDigest sets the "signer_request_digest" field.
func (_u *WalletSweepUpdateOne) SetSignerRequestDigest(v string) *WalletSweepUpdateOne {
	_u.mutation.SetSignerRequestDigest(v)
	return _u
}

// SetNillableSignerRequestDigest sets the "signer_request_digest" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableSignerRequestDigest(v *string) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetSignerRequestDigest(*v)
	}
	return _u
}

// ClearSignerRequestDigest clears the value of the "signer_request_digest" field.
func (_u *WalletSweepUpdateOne) ClearSignerRequestDigest() *WalletSweepUpdateOne {
	_u.mutation.ClearSignerRequestDigest()
	return _u
}

// SetSignerAuditID sets the "signer_audit_id" field.
func (_u *WalletSweepUpdateOne) SetSignerAuditID(v string) *WalletSweepUpdateOne {
	_u.mutation.SetSignerAuditID(v)
	return _u
}

// SetNillableSignerAuditID sets the "signer_audit_id" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableSignerAuditID(v *string) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetSignerAuditID(*v)
	}
	return _u
}

// ClearSignerAuditID clears the value of the "signer_audit_id" field.
func (_u *WalletSweepUpdateOne) ClearSignerAuditID() *WalletSweepUpdateOne {
	_u.mutation.ClearSignerAuditID()
	return _u
}

// SetTransactionID sets the "transaction_id" field.
func (_u *WalletSweepUpdateOne) SetTransactionID(v string) *WalletSweepUpdateOne {
	_u.mutation.SetTransactionID(v)
	return _u
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableTransactionID(v *string) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetTransactionID(*v)
	}
	return _u
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (_u *WalletSweepUpdateOne) ClearTransactionID() *WalletSweepUpdateOne {
	_u.mutation.ClearTransactionID()
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *WalletSweepUpdateOne) SetNonce(v int64) *WalletSweepUpdateOne {
	_u.mutation.ResetNonce()
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableNonce(v *int64) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// AddNonce adds value to the "nonce" field.
func (_u *WalletSweepUpdateOne) AddNonce(v int64) *WalletSweepUpdateOne {
	_u.mutation.AddNonce(v)
	return _u
}

// ClearNonce clears the value of the "nonce" field.
func (_u *WalletSweepUpdateOne) ClearNonce() *WalletSweepUpdateOne {
	_u.mutation.ClearNonce()
	return _u
}

// SetReplacementOfID sets the "replacement_of_id" field.
func (_u *WalletSweepUpdateOne) SetReplacementOfID(v int64) *WalletSweepUpdateOne {
	_u.mutation.ResetReplacementOfID()
	_u.mutation.SetReplacementOfID(v)
	return _u
}

// SetNillableReplacementOfID sets the "replacement_of_id" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableReplacementOfID(v *int64) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetReplacementOfID(*v)
	}
	return _u
}

// AddReplacementOfID adds value to the "replacement_of_id" field.
func (_u *WalletSweepUpdateOne) AddReplacementOfID(v int64) *WalletSweepUpdateOne {
	_u.mutation.AddReplacementOfID(v)
	return _u
}

// ClearReplacementOfID clears the value of the "replacement_of_id" field.
func (_u *WalletSweepUpdateOne) ClearReplacementOfID() *WalletSweepUpdateOne {
	_u.mutation.ClearReplacementOfID()
	return _u
}

// SetFeeRaw sets the "fee_raw" field.
func (_u *WalletSweepUpdateOne) SetFeeRaw(v string) *WalletSweepUpdateOne {
	_u.mutation.SetFeeRaw(v)
	return _u
}

// SetNillableFeeRaw sets the "fee_raw" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableFeeRaw(v *string) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetFeeRaw(*v)
	}
	return _u
}

// SetEnergyUsed sets the "energy_used" field.
func (_u *WalletSweepUpdateOne) SetEnergyUsed(v int64) *WalletSweepUpdateOne {
	_u.mutation.ResetEnergyUsed()
	_u.mutation.SetEnergyUsed(v)
	return _u
}

// SetNillableEnergyUsed sets the "energy_used" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableEnergyUsed(v *int64) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetEnergyUsed(*v)
	}
	return _u
}

// AddEnergyUsed adds value to the "energy_used" field.
func (_u *WalletSweepUpdateOne) AddEnergyUsed(v int64) *WalletSweepUpdateOne {
	_u.mutation.AddEnergyUsed(v)
	return _u
}

// SetBandwidthUsed sets the "bandwidth_used" field.
func (_u *WalletSweepUpdateOne) SetBandwidthUsed(v int64) *WalletSweepUpdateOne {
	_u.mutation.ResetBandwidthUsed()
	_u.mutation.SetBandwidthUsed(v)
	return _u
}

// SetNillableBandwidthUsed sets the "bandwidth_used" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableBandwidthUsed(v *int64) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetBandwidthUsed(*v)
	}
	return _u
}

// AddBandwidthUsed adds value to the "bandwidth_used" field.
func (_u *WalletSweepUpdateOne) AddBandwidthUsed(v int64) *WalletSweepUpdateOne {
	_u.mutation.AddBandwidthUsed(v)
	return _u
}

// SetFinalizedBlockHeight sets the "finalized_block_height" field.
func (_u *WalletSweepUpdateOne) SetFinalizedBlockHeight(v int64) *WalletSweepUpdateOne {
	_u.mutation.ResetFinalizedBlockHeight()
	_u.mutation.SetFinalizedBlockHeight(v)
	return _u
}

// SetNillableFinalizedBlockHeight sets the "finalized_block_height" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableFinalizedBlockHeight(v *int64) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetFinalizedBlockHeight(*v)
	}
	return _u
}

// AddFinalizedBlockHeight adds value to the "finalized_block_height" field.
func (_u *WalletSweepUpdateOne) AddFinalizedBlockHeight(v int64) *WalletSweepUpdateOne {
	_u.mutation.AddFinalizedBlockHeight(v)
	return _u
}

// ClearFinalizedBlockHeight clears the value of the "finalized_block_height" field.
func (_u *WalletSweepUpdateOne) ClearFinalizedBlockHeight() *WalletSweepUpdateOne {
	_u.mutation.ClearFinalizedBlockHeight()
	return _u
}

// SetFinalizedBlockHash sets the "finalized_block_hash" field.
func (_u *WalletSweepUpdateOne) SetFinalizedBlockHash(v string) *WalletSweepUpdateOne {
	_u.mutation.SetFinalizedBlockHash(v)
	return _u
}

// SetNillableFinalizedBlockHash sets the "finalized_block_hash" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableFinalizedBlockHash(v *string) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetFinalizedBlockHash(*v)
	}
	return _u
}

// ClearFinalizedBlockHash clears the value of the "finalized_block_hash" field.
func (_u *WalletSweepUpdateOne) ClearFinalizedBlockHash() *WalletSweepUpdateOne {
	_u.mutation.ClearFinalizedBlockHash()
	return _u
}

// SetStatus sets the "status" field.
func (_u *WalletSweepUpdateOne) SetStatus(v string) *WalletSweepUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableStatus(v *string) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *WalletSweepUpdateOne) SetRetryCount(v int) *WalletSweepUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableRetryCount(v *int) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *WalletSweepUpdateOne) AddRetryCount(v int) *WalletSweepUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *WalletSweepUpdateOne) SetFailureCode(v string) *WalletSweepUpdateOne {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableFailureCode(v *string) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// ClearFailureCode clears the value of the "failure_code" field.
func (_u *WalletSweepUpdateOne) ClearFailureCode() *WalletSweepUpdateOne {
	_u.mutation.ClearFailureCode()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *WalletSweepUpdateOne) SetFailureReason(v string) *WalletSweepUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableFailureReason(v *string) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *WalletSweepUpdateOne) ClearFailureReason() *WalletSweepUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *WalletSweepUpdateOne) SetNextAttemptAt(v time.Time) *WalletSweepUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableNextAttemptAt(v *time.Time) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *WalletSweepUpdateOne) ClearNextAttemptAt() *WalletSweepUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetFinalizedAt sets the "finalized_at" field.
func (_u *WalletSweepUpdateOne) SetFinalizedAt(v time.Time) *WalletSweepUpdateOne {
	_u.mutation.SetFinalizedAt(v)
	return _u
}

// SetNillableFinalizedAt sets the "finalized_at" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableFinalizedAt(v *time.Time) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetFinalizedAt(*v)
	}
	return _u
}

// ClearFinalizedAt clears the value of the "finalized_at" field.
func (_u *WalletSweepUpdateOne) ClearFinalizedAt() *WalletSweepUpdateOne {
	_u.mutation.ClearFinalizedAt()
	return _u
}

// SetVersion sets the "version" field.
func (_u *WalletSweepUpdateOne) SetVersion(v int) *WalletSweepUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *WalletSweepUpdateOne) SetNillableVersion(v *int) *WalletSweepUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *WalletSweepUpdateOne) AddVersion(v int) *WalletSweepUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the WalletSweepMutation object of the builder.
func (_u *WalletSweepUpdateOne) Mutation() *WalletSweepMutation {
	return _u.mutation
}

// Where appends a list predicates to the WalletSweepUpdate builder.
func (_u *WalletSweepUpdateOne) Where(ps ...predicate.WalletSweep) *WalletSweepUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WalletSweepUpdateOne) Select(field string, fields ...string) *WalletSweepUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WalletSweep entity.
func (_u *WalletSweepUpdateOne) Save(ctx context.Context) (*WalletSweep, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletSweepUpdateOne) SaveX(ctx context.Context) *WalletSweep {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WalletSweepUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletSweepUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WalletSweepUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := walletsweep.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WalletSweepUpdateOne) check() error {
	if v, ok := _u.mutation.SignerRequestDigest(); ok {
		if err := walletsweep.SignerRequestDigestValidator(v); err != nil {
			return &ValidationError{Name: "signer_request_digest", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.signer_request_digest": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SignerAuditID(); ok {
		if err := walletsweep.SignerAuditIDValidator(v); err != nil {
			return &ValidationError{Name: "signer_audit_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.signer_audit_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TransactionID(); ok {
		if err := walletsweep.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.transaction_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nonce(); ok {
		if err := walletsweep.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.nonce": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReplacementOfID(); ok {
		if err := walletsweep.ReplacementOfIDValidator(v); err != nil {
			return &ValidationError{Name: "replacement_of_id", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.replacement_of_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EnergyUsed(); ok {
		if err := walletsweep.EnergyUsedValidator(v); err != nil {
			return &ValidationError{Name: "energy_used", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.energy_used": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BandwidthUsed(); ok {
		if err := walletsweep.BandwidthUsedValidator(v); err != nil {
			return &ValidationError{Name: "bandwidth_used", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.bandwidth_used": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FinalizedBlockHeight(); ok {
		if err := walletsweep.FinalizedBlockHeightValidator(v); err != nil {
			return &ValidationError{Name: "finalized_block_height", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.finalized_block_height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FinalizedBlockHash(); ok {
		if err := walletsweep.FinalizedBlockHashValidator(v); err != nil {
			return &ValidationError{Name: "finalized_block_hash", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.finalized_block_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := walletsweep.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetryCount(); ok {
		if err := walletsweep.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.retry_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureCode(); ok {
		if err := walletsweep.FailureCodeValidator(v); err != nil {
			return &ValidationError{Name: "failure_code", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.failure_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := walletsweep.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "WalletSweep.version": %w`, err)}
		}
	}
	if _u.mutation.IntentCleared() && len(_u.mutation.IntentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WalletSweep.intent"`)
	}
	return nil
}

func (_u *WalletSweepUpdateOne) sqlSave(ctx context.Context) (_node *WalletSweep, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(walletsweep.Table, walletsweep.Columns, sqlgraph.NewFieldSpec(walletsweep.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WalletSweep.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, walletsweep.FieldID)
		for _, f := range fields {
			if !walletsweep.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != walletsweep.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(walletsweep.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SignerRequestDigest(); ok {
		_spec.SetField(walletsweep.FieldSignerRequestDigest, field.TypeString, value)
	}
	if _u.mutation.SignerRequestDigestCleared() {
		_spec.ClearField(walletsweep.FieldSignerRequestDigest, field.TypeString)
	}
	if value, ok := _u.mutation.SignerAuditID(); ok {
		_spec.SetField(walletsweep.FieldSignerAuditID, field.TypeString, value)
	}
	if _u.mutation.SignerAuditIDCleared() {
		_spec.ClearField(walletsweep.FieldSignerAuditID, field.TypeString)
	}
	if value, ok := _u.mutation.TransactionID(); ok {
		_spec.SetField(walletsweep.FieldTransactionID, field.TypeString, value)
	}
	if _u.mutation.TransactionIDCleared() {
		_spec.ClearField(walletsweep.FieldTransactionID, field.TypeString)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(walletsweep.FieldNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNonce(); ok {
		_spec.AddField(walletsweep.FieldNonce, field.TypeInt64, value)
	}
	if _u.mutation.NonceCleared() {
		_spec.ClearField(walletsweep.FieldNonce, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReplacementOfID(); ok {
		_spec.SetField(walletsweep.FieldReplacementOfID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReplacementOfID(); ok {
		_spec.AddField(walletsweep.FieldReplacementOfID, field.TypeInt64, value)
	}
	if _u.mutation.ReplacementOfIDCleared() {
		_spec.ClearField(walletsweep.FieldReplacementOfID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FeeRaw(); ok {
		_spec.SetField(walletsweep.FieldFeeRaw, field.TypeString, value)
	}
	if value, ok := _u.mutation.EnergyUsed(); ok {
		_spec.SetField(walletsweep.FieldEnergyUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEnergyUsed(); ok {
		_spec.AddField(walletsweep.FieldEnergyUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BandwidthUsed(); ok {
		_spec.SetField(walletsweep.FieldBandwidthUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBandwidthUsed(); ok {
		_spec.AddField(walletsweep.FieldBandwidthUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FinalizedBlockHeight(); ok {
		_spec.SetField(walletsweep.FieldFinalizedBlockHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFinalizedBlockHeight(); ok {
		_spec.AddField(walletsweep.FieldFinalizedBlockHeight, field.TypeInt64, value)
	}
	if _u.mutation.FinalizedBlockHeightCleared() {
		_spec.ClearField(walletsweep.FieldFinalizedBlockHeight, field.TypeInt64)
	}
	if value, ok := _u.mutation.FinalizedBlockHash(); ok {
		_spec.SetField(walletsweep.FieldFinalizedBlockHash, field.TypeString, value)
	}
	if _u.mutation.FinalizedBlockHashCleared() {
		_spec.ClearField(walletsweep.FieldFinalizedBlockHash, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(walletsweep.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(walletsweep.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(walletsweep.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(walletsweep.FieldFailureCode, field.TypeString, value)
	}
	if _u.mutation.FailureCodeCleared() {
		_spec.ClearField(walletsweep.FieldFailureCode, field.TypeString)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(walletsweep.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(walletsweep.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(walletsweep.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(walletsweep.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinalizedAt(); ok {
		_spec.SetField(walletsweep.FieldFinalizedAt, field.TypeTime, value)
	}
	if _u.mutation.FinalizedAtCleared() {
		_spec.ClearField(walletsweep.FieldFinalizedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(walletsweep.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(walletsweep.FieldVersion, field.TypeInt, value)
	}
	_node = &WalletSweep{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{walletsweep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
