// Code generated by ent, DO NOT EDIT.

package ethereumnoncestate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldUpdatedAt, v))
}

// ChainID applies equality check predicate on the "chain_id" field. It's identical to ChainIDEQ.
func ChainID(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldChainID, v))
}

// SenderAddress applies equality check predicate on the "sender_address" field. It's identical to SenderAddressEQ.
func SenderAddress(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldSenderAddress, v))
}

// NextNonce applies equality check predicate on the "next_nonce" field. It's identical to NextNonceEQ.
func NextNonce(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldNextNonce, v))
}

// ObservedPendingNonce applies equality check predicate on the "observed_pending_nonce" field. It's identical to ObservedPendingNonceEQ.
func ObservedPendingNonce(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldObservedPendingNonce, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldStatus, v))
}

// LeaseOwner applies equality check predicate on the "lease_owner" field. It's identical to LeaseOwnerEQ.
func LeaseOwner(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseUntil applies equality check predicate on the "lease_until" field. It's identical to LeaseUntilEQ.
func LeaseUntil(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldLeaseUntil, v))
}

// LastReconciledAt applies equality check predicate on the "last_reconciled_at" field. It's identical to LastReconciledAtEQ.
func LastReconciledAt(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldLastReconciledAt, v))
}

// LastErrorCode applies equality check predicate on the "last_error_code" field. It's identical to LastErrorCodeEQ.
func LastErrorCode(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorMessage applies equality check predicate on the "last_error_message" field. It's identical to LastErrorMessageEQ.
func LastErrorMessage(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldLastErrorMessage, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldUpdatedAt, v))
}

// ChainIDEQ applies the EQ predicate on the "chain_id" field.
func ChainIDEQ(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldChainID, v))
}

// ChainIDNEQ applies the NEQ predicate on the "chain_id" field.
func ChainIDNEQ(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldChainID, v))
}

// ChainIDIn applies the In predicate on the "chain_id" field.
func ChainIDIn(vs ...int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldChainID, vs...))
}

// ChainIDNotIn applies the NotIn predicate on the "chain_id" field.
func ChainIDNotIn(vs ...int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldChainID, vs...))
}

// ChainIDGT applies the GT predicate on the "chain_id" field.
func ChainIDGT(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldChainID, v))
}

// ChainIDGTE applies the GTE predicate on the "chain_id" field.
func ChainIDGTE(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldChainID, v))
}

// ChainIDLT applies the LT predicate on the "chain_id" field.
func ChainIDLT(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldChainID, v))
}

// ChainIDLTE applies the LTE predicate on the "chain_id" field.
func ChainIDLTE(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldChainID, v))
}

// SenderAddressEQ applies the EQ predicate on the "sender_address" field.
func SenderAddressEQ(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldSenderAddress, v))
}

// SenderAddressNEQ applies the NEQ predicate on the "sender_address" field.
func SenderAddressNEQ(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldSenderAddress, v))
}

// SenderAddressIn applies the In predicate on the "sender_address" field.
func SenderAddressIn(vs ...string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldSenderAddress, vs...))
}

// SenderAddressNotIn applies the NotIn predicate on the "sender_address" field.
func SenderAddressNotIn(vs ...string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldSenderAddress, vs...))
}

// SenderAddressGT applies the GT predicate on the "sender_address" field.
func SenderAddressGT(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldSenderAddress, v))
}

// SenderAddressGTE applies the GTE predicate on the "sender_address" field.
func SenderAddressGTE(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldSenderAddress, v))
}

// SenderAddressLT applies the LT predicate on the "sender_address" field.
func SenderAddressLT(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldSenderAddress, v))
}

// SenderAddressLTE applies the LTE predicate on the "sender_address" field.
func SenderAddressLTE(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldSenderAddress, v))
}

// SenderAddressContains applies the Contains predicate on the "sender_address" field.
func SenderAddressContains(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldContains(FieldSenderAddress, v))
}

// SenderAddressHasPrefix applies the HasPrefix predicate on the "sender_address" field.
func SenderAddressHasPrefix(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldHasPrefix(FieldSenderAddress, v))
}

// SenderAddressHasSuffix applies the HasSuffix predicate on the "sender_address" field.
func SenderAddressHasSuffix(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldHasSuffix(FieldSenderAddress, v))
}

// SenderAddressEqualFold applies the EqualFold predicate on the "sender_address" field.
func SenderAddressEqualFold(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEqualFold(FieldSenderAddress, v))
}

// SenderAddressContainsFold applies the ContainsFold predicate on the "sender_address" field.
func SenderAddressContainsFold(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldContainsFold(FieldSenderAddress, v))
}

// NextNonceEQ applies the EQ predicate on the "next_nonce" field.
func NextNonceEQ(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldNextNonce, v))
}

// NextNonceNEQ applies the NEQ predicate on the "next_nonce" field.
func NextNonceNEQ(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldNextNonce, v))
}

// NextNonceIn applies the In predicate on the "next_nonce" field.
func NextNonceIn(vs ...int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldNextNonce, vs...))
}

// NextNonceNotIn applies the NotIn predicate on the "next_nonce" field.
func NextNonceNotIn(vs ...int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldNextNonce, vs...))
}

// NextNonceGT applies the GT predicate on the "next_nonce" field.
func NextNonceGT(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldNextNonce, v))
}

// NextNonceGTE applies the GTE predicate on the "next_nonce" field.
func NextNonceGTE(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldNextNonce, v))
}

// NextNonceLT applies the LT predicate on the "next_nonce" field.
func NextNonceLT(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldNextNonce, v))
}

// NextNonceLTE applies the LTE predicate on the "next_nonce" field.
func NextNonceLTE(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldNextNonce, v))
}

// ObservedPendingNonceEQ applies the EQ predicate on the "observed_pending_nonce" field.
func ObservedPendingNonceEQ(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldObservedPendingNonce, v))
}

// ObservedPendingNonceNEQ applies the NEQ predicate on the "observed_pending_nonce" field.
func ObservedPendingNonceNEQ(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldObservedPendingNonce, v))
}

// ObservedPendingNonceIn applies the In predicate on the "observed_pending_nonce" field.
func ObservedPendingNonceIn(vs ...int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldObservedPendingNonce, vs...))
}

// ObservedPendingNonceNotIn applies the NotIn predicate on the "observed_pending_nonce" field.
func ObservedPendingNonceNotIn(vs ...int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldObservedPendingNonce, vs...))
}

// ObservedPendingNonceGT applies the GT predicate on the "observed_pending_nonce" field.
func ObservedPendingNonceGT(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldObservedPendingNonce, v))
}

// ObservedPendingNonceGTE applies the GTE predicate on the "observed_pending_nonce" field.
func ObservedPendingNonceGTE(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldObservedPendingNonce, v))
}

// ObservedPendingNonceLT applies the LT predicate on the "observed_pending_nonce" field.
func ObservedPendingNonceLT(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldObservedPendingNonce, v))
}

// ObservedPendingNonceLTE applies the LTE predicate on the "observed_pending_nonce" field.
func ObservedPendingNonceLTE(v int64) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldObservedPendingNonce, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldContainsFold(FieldStatus, v))
}

// LeaseOwnerEQ applies the EQ predicate on the "lease_owner" field.
func LeaseOwnerEQ(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseOwnerNEQ applies the NEQ predicate on the "lease_owner" field.
func LeaseOwnerNEQ(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldLeaseOwner, v))
}

// LeaseOwnerIn applies the In predicate on the "lease_owner" field.
func LeaseOwnerIn(vs ...string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerNotIn applies the NotIn predicate on the "lease_owner" field.
func LeaseOwnerNotIn(vs ...string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerGT applies the GT predicate on the "lease_owner" field.
func LeaseOwnerGT(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldLeaseOwner, v))
}

// LeaseOwnerGTE applies the GTE predicate on the "lease_owner" field.
func LeaseOwnerGTE(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldLeaseOwner, v))
}

// LeaseOwnerLT applies the LT predicate on the "lease_owner" field.
func LeaseOwnerLT(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldLeaseOwner, v))
}

// LeaseOwnerLTE applies the LTE predicate on the "lease_owner" field.
func LeaseOwnerLTE(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldLeaseOwner, v))
}

// LeaseOwnerContains applies the Contains predicate on the "lease_owner" field.
func LeaseOwnerContains(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldContains(FieldLeaseOwner, v))
}

// LeaseOwnerHasPrefix applies the HasPrefix predicate on the "lease_owner" field.
func LeaseOwnerHasPrefix(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldHasPrefix(FieldLeaseOwner, v))
}

// LeaseOwnerHasSuffix applies the HasSuffix predicate on the "lease_owner" field.
func LeaseOwnerHasSuffix(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldHasSuffix(FieldLeaseOwner, v))
}

// LeaseOwnerIsNil applies the IsNil predicate on the "lease_owner" field.
func LeaseOwnerIsNil() predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIsNull(FieldLeaseOwner))
}

// LeaseOwnerNotNil applies the NotNil predicate on the "lease_owner" field.
func LeaseOwnerNotNil() predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotNull(FieldLeaseOwner))
}

// LeaseOwnerEqualFold applies the EqualFold predicate on the "lease_owner" field.
func LeaseOwnerEqualFold(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEqualFold(FieldLeaseOwner, v))
}

// LeaseOwnerContainsFold applies the ContainsFold predicate on the "lease_owner" field.
func LeaseOwnerContainsFold(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldContainsFold(FieldLeaseOwner, v))
}

// LeaseUntilEQ applies the EQ predicate on the "lease_until" field.
func LeaseUntilEQ(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldLeaseUntil, v))
}

// LeaseUntilNEQ applies the NEQ predicate on the "lease_until" field.
func LeaseUntilNEQ(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldLeaseUntil, v))
}

// LeaseUntilIn applies the In predicate on the "lease_until" field.
func LeaseUntilIn(vs ...time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldLeaseUntil, vs...))
}

// LeaseUntilNotIn applies the NotIn predicate on the "lease_until" field.
func LeaseUntilNotIn(vs ...time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldLeaseUntil, vs...))
}

// LeaseUntilGT applies the GT predicate on the "lease_until" field.
func LeaseUntilGT(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldLeaseUntil, v))
}

// LeaseUntilGTE applies the GTE predicate on the "lease_until" field.
func LeaseUntilGTE(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldLeaseUntil, v))
}

// LeaseUntilLT applies the LT predicate on the "lease_until" field.
func LeaseUntilLT(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldLeaseUntil, v))
}

// LeaseUntilLTE applies the LTE predicate on the "lease_until" field.
func LeaseUntilLTE(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldLeaseUntil, v))
}

// LeaseUntilIsNil applies the IsNil predicate on the "lease_until" field.
func LeaseUntilIsNil() predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIsNull(FieldLeaseUntil))
}

// LeaseUntilNotNil applies the NotNil predicate on the "lease_until" field.
func LeaseUntilNotNil() predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotNull(FieldLeaseUntil))
}

// LastReconciledAtEQ applies the EQ predicate on the "last_reconciled_at" field.
func LastReconciledAtEQ(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldLastReconciledAt, v))
}

// LastReconciledAtNEQ applies the NEQ predicate on the "last_reconciled_at" field.
func LastReconciledAtNEQ(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldLastReconciledAt, v))
}

// LastReconciledAtIn applies the In predicate on the "last_reconciled_at" field.
func LastReconciledAtIn(vs ...time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldLastReconciledAt, vs...))
}

// LastReconciledAtNotIn applies the NotIn predicate on the "last_reconciled_at" field.
func LastReconciledAtNotIn(vs ...time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldLastReconciledAt, vs...))
}

// LastReconciledAtGT applies the GT predicate on the "last_reconciled_at" field.
func LastReconciledAtGT(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldLastReconciledAt, v))
}

// LastReconciledAtGTE applies the GTE predicate on the "last_reconciled_at" field.
func LastReconciledAtGTE(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldLastReconciledAt, v))
}

// LastReconciledAtLT applies the LT predicate on the "last_reconciled_at" field.
func LastReconciledAtLT(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldLastReconciledAt, v))
}

// LastReconciledAtLTE applies the LTE predicate on the "last_reconciled_at" field.
func LastReconciledAtLTE(v time.Time) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldLastReconciledAt, v))
}

// LastReconciledAtIsNil applies the IsNil predicate on the "last_reconciled_at" field.
func LastReconciledAtIsNil() predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIsNull(FieldLastReconciledAt))
}

// LastReconciledAtNotNil applies the NotNil predicate on the "last_reconciled_at" field.
func LastReconciledAtNotNil() predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotNull(FieldLastReconciledAt))
}

// LastErrorCodeEQ applies the EQ predicate on the "last_error_code" field.
func LastErrorCodeEQ(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorCodeNEQ applies the NEQ predicate on the "last_error_code" field.
func LastErrorCodeNEQ(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldLastErrorCode, v))
}

// LastErrorCodeIn applies the In predicate on the "last_error_code" field.
func LastErrorCodeIn(vs ...string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeNotIn applies the NotIn predicate on the "last_error_code" field.
func LastErrorCodeNotIn(vs ...string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeGT applies the GT predicate on the "last_error_code" field.
func LastErrorCodeGT(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldLastErrorCode, v))
}

// LastErrorCodeGTE applies the GTE predicate on the "last_error_code" field.
func LastErrorCodeGTE(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldLastErrorCode, v))
}

// LastErrorCodeLT applies the LT predicate on the "last_error_code" field.
func LastErrorCodeLT(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldLastErrorCode, v))
}

// LastErrorCodeLTE applies the LTE predicate on the "last_error_code" field.
func LastErrorCodeLTE(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldLastErrorCode, v))
}

// LastErrorCodeContains applies the Contains predicate on the "last_error_code" field.
func LastErrorCodeContains(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldContains(FieldLastErrorCode, v))
}

// LastErrorCodeHasPrefix applies the HasPrefix predicate on the "last_error_code" field.
func LastErrorCodeHasPrefix(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldHasPrefix(FieldLastErrorCode, v))
}

// LastErrorCodeHasSuffix applies the HasSuffix predicate on the "last_error_code" field.
func LastErrorCodeHasSuffix(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldHasSuffix(FieldLastErrorCode, v))
}

// LastErrorCodeIsNil applies the IsNil predicate on the "last_error_code" field.
func LastErrorCodeIsNil() predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIsNull(FieldLastErrorCode))
}

// LastErrorCodeNotNil applies the NotNil predicate on the "last_error_code" field.
func LastErrorCodeNotNil() predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotNull(FieldLastErrorCode))
}

// LastErrorCodeEqualFold applies the EqualFold predicate on the "last_error_code" field.
func LastErrorCodeEqualFold(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEqualFold(FieldLastErrorCode, v))
}

// LastErrorCodeContainsFold applies the ContainsFold predicate on the "last_error_code" field.
func LastErrorCodeContainsFold(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldContainsFold(FieldLastErrorCode, v))
}

// LastErrorMessageEQ applies the EQ predicate on the "last_error_message" field.
func LastErrorMessageEQ(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageNEQ applies the NEQ predicate on the "last_error_message" field.
func LastErrorMessageNEQ(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageIn applies the In predicate on the "last_error_message" field.
func LastErrorMessageIn(vs ...string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageNotIn applies the NotIn predicate on the "last_error_message" field.
func LastErrorMessageNotIn(vs ...string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageGT applies the GT predicate on the "last_error_message" field.
func LastErrorMessageGT(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldLastErrorMessage, v))
}

// LastErrorMessageGTE applies the GTE predicate on the "last_error_message" field.
func LastErrorMessageGTE(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldLastErrorMessage, v))
}

// LastErrorMessageLT applies the LT predicate on the "last_error_message" field.
func LastErrorMessageLT(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldLastErrorMessage, v))
}

// LastErrorMessageLTE applies the LTE predicate on the "last_error_message" field.
func LastErrorMessageLTE(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldLastErrorMessage, v))
}

// LastErrorMessageContains applies the Contains predicate on the "last_error_message" field.
func LastErrorMessageContains(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldContains(FieldLastErrorMessage, v))
}

// LastErrorMessageHasPrefix applies the HasPrefix predicate on the "last_error_message" field.
func LastErrorMessageHasPrefix(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldHasPrefix(FieldLastErrorMessage, v))
}

// LastErrorMessageHasSuffix applies the HasSuffix predicate on the "last_error_message" field.
func LastErrorMessageHasSuffix(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldHasSuffix(FieldLastErrorMessage, v))
}

// LastErrorMessageIsNil applies the IsNil predicate on the "last_error_message" field.
func LastErrorMessageIsNil() predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIsNull(FieldLastErrorMessage))
}

// LastErrorMessageNotNil applies the NotNil predicate on the "last_error_message" field.
func LastErrorMessageNotNil() predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotNull(FieldLastErrorMessage))
}

// LastErrorMessageEqualFold applies the EqualFold predicate on the "last_error_message" field.
func LastErrorMessageEqualFold(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEqualFold(FieldLastErrorMessage, v))
}

// LastErrorMessageContainsFold applies the ContainsFold predicate on the "last_error_message" field.
func LastErrorMessageContainsFold(v string) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldContainsFold(FieldLastErrorMessage, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.FieldLTE(FieldVersion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EthereumNonceState) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EthereumNonceState) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EthereumNonceState) predicate.EthereumNonceState {
	return predicate.EthereumNonceState(sql.NotPredicates(p))
}
