// Code generated by ent, DO NOT EDIT.

package chainscancursor

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the chainscancursor type in the database.
	Label = "chain_scan_cursor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldNetwork holds the string denoting the network field in the database.
	FieldNetwork = "network"
	// FieldChainID holds the string denoting the chain_id field in the database.
	FieldChainID = "chain_id"
	// FieldFinalizedHeight holds the string denoting the finalized_height field in the database.
	FieldFinalizedHeight = "finalized_height"
	// FieldFinalizedHash holds the string denoting the finalized_hash field in the database.
	FieldFinalizedHash = "finalized_hash"
	// FieldLeaseOwner holds the string denoting the lease_owner field in the database.
	FieldLeaseOwner = "lease_owner"
	// FieldLeaseUntil holds the string denoting the lease_until field in the database.
	FieldLeaseUntil = "lease_until"
	// FieldHealth holds the string denoting the health field in the database.
	FieldHealth = "health"
	// FieldLastSuccessAt holds the string denoting the last_success_at field in the database.
	FieldLastSuccessAt = "last_success_at"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// FieldLastErrorMessage holds the string denoting the last_error_message field in the database.
	FieldLastErrorMessage = "last_error_message"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// Table holds the table name of the chainscancursor in the database.
	Table = "chain_scan_cursors"
)

// Columns holds all SQL columns for chainscancursor fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldNetwork,
	FieldChainID,
	FieldFinalizedHeight,
	FieldFinalizedHash,
	FieldLeaseOwner,
	FieldLeaseUntil,
	FieldHealth,
	FieldLastSuccessAt,
	FieldLastErrorCode,
	FieldLastErrorMessage,
	FieldVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NetworkValidator is a validator for the "network" field. It is called by the builders before save.
	NetworkValidator func(string) error
	// ChainIDValidator is a validator for the "chain_id" field. It is called by the builders before save.
	ChainIDValidator func(int64) error
	// DefaultFinalizedHeight holds the default value on creation for the "finalized_height" field.
	DefaultFinalizedHeight int64
	// FinalizedHeightValidator is a validator for the "finalized_height" field. It is called by the builders before save.
	FinalizedHeightValidator func(int64) error
	// DefaultFinalizedHash holds the default value on creation for the "finalized_hash" field.
	DefaultFinalizedHash string
	// FinalizedHashValidator is a validator for the "finalized_hash" field. It is called by the builders before save.
	FinalizedHashValidator func(string) error
	// LeaseOwnerValidator is a validator for the "lease_owner" field. It is called by the builders before save.
	LeaseOwnerValidator func(string) error
	// DefaultHealth holds the default value on creation for the "health" field.
	DefaultHealth string
	// HealthValidator is a validator for the "health" field. It is called by the builders before save.
	HealthValidator func(string) error
	// LastErrorCodeValidator is a validator for the "last_error_code" field. It is called by the builders before save.
	LastErrorCodeValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int) error
)

// OrderOption defines the ordering options for the ChainScanCursor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNetwork orders the results by the network field.
func ByNetwork(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetwork, opts...).ToFunc()
}

// ByChainID orders the results by the chain_id field.
func ByChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChainID, opts...).ToFunc()
}

// ByFinalizedHeight orders the results by the finalized_height field.
func ByFinalizedHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinalizedHeight, opts...).ToFunc()
}

// ByFinalizedHash orders the results by the finalized_hash field.
func ByFinalizedHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinalizedHash, opts...).ToFunc()
}

// ByLeaseOwner orders the results by the lease_owner field.
func ByLeaseOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseOwner, opts...).ToFunc()
}

// ByLeaseUntil orders the results by the lease_until field.
func ByLeaseUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseUntil, opts...).ToFunc()
}

// ByHealth orders the results by the health field.
func ByHealth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealth, opts...).ToFunc()
}

// ByLastSuccessAt orders the results by the last_success_at field.
func ByLastSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSuccessAt, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}

// ByLastErrorMessage orders the results by the last_error_message field.
func ByLastErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorMessage, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}
