// Code generated by ent, DO NOT EDIT.

package chainscancursor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldUpdatedAt, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldNetwork, v))
}

// ChainID applies equality check predicate on the "chain_id" field. It's identical to ChainIDEQ.
func ChainID(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldChainID, v))
}

// FinalizedHeight applies equality check predicate on the "finalized_height" field. It's identical to FinalizedHeightEQ.
func FinalizedHeight(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldFinalizedHeight, v))
}

// FinalizedHash applies equality check predicate on the "finalized_hash" field. It's identical to FinalizedHashEQ.
func FinalizedHash(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldFinalizedHash, v))
}

// LeaseOwner applies equality check predicate on the "lease_owner" field. It's identical to LeaseOwnerEQ.
func LeaseOwner(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseUntil applies equality check predicate on the "lease_until" field. It's identical to LeaseUntilEQ.
func LeaseUntil(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldLeaseUntil, v))
}

// Health applies equality check predicate on the "health" field. It's identical to HealthEQ.
func Health(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldHealth, v))
}

// LastSuccessAt applies equality check predicate on the "last_success_at" field. It's identical to LastSuccessAtEQ.
func LastSuccessAt(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastErrorCode applies equality check predicate on the "last_error_code" field. It's identical to LastErrorCodeEQ.
func LastErrorCode(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorMessage applies equality check predicate on the "last_error_message" field. It's identical to LastErrorMessageEQ.
func LastErrorMessage(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldLastErrorMessage, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldUpdatedAt, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContainsFold(FieldNetwork, v))
}

// ChainIDEQ applies the EQ predicate on the "chain_id" field.
func ChainIDEQ(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldChainID, v))
}

// ChainIDNEQ applies the NEQ predicate on the "chain_id" field.
func ChainIDNEQ(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldChainID, v))
}

// ChainIDIn applies the In predicate on the "chain_id" field.
func ChainIDIn(vs ...int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldChainID, vs...))
}

// ChainIDNotIn applies the NotIn predicate on the "chain_id" field.
func ChainIDNotIn(vs ...int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldChainID, vs...))
}

// ChainIDGT applies the GT predicate on the "chain_id" field.
func ChainIDGT(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldChainID, v))
}

// ChainIDGTE applies the GTE predicate on the "chain_id" field.
func ChainIDGTE(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldChainID, v))
}

// ChainIDLT applies the LT predicate on the "chain_id" field.
func ChainIDLT(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldChainID, v))
}

// ChainIDLTE applies the LTE predicate on the "chain_id" field.
func ChainIDLTE(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldChainID, v))
}

// FinalizedHeightEQ applies the EQ predicate on the "finalized_height" field.
func FinalizedHeightEQ(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldFinalizedHeight, v))
}

// FinalizedHeightNEQ applies the NEQ predicate on the "finalized_height" field.
func FinalizedHeightNEQ(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldFinalizedHeight, v))
}

// FinalizedHeightIn applies the In predicate on the "finalized_height" field.
func FinalizedHeightIn(vs ...int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldFinalizedHeight, vs...))
}

// FinalizedHeightNotIn applies the NotIn predicate on the "finalized_height" field.
func FinalizedHeightNotIn(vs ...int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldFinalizedHeight, vs...))
}

// FinalizedHeightGT applies the GT predicate on the "finalized_height" field.
func FinalizedHeightGT(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldFinalizedHeight, v))
}

// FinalizedHeightGTE applies the GTE predicate on the "finalized_height" field.
func FinalizedHeightGTE(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldFinalizedHeight, v))
}

// FinalizedHeightLT applies the LT predicate on the "finalized_height" field.
func FinalizedHeightLT(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldFinalizedHeight, v))
}

// FinalizedHeightLTE applies the LTE predicate on the "finalized_height" field.
func FinalizedHeightLTE(v int64) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldFinalizedHeight, v))
}

// FinalizedHashEQ applies the EQ predicate on the "finalized_hash" field.
func FinalizedHashEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldFinalizedHash, v))
}

// FinalizedHashNEQ applies the NEQ predicate on the "finalized_hash" field.
func FinalizedHashNEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldFinalizedHash, v))
}

// FinalizedHashIn applies the In predicate on the "finalized_hash" field.
func FinalizedHashIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldFinalizedHash, vs...))
}

// FinalizedHashNotIn applies the NotIn predicate on the "finalized_hash" field.
func FinalizedHashNotIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldFinalizedHash, vs...))
}

// FinalizedHashGT applies the GT predicate on the "finalized_hash" field.
func FinalizedHashGT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldFinalizedHash, v))
}

// FinalizedHashGTE applies the GTE predicate on the "finalized_hash" field.
func FinalizedHashGTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldFinalizedHash, v))
}

// FinalizedHashLT applies the LT predicate on the "finalized_hash" field.
func FinalizedHashLT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldFinalizedHash, v))
}

// FinalizedHashLTE applies the LTE predicate on the "finalized_hash" field.
func FinalizedHashLTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldFinalizedHash, v))
}

// FinalizedHashContains applies the Contains predicate on the "finalized_hash" field.
func FinalizedHashContains(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContains(FieldFinalizedHash, v))
}

// FinalizedHashHasPrefix applies the HasPrefix predicate on the "finalized_hash" field.
func FinalizedHashHasPrefix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasPrefix(FieldFinalizedHash, v))
}

// FinalizedHashHasSuffix applies the HasSuffix predicate on the "finalized_hash" field.
func FinalizedHashHasSuffix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasSuffix(FieldFinalizedHash, v))
}

// FinalizedHashEqualFold applies the EqualFold predicate on the "finalized_hash" field.
func FinalizedHashEqualFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEqualFold(FieldFinalizedHash, v))
}

// FinalizedHashContainsFold applies the ContainsFold predicate on the "finalized_hash" field.
func FinalizedHashContainsFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContainsFold(FieldFinalizedHash, v))
}

// LeaseOwnerEQ applies the EQ predicate on the "lease_owner" field.
func LeaseOwnerEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseOwnerNEQ applies the NEQ predicate on the "lease_owner" field.
func LeaseOwnerNEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldLeaseOwner, v))
}

// LeaseOwnerIn applies the In predicate on the "lease_owner" field.
func LeaseOwnerIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerNotIn applies the NotIn predicate on the "lease_owner" field.
func LeaseOwnerNotIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerGT applies the GT predicate on the "lease_owner" field.
func LeaseOwnerGT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldLeaseOwner, v))
}

// LeaseOwnerGTE applies the GTE predicate on the "lease_owner" field.
func LeaseOwnerGTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldLeaseOwner, v))
}

// LeaseOwnerLT applies the LT predicate on the "lease_owner" field.
func LeaseOwnerLT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldLeaseOwner, v))
}

// LeaseOwnerLTE applies the LTE predicate on the "lease_owner" field.
func LeaseOwnerLTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldLeaseOwner, v))
}

// LeaseOwnerContains applies the Contains predicate on the "lease_owner" field.
func LeaseOwnerContains(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContains(FieldLeaseOwner, v))
}

// LeaseOwnerHasPrefix applies the HasPrefix predicate on the "lease_owner" field.
func LeaseOwnerHasPrefix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasPrefix(FieldLeaseOwner, v))
}

// LeaseOwnerHasSuffix applies the HasSuffix predicate on the "lease_owner" field.
func LeaseOwnerHasSuffix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasSuffix(FieldLeaseOwner, v))
}

// LeaseOwnerIsNil applies the IsNil predicate on the "lease_owner" field.
func LeaseOwnerIsNil() predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIsNull(FieldLeaseOwner))
}

// LeaseOwnerNotNil applies the NotNil predicate on the "lease_owner" field.
func LeaseOwnerNotNil() predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotNull(FieldLeaseOwner))
}

// LeaseOwnerEqualFold applies the EqualFold predicate on the "lease_owner" field.
func LeaseOwnerEqualFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEqualFold(FieldLeaseOwner, v))
}

// LeaseOwnerContainsFold applies the ContainsFold predicate on the "lease_owner" field.
func LeaseOwnerContainsFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContainsFold(FieldLeaseOwner, v))
}

// LeaseUntilEQ applies the EQ predicate on the "lease_until" field.
func LeaseUntilEQ(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldLeaseUntil, v))
}

// LeaseUntilNEQ applies the NEQ predicate on the "lease_until" field.
func LeaseUntilNEQ(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldLeaseUntil, v))
}

// LeaseUntilIn applies the In predicate on the "lease_until" field.
func LeaseUntilIn(vs ...time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldLeaseUntil, vs...))
}

// LeaseUntilNotIn applies the NotIn predicate on the "lease_until" field.
func LeaseUntilNotIn(vs ...time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldLeaseUntil, vs...))
}

// LeaseUntilGT applies the GT predicate on the "lease_until" field.
func LeaseUntilGT(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldLeaseUntil, v))
}

// LeaseUntilGTE applies the GTE predicate on the "lease_until" field.
func LeaseUntilGTE(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldLeaseUntil, v))
}

// LeaseUntilLT applies the LT predicate on the "lease_until" field.
func LeaseUntilLT(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldLeaseUntil, v))
}

// LeaseUntilLTE applies the LTE predicate on the "lease_until" field.
func LeaseUntilLTE(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldLeaseUntil, v))
}

// LeaseUntilIsNil applies the IsNil predicate on the "lease_until" field.
func LeaseUntilIsNil() predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIsNull(FieldLeaseUntil))
}

// LeaseUntilNotNil applies the NotNil predicate on the "lease_until" field.
func LeaseUntilNotNil() predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotNull(FieldLeaseUntil))
}

// HealthEQ applies the EQ predicate on the "health" field.
func HealthEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldHealth, v))
}

// HealthNEQ applies the NEQ predicate on the "health" field.
func HealthNEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldHealth, v))
}

// HealthIn applies the In predicate on the "health" field.
func HealthIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldHealth, vs...))
}

// HealthNotIn applies the NotIn predicate on the "health" field.
func HealthNotIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldHealth, vs...))
}

// HealthGT applies the GT predicate on the "health" field.
func HealthGT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldHealth, v))
}

// HealthGTE applies the GTE predicate on the "health" field.
func HealthGTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldHealth, v))
}

// HealthLT applies the LT predicate on the "health" field.
func HealthLT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldHealth, v))
}

// HealthLTE applies the LTE predicate on the "health" field.
func HealthLTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldHealth, v))
}

// HealthContains applies the Contains predicate on the "health" field.
func HealthContains(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContains(FieldHealth, v))
}

// HealthHasPrefix applies the HasPrefix predicate on the "health" field.
func HealthHasPrefix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasPrefix(FieldHealth, v))
}

// HealthHasSuffix applies the HasSuffix predicate on the "health" field.
func HealthHasSuffix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasSuffix(FieldHealth, v))
}

// HealthEqualFold applies the EqualFold predicate on the "health" field.
func HealthEqualFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEqualFold(FieldHealth, v))
}

// HealthContainsFold applies the ContainsFold predicate on the "health" field.
func HealthContainsFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContainsFold(FieldHealth, v))
}

// LastSuccessAtEQ applies the EQ predicate on the "last_success_at" field.
func LastSuccessAtEQ(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtNEQ applies the NEQ predicate on the "last_success_at" field.
func LastSuccessAtNEQ(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtIn applies the In predicate on the "last_success_at" field.
func LastSuccessAtIn(vs ...time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtNotIn applies the NotIn predicate on the "last_success_at" field.
func LastSuccessAtNotIn(vs ...time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtGT applies the GT predicate on the "last_success_at" field.
func LastSuccessAtGT(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldLastSuccessAt, v))
}

// LastSuccessAtGTE applies the GTE predicate on the "last_success_at" field.
func LastSuccessAtGTE(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldLastSuccessAt, v))
}

// LastSuccessAtLT applies the LT predicate on the "last_success_at" field.
func LastSuccessAtLT(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldLastSuccessAt, v))
}

// LastSuccessAtLTE applies the LTE predicate on the "last_success_at" field.
func LastSuccessAtLTE(v time.Time) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldLastSuccessAt, v))
}

// LastSuccessAtIsNil applies the IsNil predicate on the "last_success_at" field.
func LastSuccessAtIsNil() predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIsNull(FieldLastSuccessAt))
}

// LastSuccessAtNotNil applies the NotNil predicate on the "last_success_at" field.
func LastSuccessAtNotNil() predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotNull(FieldLastSuccessAt))
}

// LastErrorCodeEQ applies the EQ predicate on the "last_error_code" field.
func LastErrorCodeEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorCodeNEQ applies the NEQ predicate on the "last_error_code" field.
func LastErrorCodeNEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldLastErrorCode, v))
}

// LastErrorCodeIn applies the In predicate on the "last_error_code" field.
func LastErrorCodeIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeNotIn applies the NotIn predicate on the "last_error_code" field.
func LastErrorCodeNotIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeGT applies the GT predicate on the "last_error_code" field.
func LastErrorCodeGT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldLastErrorCode, v))
}

// LastErrorCodeGTE applies the GTE predicate on the "last_error_code" field.
func LastErrorCodeGTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldLastErrorCode, v))
}

// LastErrorCodeLT applies the LT predicate on the "last_error_code" field.
func LastErrorCodeLT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldLastErrorCode, v))
}

// LastErrorCodeLTE applies the LTE predicate on the "last_error_code" field.
func LastErrorCodeLTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldLastErrorCode, v))
}

// LastErrorCodeContains applies the Contains predicate on the "last_error_code" field.
func LastErrorCodeContains(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContains(FieldLastErrorCode, v))
}

// LastErrorCodeHasPrefix applies the HasPrefix predicate on the "last_error_code" field.
func LastErrorCodeHasPrefix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasPrefix(FieldLastErrorCode, v))
}

// LastErrorCodeHasSuffix applies the HasSuffix predicate on the "last_error_code" field.
func LastErrorCodeHasSuffix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasSuffix(FieldLastErrorCode, v))
}

// LastErrorCodeIsNil applies the IsNil predicate on the "last_error_code" field.
func LastErrorCodeIsNil() predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIsNull(FieldLastErrorCode))
}

// LastErrorCodeNotNil applies the NotNil predicate on the "last_error_code" field.
func LastErrorCodeNotNil() predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotNull(FieldLastErrorCode))
}

// LastErrorCodeEqualFold applies the EqualFold predicate on the "last_error_code" field.
func LastErrorCodeEqualFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEqualFold(FieldLastErrorCode, v))
}

// LastErrorCodeContainsFold applies the ContainsFold predicate on the "last_error_code" field.
func LastErrorCodeContainsFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContainsFold(FieldLastErrorCode, v))
}

// LastErrorMessageEQ applies the EQ predicate on the "last_error_message" field.
func LastErrorMessageEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageNEQ applies the NEQ predicate on the "last_error_message" field.
func LastErrorMessageNEQ(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageIn applies the In predicate on the "last_error_message" field.
func LastErrorMessageIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageNotIn applies the NotIn predicate on the "last_error_message" field.
func LastErrorMessageNotIn(vs ...string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageGT applies the GT predicate on the "last_error_message" field.
func LastErrorMessageGT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldLastErrorMessage, v))
}

// LastErrorMessageGTE applies the GTE predicate on the "last_error_message" field.
func LastErrorMessageGTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldLastErrorMessage, v))
}

// LastErrorMessageLT applies the LT predicate on the "last_error_message" field.
func LastErrorMessageLT(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldLastErrorMessage, v))
}

// LastErrorMessageLTE applies the LTE predicate on the "last_error_message" field.
func LastErrorMessageLTE(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldLastErrorMessage, v))
}

// LastErrorMessageContains applies the Contains predicate on the "last_error_message" field.
func LastErrorMessageContains(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContains(FieldLastErrorMessage, v))
}

// LastErrorMessageHasPrefix applies the HasPrefix predicate on the "last_error_message" field.
func LastErrorMessageHasPrefix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasPrefix(FieldLastErrorMessage, v))
}

// LastErrorMessageHasSuffix applies the HasSuffix predicate on the "last_error_message" field.
func LastErrorMessageHasSuffix(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldHasSuffix(FieldLastErrorMessage, v))
}

// LastErrorMessageIsNil applies the IsNil predicate on the "last_error_message" field.
func LastErrorMessageIsNil() predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIsNull(FieldLastErrorMessage))
}

// LastErrorMessageNotNil applies the NotNil predicate on the "last_error_message" field.
func LastErrorMessageNotNil() predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotNull(FieldLastErrorMessage))
}

// LastErrorMessageEqualFold applies the EqualFold predicate on the "last_error_message" field.
func LastErrorMessageEqualFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEqualFold(FieldLastErrorMessage, v))
}

// LastErrorMessageContainsFold applies the ContainsFold predicate on the "last_error_message" field.
func LastErrorMessageContainsFold(v string) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldContainsFold(FieldLastErrorMessage, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.FieldLTE(FieldVersion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChainScanCursor) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChainScanCursor) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChainScanCursor) predicate.ChainScanCursor {
	return predicate.ChainScanCursor(sql.NotPredicates(p))
}
