// Code generated by ent, DO NOT EDIT.

package walletderivationcursor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldUpdatedAt, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldNetwork, v))
}

// NextIndex applies equality check predicate on the "next_index" field. It's identical to NextIndexEQ.
func NextIndex(v int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldNextIndex, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLTE(FieldUpdatedAt, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldContainsFold(FieldNetwork, v))
}

// NextIndexEQ applies the EQ predicate on the "next_index" field.
func NextIndexEQ(v int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldNextIndex, v))
}

// NextIndexNEQ applies the NEQ predicate on the "next_index" field.
func NextIndexNEQ(v int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNEQ(FieldNextIndex, v))
}

// NextIndexIn applies the In predicate on the "next_index" field.
func NextIndexIn(vs ...int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldIn(FieldNextIndex, vs...))
}

// NextIndexNotIn applies the NotIn predicate on the "next_index" field.
func NextIndexNotIn(vs ...int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNotIn(FieldNextIndex, vs...))
}

// NextIndexGT applies the GT predicate on the "next_index" field.
func NextIndexGT(v int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGT(FieldNextIndex, v))
}

// NextIndexGTE applies the GTE predicate on the "next_index" field.
func NextIndexGTE(v int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGTE(FieldNextIndex, v))
}

// NextIndexLT applies the LT predicate on the "next_index" field.
func NextIndexLT(v int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLT(FieldNextIndex, v))
}

// NextIndexLTE applies the LTE predicate on the "next_index" field.
func NextIndexLTE(v int64) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLTE(FieldNextIndex, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.FieldLTE(FieldVersion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WalletDerivationCursor) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WalletDerivationCursor) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WalletDerivationCursor) predicate.WalletDerivationCursor {
	return predicate.WalletDerivationCursor(sql.NotPredicates(p))
}
